return {
    { type = "Animation", name = "Gada z pozycji", id = "1", group = "GROUP", character = "" },
    { type = "Animation", name = "Szatanska_fura_z_wlaczonym_silnikiem_stoi_pod_wiezieniem_na_Rakowieckiej", id = "2" },
    { type = "Animation", name = "Winyl_siedzi_petla", id = "3" },
    { type = "Animation", name = "Winyl_gada_1", id = "4" },
    { type = "Animation", name = "Winyl_gada_2", id = "5" },
    { type = "Animation", name = "Fred_Wychodzi_z_grobu", id = "6" },
    { type = "Animation", name = "Fred_rozglada_sie_niepewnie", id = "7" },
    { type = "Animation", name = "FZB_Gada_na_polanie", id = "8" },
    { type = "Animation", name = "Fred_przestraszyl_sie_z_G", id = "9" },
    { type = "Animation", name = "Fred_mowi_zaskoczony_z_G", id = "10" },
    { type = "Animation", name = "Fred_mowi_oslupialy_z_G", id = "11" },
    { type = "Animation", name = "Fred_przestraszyl_sie_z_C", id = "12" },
    { type = "Animation", name = "Fred_mowi_zaskoczony_z_C", id = "13" },
    { type = "Animation", name = "Fred_mowi_oslupialy_z_C", id = "14" },
    { type = "Animation", name = "Fred_wyjmuje_pistolet_i_mierzy_w_FZB", id = "15" },
    { type = "Animation", name = "FZB_uzywa_magii_aby_udowodnic_Fredowi_swa_sile", id = "16" },
    { type = "Animation", name = "Fred_budzi_sie_na_polanie", id = "17" },
    { type = "Animation", name = "FZB_mowi_wskazujac_reka_grob_na_polanie", id = "18" },
    { type = "Animation", name = "Fred_mowi_zrezygnowany_z_C", id = "19" },
    { type = "Animation", name = "FZB_gada_po_czym_rozplywa_sie_w_klebach_dymu", id = "20" },
    { type = "Animation", name = "Fred_macha_w_rezygnacji_reka_z_C", id = "21" },
    { type = "Animation", name = "Stroz_przystepuje_do_rozmowy", id = "22" },
    { type = "Animation", name = "Stroz_Rozmawia_1", id = "23" },
    { type = "Animation", name = "Stroz_Rozmawia_2", id = "24" },
    { type = "Animation", name = "Stroz_drapie_sie_w_glowe", id = "25" },
    { type = "Animation", name = "Stroz_Stuga_patyk", id = "26" },
    { type = "Animation", name = "Diler_symuluje_kaszlniecie", id = "27" },
    { type = "Animation", name = "Diler_przerazony", id = "28" },
    { type = "Animation", name = "Hotdogman_mowi", id = "29" },
    { type = "Animation", name = "Hotdogman_potracony", id = "30" },
    { type = "Animation", name = "Hotdogman_sprzedaje", id = "31" },
    { type = "Animation", name = "Flower_robi_ewolucje_na_rampie", id = "32" },
    { type = "Animation", name = "Flower_mowi_na_rampie", id = "33" },
    { type = "Animation", name = "Flower_robi_orla", id = "34" },
    { type = "Animation", name = "Flower_jeczy", id = "35" },
    { type = "Animation", name = "Flower_wstaje_i_idzie", id = "36" },
    { type = "Animation", name = "Ochroniarz_stoi", id = "37" },
    { type = "Animation", name = "Ochroniarz_gada", id = "38" },
    { type = "Animation", name = "Fred_opatruje_Flowera", id = "39" },
    { type = "Animation", name = "Fred_przeglada_mape", id = "40" },
    { type = "Animation", name = "Fred_wzrusza_ramionami", id = "41" },
    { type = "Animation", name = "Dealer_ucieka", id = "42" },
    { type = "Animation", name = "Dziadek_karmi_golebie", id = "43" },
    { type = "Animation", name = "Dziadek_petla_ruchu", id = "44" },
    { type = "Animation", name = "Dziadek_mowi", id = "45" },
    { type = "Animation", name = "Flower_gada_obandazowany", id = "46" },
    { type = "Animation", name = "Fred_Gadanie_normalne_A", id = "47", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_B", id = "48", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_C", id = "49", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_D", id = "50", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_E", id = "51", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_F", id = "52", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_G", id = "53", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Gadanie_normalne_H", id = "54", group = "Gada z pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_Rozglada_sie_i_gada", id = "55" },
    { type = "Animation", name = "Fred_gada_zrezygnowany", id = "56" },
    { type = "Animation", name = "Fred_celuje_w_ekran", id = "57" },
    { type = "Animation", name = "Fred_zastanawia_sie_podczas_gry", id = "58" },
    { type = "Animation", name = "Fred_popisuje_sie", id = "59" },
    { type = "Animation", name = "Fred_poblazliwie_odmawia_graczowi", id = "60" },
    { type = "Animation", name = "Fred_mysli_przebiegle", id = "61" },
    { type = "Animation", name = "Fred_patrzy_jak_kretyn_w_lewo", id = "62" },
    { type = "Animation", name = "Fred_patrzy_jak_kretyn_w_prawo", id = "63" },
    { type = "Animation", name = "Fred_sie_boi_w_lewo", id = "64" },
    { type = "Animation", name = "Fred_sie_boi_w_prawo", id = "65" },
    { type = "Animation", name = "Fred_uzywa_pilota", id = "66" },
    { type = "Animation", name = "Fred_bada_zarosla", id = "67" },
    { type = "Animation", name = "Fred_lapie_motylki_w_lewo", id = "68" },
    { type = "Animation", name = "Fred_lapie_motylki_w_prawo", id = "69" },
    { type = "Animation", name = "FZB_Znika", id = "70" },
    { type = "Animation", name = "Fred_sie_smieje", id = "71" },
    { type = "Animation", name = "Fred_sie_smieje_bardzo", id = "72" },
    { type = "Animation", name = "Fred_konsternacja", id = "73" },
    { type = "Animation", name = "Fred_Nieme_zdziwienie", id = "74" },
    { type = "Animation", name = "Fred_wchodzi_do_budki", id = "75" },
    { type = "Animation", name = "Fred_wychodzi_z_budki", id = "76" },
    { type = "Animation", name = "Fred_podnosi_hotdoga", id = "77" },
    { type = "Animation", name = "Fred_przystawia_dealerowi_giwere", id = "78" },
    { type = "Animation", name = "Fred_opuszcza_giwere", id = "79" },
    { type = "Animation", name = "Fred_siada_na_lawce", id = "81" },
    { type = "Animation", name = "Fred_siedzi_na_lawce", id = "82" },
    { type = "Animation", name = "Fred_gada_siedzac_na_lawce", id = "83" },
    { type = "Animation", name = "Fred_wstaje_z_lawki", id = "84" },
    { type = "Animation", name = "Fred_odmowa", id = "85" },
    { type = "Animation", name = "Fred_kategoryczna_odmowa", id = "86" },
    { type = "Animation", name = "Fred_grzebie_w_smietniku_na_parkingu", id = "87" },
    { type = "Animation", name = "Fred_grzebie_w_apteczce", id = "88" },
    { type = "Animation", name = "FZB_przyjmuje_poze_szlenca", id = "89" },
    { type = "Animation", name = "FZB_pokazuje_zdjecia", id = "90" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_A", id = "91", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_B", id = "92", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_C", id = "93", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_D", id = "94", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_E", id = "95", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_F", id = "96", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_G", id = "97", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_Gadanie_normalne_H", id = "98", group = "Gada z pozycji", character = "Grucha" },
    { type = "Animation", name = "Grucha_mowi_z_zalozonymi_rekami", id = "99" },
    { type = "Animation", name = "Grucha_wychodzi_z_wiezienia", id = "100" },
    { type = "Animation", name = "Grucha_przerazenie_na_widok_Freda", id = "101" },
    { type = "Animation", name = "Grucha_konsternacja", id = "102" },
    { type = "Animation", name = "Grucha_Nieme_zdziwienie", id = "103" },
    { type = "Animation", name = "Grucha_odmowa", id = "104" },
    { type = "Animation", name = "Grucha_kategoryczna_odmowa", id = "105" },
    { type = "Animation", name = "Grucha_siada_na_lawce", id = "106" },
    { type = "Animation", name = "Grucha_gada_na_lawce", id = "107" },
    { type = "Animation", name = "Grucha_wstaje_z_lawki", id = "108" },
    { type = "Animation", name = "Grucha_ironizuje_C", id = "109" },
    { type = "Animation", name = "Grucha_stoi_i_sie_drapie", id = "110" },
    { type = "Animation", name = "Grucha_rozglada_sie", id = "111" },
    { type = "Animation", name = "Grucha_ziewa", id = "112" },
    { type = "Animation", name = "Grucha_odmawia_B", id = "113" },
    { type = "Animation", name = "Grucha_odmawia_C", id = "114" },
    { type = "Animation", name = "Grucha_wzrusza_ramionami", id = "115" },
    { type = "Animation", name = "Grucha_mowi_wzburzony", id = "116" },
    { type = "Animation", name = "Grucha_pali_fajka", id = "117" },
    { type = "Animation", name = "Grucha_kuli_sie_w_sobie_na_widok_wypadku_Flowers", id = "118" },
    { type = "Animation", name = "Grucha_sie_smieje", id = "119" },
    { type = "Animation", name = "Grucha_rozmawia_przez_telefon", id = "120" },
    { type = "Animation", name = "Matka_petla_ruchu", id = "121" },
    { type = "Animation", name = "Matka_mowi", id = "122" },
    { type = "Animation", name = "PiesStroza_spi", id = "123" },
    { type = "Animation", name = "PiesStroza_warczy", id = "124" },
    { type = "Animation", name = "ZIOM1_siedzi_na_lawce", id = "125" },
    { type = "Animation", name = "ZIOM1_mowi", id = "126" },
    { type = "Animation", name = "ZIOM2_siedzi_na_lawce", id = "127" },
    { type = "Animation", name = "ZIOM2_mowi", id = "128" },
    { type = "Animation", name = "ZIOM2_wstaje_z_lawki_i_idzie", id = "129" },
    { type = "Animation", name = "ZIOM3_siedzi_na_lawce", id = "130" },
    { type = "Animation", name = "ZIOM3_mowi", id = "131" },
    { type = "Animation", name = "ZIOM3_fristajluje", id = "132" },
    { type = "Animation", name = "ZIOM2_stoi_i_przysluchuje_sie", id = "133" },
    { type = "Animation", name = "ZIOM2_stoi_i_mowi", id = "134" },
    { type = "Animation", name = "ZIOM2_opuszcza_Parking", id = "135" },
    { type = "Animation", name = "ZIOM2_opuszcza_Skejtpark", id = "136" },
    { type = "Animation", name = "FZB_pojawia_sie_w_dymku", id = "137" },
    { type = "Animation", name = "Grucha_przerazenie_w_lewo", id = "138" },
    { type = "Animation", name = "Grucha_przerazenie_w_prawo", id = "139" },
    { type = "Animation", name = "Fred_zwraca_sie_do_gracza_teatralnym_szeptem", id = "140" },
    { type = "Animation", name = "Grucha_mowi_pod_nosem_C", id = "141" },
    { type = "Animation", name = "Grucha_odmawia_C", id = "142" },
    { type = "Animation", name = "Grucha_ironizuje_G", id = "143" },
    { type = "Animation", name = "Fred_mowi_zaklopotany_C", id = "144" },
    { type = "Animation", name = "Fred_mowi_zaklopotany_C", id = "145" },
    { type = "Animation", name = "Matka_z_dzieckiem_rozmawia_podejrzliwie", id = "146" },
    { type = "Animation", name = "Fred_mowi_zaklopotany_G", id = "147" },
    { type = "Animation", name = "Grucha_straszy_dziadka_F", id = "148" },
    { type = "Animation", name = "Fred_puka_w_szybke", id = "149" },
    { type = "Animation", name = "Opuszczanie_szybki", id = "150" },
    { type = "Animation", name = "Zamykanie_szybki", id = "151" },
    { type = "Animation", name = "Fred_wyskakuje_z_krzakow", id = "152" },
    { type = "Animation", name = "Grucha_mowi_wzburzony_w_lewo", id = "153" },
    { type = "Animation", name = "Diler_obrywa_od_Gruchy", id = "154" },
    { type = "Animation", name = "Fred_tlucze_Dilera_pistoletem", id = "155" },
    { type = "Animation", name = "Diler_obrywa_od_Freda", id = "156" },
    { type = "Animation", name = "Diler_wypluwa_zeby", id = "157" },
    { type = "Animation", name = "Grucha_patrzy_zdziwiony_na_Freda_C", id = "158" },
    { type = "Animation", name = "Fred_patrzy_zdziwiony_G", id = "159" },
    { type = "Animation", name = "Diler_kuli_sie_panicznie_przed_Grucha", id = "160" },
    { type = "Animation", name = "Grucha_mowi_przez_ramie_w_kierunku_C", id = "161" },
    { type = "Animation", name = "Fred_mowi_z_giwera_w_lewo", id = "162" },
    { type = "Animation", name = "Fred_mowi_z_giwera_w_prawo", id = "163" },
    { type = "Animation", name = "Diler_ucieka_z_boiska", id = "164" },
    { type = "Animation", name = "Grucha_slucha_plyt", id = "165" },
    { type = "Animation", name = "Elektronik_sprzedaje", id = "166" },
    { type = "Animation", name = "Elektronik_rozmawia", id = "167" },
    { type = "Animation", name = "Elektronik_podaje_golarke", id = "168" },
    { type = "Animation", name = "Tekstylia_sprzedaje", id = "169" },
    { type = "Animation", name = "Tekstylia_rozmawia_1", id = "170" },
    { type = "Animation", name = "Tekstylia_rozmawia_2", id = "171" },
    { type = "Animation", name = "Tekstylia_daje_Fredowi_dres", id = "172" },
    { type = "Animation", name = "Licealisci_rozmawiaja", id = "173" },
    { type = "Animation", name = "Licealisci_okupuja_konsole", id = "174" },
    { type = "Animation", name = "Licealisci_graja_z_Grucha", id = "175" },
    { type = "Animation", name = "Grucha_gra_z_Licealistami", id = "176" },
    { type = "Animation", name = "Grucha_bierze_od_Freda_kartke_z_telefonem", id = "177" },
    { type = "Animation", name = "Diler_mowi_z_offu", id = "178" },
    { type = "Animation", name = "Nuke_stoi", id = "179" },
    { type = "Animation", name = "Nuke_rozmawia_przed_przegrana", id = "180" },
    { type = "Animation", name = "Nuke_rozmawia_po_przegranej", id = "181" },
    { type = "Animation", name = "Nuke_gra_w_Tonka", id = "182" },
    { type = "Animation", name = "Nuke_wygrywa", id = "183" },
    { type = "Animation", name = "Nuke_przegrywa", id = "184" },
    { type = "Animation", name = "Fred_gra_w_Tonka", id = "185" },
    { type = "Animation", name = "Fred_przegrywa_w_Tonka", id = "186" },
    { type = "Animation", name = "Grucha_wygrywa_w_Tonka", id = "187" },
    { type = "Animation", name = "Nuke_daje_Fredowi_kartke", id = "188" },
    { type = "Animation", name = "Blondyna_macha_nozka", id = "189" },
    { type = "Animation", name = "Blondyna_rozmawia_1", id = "190" },
    { type = "Animation", name = "Blondyna_rozmawia_2", id = "191" },
    { type = "Animation", name = "Nerd_oddycha", id = "192" },
    { type = "Animation", name = "Nerd_rozmawia", id = "193" },
    { type = "Animation", name = "Perla_pali_szluga", id = "194" },
    { type = "Animation", name = "Perla_rozmawia_z_chlopakami", id = "195" },
    { type = "Animation", name = "Perla_rozmawia_po_wypadku", id = "196" },
    { type = "Animation", name = "Szypula_popija_piwo", id = "197" },
    { type = "Animation", name = "Szypula_rozmawia_z_chlopakami", id = "198" },
    { type = "Animation", name = "Chrzastek_puszcza_latawiec", id = "199" },
    { type = "Animation", name = "Chrzastek_rozwija_sznurek", id = "200" },
    { type = "Animation", name = "Chrzastek_bierze_od_Freda_sznurek", id = "201" },
    { type = "Animation", name = "Chrzastek_zostaje_porazony_pradem", id = "202" },
    { type = "Animation", name = "Chrzastek_dogorywa", id = "203" },
    { type = "Animation", name = "Grucha_chowa_glowe_w_ramiona", id = "204" },
    { type = "Animation", name = "Chrzastek_mowi", id = "205" },
    { type = "Animation", name = "Mafioso_1_mowi_jak_wariat", id = "206" },
    { type = "Animation", name = "Mafioso_1_rozkazuje_Kafarom", id = "207" },
    { type = "Animation", name = "Mafioso_2_mowi_zlowieszczo", id = "208" },
    { type = "Animation", name = "Mafioso_2_mowi_z_rekami_w_gorze", id = "209" },
    { type = "Animation", name = "Kafary_kiwaja_glowami", id = "210" },
    { type = "Animation", name = "Grucha_nasluchuje", id = "211" },
    { type = "Animation", name = "Fred_wali_w_drzwi", id = "212" },
    { type = "Animation", name = "Glos_zza_drzwi", id = "213" },
    { type = "Animation", name = "Fred_wylewa_olej_na_rampe", id = "214" },
    { type = "Animation", name = "Fred_kuli_sie_podczas_wypadku_Flowera", id = "215" },
    { type = "Animation", name = "Harasym_wychodzi_spomiedzy_drzew", id = "216" },
    { type = "Animation", name = "Harasym_rozmawia_1", id = "217" },
    { type = "Animation", name = "Harasym_znika_w_mrokach_nocy", id = "218" },
    { type = "Animation", name = "Egzema_petla_w_tle", id = "219" },
    { type = "Animation", name = "Egzema_rozmawia_z_Fredem_1", id = "220" },
    { type = "Animation", name = "Egzema_rozmawia_z_Fredem_2", id = "221" },
    { type = "Animation", name = "Pierwszy_Hipis_rozmawia_1", id = "222" },
    { type = "Animation", name = "Pierwszy_Hipis_rozmawia_2", id = "223" },
    { type = "Animation", name = "Pierwszy_Hipis_petla_w_tle", id = "224" },
    { type = "Animation", name = "Drugi_Hipis_petla_w_tle", id = "225" },
    { type = "Animation", name = "Drugi_Hipis_mowi_dramatycznie", id = "226" },
    { type = "Animation", name = "swiadek_rozmysla", id = "227" },
    { type = "Animation", name = "swiadek_odmawia", id = "228" },
    { type = "Animation", name = "swiadek_rozmawia_1", id = "229" },
    { type = "Animation", name = "swiadek_rozmawia_1", id = "230" },
    { type = "Animation", name = "swiadek_bierze_od_Freda_glejt", id = "231" },
    { type = "Animation", name = "Fred_daje_swiadkowi_rybe", id = "232" },
    { type = "Animation", name = "Grucha_chwieje_sie", id = "233" },
    { type = "Animation", name = "Grucha_rozmawia_chwiejnie", id = "234" },
    { type = "Animation", name = "Kowal_spluwa_na_rece_i_przystepuje_do_pracy", id = "235" },
    { type = "Animation", name = "Kowal_mowi_na_polanie", id = "236" },
    { type = "Animation", name = "Kowal_nasluchuje", id = "237" },
    { type = "Animation", name = "Kowal_umyka", id = "238" },
    { type = "Animation", name = "Kowal_znika_w_namiocie", id = "239" },
    { type = "Animation", name = "Kowal_wychodzi_z_namiotu", id = "240" },
    { type = "Animation", name = "zona_Kowala", id = "241" },
    { type = "Animation", name = "Lekarz_rozmawia_1", id = "242" },
    { type = "Animation", name = "Lekarz_siedzi", id = "243" },
    { type = "Animation", name = "Lekarz_odmawia", id = "244" },
    { type = "Animation", name = "Lekarz_bierze_glejt", id = "245" },
    { type = "Animation", name = "Lekarz_wstaje_i_wychodzi", id = "246" },
    { type = "Animation", name = "Kowal_rozmawia", id = "247" },
    { type = "Animation", name = "Kowal_podaje_Fredowi_glejt", id = "248" },
    { type = "Animation", name = "Kowal_ziewa", id = "249" },
    { type = "Animation", name = "Kowal_otwiera_furtke", id = "250" },
    { type = "Animation", name = "Fred_oglada_glejt", id = "251" },
    { type = "Animation", name = "Kowal_bierze_od_Freda_glejt", id = "252" },
    { type = "Animation", name = "Fred_wchodzi_po_drabinie", id = "253" },
    { type = "Animation", name = "Fred_schodzi_po_drabinie", id = "254" },
    { type = "Animation", name = "Fred_slucha_na_drabinie", id = "255" },
    { type = "Animation", name = "Fred_rozmawia_na_drabinie", id = "256" },
    { type = "Animation", name = "Malwina_petla_neutralna", id = "257" },
    { type = "Animation", name = "Malwina_rozmawia_z_Fredem_na_dole", id = "258" },
    { type = "Animation", name = "Malwina_rozmawia_z_Fredem_normalnie", id = "259" },
    { type = "Animation", name = "Fred_podaje_na_drabinie", id = "260" },
    { type = "Animation", name = "Malwina_przyjmuje_prezent", id = "261" },
    { type = "Animation", name = "Malwina_zamyka_okiennice", id = "262" },
    { type = "Animation", name = "Pierwszy_Hipis_bierze_od_Freda_pierscionek", id = "263" },
    { type = "Animation", name = "Zawodnik_W_Kapeluszu_siedzi_i_rechocze", id = "264" },
    { type = "Animation", name = "Zawodnik_w_Kapeluszu_swieci_latarka", id = "265" },
    { type = "Animation", name = "Zawodnik_W_Kapeluszu_rozmawia", id = "266" },
    { type = "Animation", name = "Zawodnik_W_Kapeluszu_rozglada_sie_nerwowo", id = "267" },
    { type = "Animation", name = "Zawodnik_W_Kapeluszu_krzyczy_przerazony", id = "268" },
    { type = "Animation", name = "Zawodnik_W_Kapeluszu_ucieka_przerazony", id = "269" },
    { type = "Animation", name = "Zawodnik_Z_Papierosem_pali_papierosa", id = "270" },
    { type = "Animation", name = "Zawodnik_Z_Papierosem_rozmawia_belkotliwie", id = "271" },
    { type = "Animation", name = "Zawodnik_Z_Papierosem_zastyga_w_przerazeniu", id = "272" },
    { type = "Animation", name = "Zawodnik_Z_Papierosem_mdleje", id = "273" },
    { type = "Animation", name = "Fred_straszy_w_Masce", id = "274" },
    { type = "Animation", name = "Grabarz_placze", id = "275" },
    { type = "Animation", name = "Grabarz_rozmawia_zdruzgotany", id = "276" },
    { type = "Animation", name = "Grabarz_otrzymuje_lopate", id = "277" },
    { type = "Animation", name = "Grabarz_petla_w_grobie", id = "278" },
    { type = "Animation", name = "Fred_rozmawia_z_glejtem_w_lapie", id = "279" },
    { type = "Animation", name = "Grabarz_gada_w_grobie", id = "280" },
    { type = "Animation", name = "Rybak_chwieje_sie_na_boki", id = "281" },
    { type = "Animation", name = "Rybak_rozmawia_z_Fredem_1", id = "282" },
    { type = "Animation", name = "Rybak_rozmawia_z_Fredem_2", id = "283" },
    { type = "Animation", name = "Rybak_patrzy_na_rybe", id = "284" },
    { type = "Animation", name = "Rybak_akcja_brzuchomowcy", id = "285" },
    { type = "Animation", name = "Rybak_dostaje_od_Freda_kawe", id = "286" },
    { type = "Animation", name = "Rybak_wrecza_Fredowi_rybe", id = "287" },
    { type = "Animation", name = "Rybak_pyka_fajke", id = "288" },
    { type = "Animation", name = "Fred_bierze_od_Rybaka_rybe", id = "289" },
    { type = "Animation", name = "Rybak_rozmawia_przytomnie", id = "290" },
    { type = "Animation", name = "Fred_lapanie_swietlikow_nieudane", id = "291" },
    { type = "Animation", name = "Fred_lapanie_swietlikow_udane", id = "292" },
    { type = "Animation", name = "Pani_Z_Obslugi_czyta", id = "293" },
    { type = "Animation", name = "Pani_Z_Obslugi_rozmawia", id = "294" },
    { type = "Animation", name = "Bandytowoz_wjezdza_na_stacje", id = "295" },
    { type = "Animation", name = "Fred_ucieka", id = "296" },
    { type = "Animation", name = "Kafar_1_z_offu", id = "297" },
    { type = "Animation", name = "Kafar_2_z_offu", id = "298" },
    { type = "Animation", name = "Pani_Z_Obslugi_daje_Fredowi_kawe", id = "299" },
    { type = "Animation", name = "Pani_Z_Obslugi_opuszcza_kolczyk", id = "300" },
    { type = "Animation", name = "Kafar_1_wysiada_z_Bandytowozu", id = "301" },
    { type = "Animation", name = "Fred_oparty_od_drzwi", id = "302" },
    { type = "Animation", name = "Fred_wspina_sie_na_sedes", id = "303" },
    { type = "Animation", name = "Kafar_2_wali_w_drzwi", id = "304" },
    { type = "Animation", name = "Kafar_1_szarpie_drzwi", id = "305" },
    { type = "Animation", name = "Fred_wypada_przez_lufcik", id = "306" },
    { type = "Animation", name = "Fred_wskakuje_do_swiezego_grobu", id = "307" },
    { type = "Animation", name = "Fred_wychodzi_ze_swiezego_grobu", id = "308" },
    { type = "Animation", name = "Kafary_wbiegaja_na_cmentarz", id = "309" },
    { type = "Animation", name = "Kafar_1_mowi", id = "310" },
    { type = "Animation", name = "Kafary_opuszczaja_cmentarz", id = "311" },
    { type = "Animation", name = "Szer_Posucha_rozmawia", id = "312" },
    { type = "Animation", name = "Szer_Posucha_melduje", id = "313" },
    { type = "Animation", name = "Szer_Posucha_slucha_kaprala", id = "314" },
    { type = "Animation", name = "Gromnica_rozmawia_z_Fredem", id = "315" },
    { type = "Animation", name = "Gromnica_wykrzykuje_cos_do_Posuchy", id = "316" },
    { type = "Animation", name = "Gromnica_petla_neutralna", id = "317" },
    { type = "Animation", name = "Posucha_petla_neutralna", id = "318" },
    { type = "Animation", name = "Gromnica_robi_sztuczke_z_nozem", id = "319" },
    { type = "Animation", name = "Fred_podziwia_sztuczke_z_nozem", id = "320" },
    { type = "Animation", name = "Fred_podziwia_sztuczke_z_nozem_trzymajac_wieczko", id = "321" },
    { type = "Animation", name = "furgonetka_stoi", id = "322" },
    { type = "Animation", name = "furgonetka_lina", id = "323" },
    { type = "Animation", name = "furgonetka_odjezdza", id = "324" },
    { type = "Animation", name = "DJ_Radiowy_siedzi_zamyslony", id = "325" },
    { type = "Animation", name = "DJ_Radiowy_rozmawia", id = "326" },
    { type = "Animation", name = "DJ_Radiowy_przytupuje", id = "327" },
    { type = "Animation", name = "DJ_Radiowy_mowi_do_mikrofonu", id = "328" },
    { type = "Animation", name = "DJ_radiowy_dostaje_od_Freda_Hejnal", id = "329" },
    { type = "Animation", name = "DJ_Radiowy_daje_Fredowi_karte_biblioteczna", id = "330" },
    { type = "Animation", name = "Fred_siada_na_kanapie", id = "331" },
    { type = "Animation", name = "Fred_rozmawia_przez_telefon_A", id = "332" },
    { type = "Animation", name = "Fred_wykreca_numer", id = "333" },
    { type = "Animation", name = "Fred_odklada_sluchawke", id = "334" },
    { type = "Animation", name = "Glos_W_Sluchawce", id = "335" },
    { type = "Animation", name = "Fred_wstaje_z_kanapy", id = "336" },
    { type = "Animation", name = "Fred_czyta_nr_karty_kredytowej", id = "337" },
    { type = "Animation", name = "Aldona_spi", id = "338" },
    { type = "Animation", name = "DJ_Radiowy_je_zupe_w_Zajezdzie", id = "339" },
    { type = "Animation", name = "DJ_Radiowy_rozmawia_w_Zajezdzie", id = "340" },
    { type = "Animation", name = "Gosc1_pije_piwo", id = "341" },
    { type = "Animation", name = "Gosc1_rozmawia_z_Freden", id = "342" },
    { type = "Animation", name = "Gosc1_rozmawia_z_Gosciem2", id = "343" },
    { type = "Animation", name = "Gosc2_rozmawia_z_Gosciem1", id = "344" },
    { type = "Animation", name = "Gosc2_rozmawia_z_Fredem", id = "345" },
    { type = "Animation", name = "Gosc2_mow_z_palcem_w_gorze", id = "346" },
    { type = "Animation", name = "Kelner_pali_papierosa", id = "347" },
    { type = "Animation", name = "Kelner_usmiecha_sie", id = "348" },
    { type = "Animation", name = "Kelner_rozmawia_1", id = "349" },
    { type = "Animation", name = "Kelner_rozmawia_2", id = "350" },
    { type = "Animation", name = "Fred_boi_sie_B", id = "351" },
    { type = "Animation", name = "Fred_lapie_motylki_B", id = "352" },
    { type = "Animation", name = "Fred_mercedes_gada", id = "353" },
    { type = "Animation", name = "Fred_mercedes_odchodzi", id = "354" },
    { type = "Animation", name = "Fred_nudzi_sie", id = "355" },
    { type = "Animation", name = "Fred_odmowa", id = "356" },
    { type = "Animation", name = "Fred_pochyla_sie_A", id = "357" },
    { type = "Animation", name = "Fred_pochyla_sie_C", id = "358" },
    { type = "Animation", name = "Fred_pochyla_sie_E", id = "359" },
    { type = "Animation", name = "Fred_przysypia", id = "360" },
    { type = "Animation", name = "Fred_zalamany", id = "361" },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_A",
        id = "362",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_B",
        id = "363",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_C",
        id = "364",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_D",
        id = "365",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_E",
        id = "366",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_F",
        id = "367",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_G",
        id = "368",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    {
        type = "Animation",
        name = "Grucha_nasluchuje_H",
        id = "369",
        group = "Grucha_nasluchuje_z_pozycji",
        character = "Grucha",
    },
    { type = "Animation", name = "Aldona_ziewa", id = "370" },
    { type = "Animation", name = "Aldona_rozmawia", id = "371" },
    { type = "Animation", name = "Aldona_zaspana", id = "372" },
    { type = "Animation", name = "Aldona_odbiera_Line", id = "373" },
    { type = "Animation", name = "Fred_zapowietrza_sie_h", id = "374" },
    { type = "Animation", name = "Kobieta_rozmawia", id = "375" },
    { type = "Animation", name = "Kobieta_rozglada_sie", id = "376" },
    { type = "Animation", name = "Kobieta_daje_mieso", id = "377" },
    { type = "Animation", name = "Kobieta_chichocze_upiornie", id = "378" },
    { type = "Animation", name = "Fred_bierze_mieso", id = "379" },
    { type = "Animation", name = "Tow_Roman_pali_papierosa", id = "380" },
    { type = "Animation", name = "Tow_Roman_rozmawia", id = "381" },
    { type = "Animation", name = "Tow_Roman_przemawia", id = "382" },
    { type = "Animation", name = "Chlop1_pokrzykuje", id = "383" },
    { type = "Animation", name = "Chlop1_mowi_do_swoich", id = "384" },
    { type = "Animation", name = "Chlop1_rozmawia_z_bohaterami", id = "385" },
    { type = "Animation", name = "Chlop1_potrzasa_grabiami", id = "386" },
    { type = "Animation", name = "Chlop1_zwraca_sie_ku_Romanowi", id = "387" },
    { type = "Animation", name = "Chlopka_pokrzykuje", id = "388" },
    { type = "Animation", name = "Chlopka_potakuje", id = "389" },
    { type = "Animation", name = "Chlopka_rozmawia_z_bohaterami", id = "390" },
    { type = "Animation", name = "Chlopka_trzyma_sie_pod_boki", id = "391" },
    { type = "Animation", name = "Chlopka_zwraca_sie_ku_Romanowi", id = "392" },
    { type = "Animation", name = "Chlopka_mowi_do_swoich", id = "393" },
    { type = "Animation", name = "ChlopNo2_spluwa", id = "394" },
    { type = "Animation", name = "ChlopNo2_pokrzykuje", id = "395" },
    { type = "Animation", name = "ChlopNo2_pali_szluga", id = "396" },
    { type = "Animation", name = "Chlop2_zwraca_sie_ku_Romanowi", id = "397" },
    { type = "Animation", name = "Fred_wyjmuje_tyczke_1", id = "398" },
    { type = "Animation", name = "Fred_wyjmuje_tyczke_2", id = "399" },
    { type = "Animation", name = "Wojarska_agituje", id = "400" },
    { type = "Animation", name = "Wojarska_rozmawia_z_bohaterami", id = "401" },
    { type = "Animation", name = "Wojarska_daje_ulotki", id = "402" },
    { type = "Animation", name = "Bibliotekarka_mowi", id = "403" },
    { type = "Animation", name = "Fred_wychodzi_z_biblioteki", id = "404" },
    { type = "Animation", name = "Fred_mowi_z_offu", id = "405" },
    { type = "Animation", name = "Grucha_bierze_od_Freda_mieso", id = "406" },
    { type = "Animation", name = "Grucha_bierze_od_Freda_Mieso2", id = "407" },
    { type = "Animation", name = "Psy_porywaja_Mieso1", id = "408" },
    { type = "Animation", name = "Psy_porywaja_Mieso2", id = "409" },
    { type = "Animation", name = "Psy_biegaja_po_kojcu", id = "410" },
    { type = "Animation", name = "Fred_siada_za_sterami_dzwigu", id = "411" },
    { type = "Animation", name = "Fred_mowi_za_sterami", id = "412" },
    { type = "Animation", name = "Fred_manipuluje_dzwigiem1", id = "413" },
    { type = "Animation", name = "Grucha_zostaje_porwany1", id = "414" },
    { type = "Animation", name = "Grucha_otwiera_furtke", id = "415" },
    { type = "Animation", name = "Grucha_odmawia_przerazony", id = "416" },
    { type = "Animation", name = "Fred_opuszcza_kontrolke", id = "417" },
    { type = "Animation", name = "fzb_pojawia_sie_w_dymku_kapliczka", id = "418" },
    { type = "Animation", name = "fzb_gada_kapliczka", id = "419" },
    { type = "Animation", name = "fzb_gada_jak_wariat_kapliczka", id = "420" },
    { type = "Animation", name = "fzb_gada_po_czym_rozplywa_sie_w_klebach_dymu_kapliczka", id = "421" },
    { type = "Animation", name = "DJ_Hajs_rozglada_sie_smutno", id = "422" },
    { type = "Animation", name = "DJ_Hajs_rozmawia_z_bohaterami_1", id = "423" },
    { type = "Animation", name = "DJ_Hajs_rozmawia_z_bohaterami_2", id = "424" },
    { type = "Animation", name = "DJ_Hajs_bierze_igle", id = "425" },
    { type = "Animation", name = "DJ_Hajs_katuje_plyty", id = "426" },
    { type = "Animation", name = "DJ_Hajs_daje_Hejnal", id = "427" },
    { type = "Animation", name = "Kierowniczka_przeglada_papiery", id = "428" },
    { type = "Animation", name = "Kierowniczka_rozmawia_z_bohaterami", id = "429" },
    { type = "Animation", name = "Kierowniczka_mowi_powstrzymujac_smiech", id = "430" },
    { type = "Animation", name = "Poslaniec_nadchodzi", id = "431" },
    { type = "Animation", name = "Poslaniec_rozmawia", id = "432" },
    { type = "Animation", name = "Poslaniec_odchodzi", id = "433" },
    { type = "Animation", name = "Harasym_stoi_przy_bibliotece", id = "434" },
    { type = "Animation", name = "Harasym_rozmawia_przy_bibliotece", id = "435" },
    { type = "Animation", name = "Harasym_macha_reka_na_powitanie_biblioteka", id = "436" },
    { type = "Animation", name = "Harasym_opuszcza_okolice_biblioteki", id = "437" },
    { type = "Animation", name = "Babina_przezuwa", id = "438" },
    { type = "Animation", name = "Babina_slucha", id = "439" },
    { type = "Animation", name = "Babina_mowi", id = "440" },
    { type = "Animation", name = "Babina_idzie_na_podworko", id = "441" },
    { type = "Animation", name = "Babina_bierze_Gumiaki", id = "442" },
    { type = "Animation", name = "Babina_mowi_ozywiona", id = "443" },
    { type = "Animation", name = "Grucha_sprawdza_stan_higieny", id = "444" },
    { type = "Animation", name = "Nieudana_proba_zabrania_podkowy", id = "445" },
    { type = "Animation", name = "Babina_rozmawia_na_podworku", id = "446" },
    { type = "Animation", name = "Babina_przezuwa_na_podworku", id = "447" },
    { type = "Animation", name = "Babina_slucha_na_podworku", id = "448" },
    { type = "Animation", name = "Fred_nasluchuje_A", id = "451", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_B", id = "452", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_C", id = "453", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_D", id = "454", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_E", id = "455", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_F", id = "456", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_G", id = "457", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Fred_nasluchuje_H", id = "458", group = "Fred_nasluchuje_z_pozycji", character = "Fred" },
    { type = "Animation", name = "Grucha_wzdycha_znudzony", id = "459" },
    { type = "Animation", name = "Fred_goli_Gruche_Raz", id = "460" },
    { type = "Animation", name = "Grucha_jest_golony_raz", id = "461" },
    { type = "Animation", name = "Grucha_reakcja_na_pierwsze_golenie", id = "462" },
    { type = "Animation", name = "Grucha_bierze_tupecik", id = "463" },
    { type = "Animation", name = "Pies_je_hotdoga", id = "464" },
    { type = "Animation", name = "Fred_goli_Gruche_Dwa", id = "465" },
    { type = "Animation", name = "Grucha_jest_golony_Dwa", id = "466" },
    { type = "Animation", name = "Grucha_zaklada_dres", id = "467" },
    { type = "Animation", name = "Diler_rozmawia_Skejtpark1", id = "468" },
    { type = "Animation", name = "FZB_gada_jak_wariat", id = "469" },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_A",
        id = "470",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_B",
        id = "471",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_C",
        id = "472",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_D",
        id = "473",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_E",
        id = "474",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_F",
        id = "475",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_G",
        id = "476",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_wysoko_H",
        id = "477",
        group = "Fred_wysoko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_A",
        id = "478",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_B",
        id = "479",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_C",
        id = "480",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_D",
        id = "481",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_E",
        id = "482",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_F",
        id = "483",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_G",
        id = "484",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_normalnie_H",
        id = "485",
        group = "Fred_normalnie_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_A",
        id = "486",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_B",
        id = "487",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_C",
        id = "488",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_D",
        id = "489",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_E",
        id = "490",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_F",
        id = "491",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_G",
        id = "492",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    {
        type = "Animation",
        name = "Fred_bierze_daje_nisko_H",
        id = "493",
        group = "Fred_nisko_bierze_daje_z_pozycji",
        character = "Fred",
    },
    { type = "Animation", name = "Reka_boga_chwyta_Freda", id = "494" },
    { type = "Animation", name = "Reka_boga_trzyma_Freda_nad_pieklem", id = "495" },
    { type = "Animation", name = "Fred_mowi_przerazony_nad_pieklem", id = "496" },
    { type = "Animation", name = "Glos_Boga_z_offu", id = "497" },
    { type = "Animation", name = "podskakujacy_wozek", id = "498" },
    { type = "Animation", name = "Stalowe_drzwi_zbrojone_gadanie", id = "499" },
    { type = "Animation", name = "Aparat_telefoniczny_nr_4_gadanie", id = "500" },
    { type = "Animation", name = "Magnes_zabiera_gruche", id = "501" },
    { type = "Animation", name = "Magnes_przenosi_gruche", id = "502" },
    { type = "Animation", name = "Klamka_porusza_sie_w_drzwiach_zbrojonych", id = "503" },
    { type = "Animation", name = "glos1_gada", id = "504" },
    { type = "Animation", name = "glos2_gada", id = "505" },
    { type = "Animation", name = "glos3_gada", id = "506" },
    { type = "Animation", name = "glos4_gada", id = "507" },
    { type = "Animation", name = "Fred_nisko_bierze_daje_z_pozycji", id = "508", group = "GROUP", character = "" },
    { type = "Animation", name = "Fred_normalnie_bierze_daje_z_pozycji", id = "509", group = "GROUP", character = "" },
    { type = "Animation", name = "Fred_wysoko_bierze_daje_z_pozycji", id = "510", group = "GROUP", character = "" },
    { type = "Animation", name = "Fred_puka_do_drzwi_E", id = "511" },
    { type = "Animation", name = "Glos_z_offu_gada", id = "512" },
    { type = "Animation", name = "Grucha_obrywa_magnesem", id = "513" },
    { type = "Animation", name = "Fred_patrzy_jak_kretyn_B", id = "514" },
    { type = "Animation", name = "Grucha_w_dresie_gadanie_G", id = "515" },
    { type = "Animation", name = "Grucha_w_dresie_gadanie_przez_ramię_w_kier_B", id = "516" },
    { type = "Animation", name = "Grucha_w_dresie_gadanie_wzburzone_G", id = "517" },
    { type = "Animation", name = "Grucha_w_dresie_bije_Dilera", id = "518" },
    { type = "Animation", name = "Grucha_w_dresie_patrzy_zdziwiony_na_Freda", id = "519" },
    { type = "Animation", name = "Grucha_w_dresie_zamachuje_sie_na_Dilera", id = "520" },
    { type = "Animation", name = "Fred_nasluchuje_z_pozycji", id = "521", group = "GROUP", character = "" },
    { type = "Animation", name = "Grucha_nasluchuje_z_pozycji", id = "522", group = "GROUP", character = "" },
    { type = "Animation", name = "Fred_macha_w_rezygnacji_reka_z_G", id = "523" },
    { type = "Animation", name = "Grucha_spoglada_skonsternowany", id = "524" },
    { type = "Animation", name = "FZB_przyjmuje_poze_szalenca_pod_kosciolem", id = "525" },
    { type = "Animation", name = "FZB_gada_po_czym_rozplywa_sie_w_klebach_dymu_pod_kosciolem", id = "526" },
    { type = "Animation", name = "FZB_pojawia_sie_w_dymku_pod_kosciolem", id = "527" },
    { type = "Animation", name = "FZB_pokazuje_zdjecia_pod_kosciolem", id = "528" },
    { type = "Animation", name = "Fzb_n", id = "529" },
    { type = "Animation", name = "szybka_n", id = "530" },
    { type = "Animation", name = "Opuszczanie_szybki", id = "531" },
    { type = "Animation", name = "Zamykanie_szybki", id = "532" },
    { type = "Animation", name = "apteczka_opened", id = "533" },
    { type = "Animation", name = "bagaznik", id = "534" },
    { type = "Animation", name = "bagaznik_otwarty", id = "535" },
    { type = "Animation", name = "Fred_mowi_skwaszony_G", id = "536" },
    { type = "Animation", name = "diler_przerazony_skejtpark1", id = "537" },
    { type = "Animation", name = "diler_rozmawia_skejtpark1", id = "538" },
    { type = "Animation", name = "diler_symuluje_kaszlniecie_skejtpark1", id = "539" },
    { type = "Animation", name = "diler_ucieka_skejtpark1", id = "540" },
    { type = "Animation", name = "Fred_patrzy_zdziwiony_C", id = "541" },
    { type = "Animation", name = "Grucha_patrzy_zdziwiony_na_Freda_G", id = "542" },
    { type = "Animation", name = "fred_G_bieg", id = "543" },
    { type = "Animation", name = "fred_macha_w_rezygnacji_reka_z_c", id = "544" },
    { type = "Animation", name = "fred_patrzy_jak_kretyn_h", id = "545" },
    { type = "Animation", name = "fred_pochyla_sie_g", id = "546" },
    { type = "Animation", name = "fred_boi_sie_h", id = "547" },
    { type = "Animation", name = "Fred_zastanawia_sie", id = "548" },
    { type = "Animation", name = "fred_wzburzony_siega_po_giwere", id = "549" },
    { type = "Animation", name = "Grucha_pollysy_bierze_normalnie_B", id = "550" },
    { type = "Animation", name = "Grucha_pollysy_zaklada_tupecik", id = "551" },
    { type = "Animation", name = "fred_drapie_sie_po_glowie", id = "552" },
    { type = "Animation", name = "schowek_otwarty", id = "553" },
    { type = "Animation", name = "schowek_zamkniety", id = "554" },
    { type = "Animation", name = "fred_trzyma_dealerowi_giwere_nad_glowa", id = "555" },
    { type = "Animation", name = "diler_przerazony_gada_skejtpark1", id = "556" },
    { type = "Animation", name = "diler_przerazony_skejtpark1_petla", id = "557" },
    { type = "Animation", name = "diler_od_przerazenia_do_normalnosci", id = "558" },
    { type = "Animation", name = "FZB_n1", id = "559" },
    { type = "Animation", name = "fred_lapie_motylki_h", id = "560" },
    { type = "Animation", name = "bagaznik_skos_zamkniety", id = "561" },
    { type = "Animation", name = "bagaznik_skos_otwarty", id = "562" },
    { type = "Animation", name = "zbrojone_otwarte", id = "563" },
    { type = "Animation", name = "zbrojone_zamkniete", id = "564" },
    { type = "Animation", name = "szatanska_fura_jedzie", id = "565" },
    { type = "Animation", name = "szatanska_fura_stoi", id = "566" },
    { type = "Animation", name = "Punkt", id = "567" },
    { type = "Animation", name = "Szybka_z_pistoletem", id = "568" },
    { type = "Animation", name = "Mestores_petla_neutralna", id = "569" },
    { type = "Animation", name = "Mestores_rozmawia", id = "570" },
    { type = "Animation", name = "Agatokles_petla_neutralna", id = "571" },
    { type = "Animation", name = "Agatokles_rozmawia", id = "572" },
    { type = "Animation", name = "Lucyfugus_petla_neutralna", id = "573" },
    { type = "Animation", name = "Lucyfugus_rozmawia", id = "574" },
    { type = "Animation", name = "Kula_dyskotekowa_n", id = "575" },
    { type = "Animation", name = "Kula_dyskotekowa_obrot", id = "576" },
    { type = "Animation", name = "rakowiecka_otwarte_drzwi_anim", id = "577" },
    { type = "Animation", name = "rakowiecka_zamkniete_drzwi_anim", id = "578" },
    { type = "Animation", name = "Fred_podnosi_kluczyki_patykiem", id = "579" },
    { type = "Animation", name = "Grucha_wychyla_sie", id = "580" },
    { type = "Animation", name = "gadanie_w_furze", id = "581" },
    { type = "Animation", name = "Wrota_otwarte", id = "582" },
    { type = "Animation", name = "Wrota_podejscie_z_latarka", id = "583" },
    { type = "Animation", name = "Wrota_swiatlo", id = "584" },
    { type = "Animation", name = "Wrota_zamkniete", id = "585" },
    { type = "Animation", name = "Otwieranie_wrot", id = "586" },
    { type = "Animation", name = "Stodola_ciemna", id = "587" },
    { type = "Animation", name = "Stodola_swiatlo", id = "588" },
    { type = "Animation", name = "Grucha_1_lezy_chory", id = "589" },
    { type = "Animation", name = "Grucha_1_gada_chory", id = "590" },
    { type = "Animation", name = "Reka_boga_trzyma_Freda_niebo", id = "591" },
    { type = "Animation", name = "Fred_niebo_przestraszyl_sie_z_C", id = "592" },
    { type = "Animation", name = "Fred_niebo_mowi_oslupialy_z_C", id = "593" },
    { type = "Animation", name = "Fred_niebo_nasluchuje_c", id = "594" },
    { type = "Animation", name = "Furtka_otw", id = "595" },
    { type = "Animation", name = "Furtka_otwieranie", id = "596" },
    { type = "Animation", name = "Furtka_zamk", id = "597" },
    { type = "Animation", name = "Furtka_zamykanie", id = "598" },
    { type = "Animation", name = "Fred_podskok_e", id = "599" },
    { type = "Animation", name = "fred_niebo_rozglada_sie_i_gada", id = "600" },
    { type = "Animation", name = "fred_niebo_nasluchuje_a", id = "601" },
    { type = "Animation", name = "Fred_niebo_obrot_ac", id = "602" },
    { type = "Animation", name = "Pani_z_Obslugi_slucha", id = "603" },
    { type = "Animation", name = "FZB_gada_pod_Kosciolem", id = "604" },
    { type = "Animation", name = "grucha_podnosi_sluchawke", id = "605" },
    { type = "Animation", name = "grucha_odklada_sluchawke", id = "606" },
    { type = "Animation", name = "grucha_trzyma_sluchawke", id = "607" },
    { type = "Animation", name = "Fred_bierze_daje_srednio_e", id = "608" },
    { type = "Animation", name = "telewizor", id = "609" },
    { type = "Animation", name = "tv1", id = "610" },
    { type = "Animation", name = "tv2", id = "611" },
    { type = "Animation", name = "tv3", id = "612" },
    { type = "Animation", name = "judasz", id = "613" },
    { type = "Animation", name = "judasz_rozmawia_slucha", id = "614" },
    { type = "Animation", name = "judasz_zamyka", id = "615" },
    { type = "Animation", name = "judasz_otwiera", id = "616" },
    { type = "Animation", name = "Fzb_brak", id = "617" },
    { type = "Animation", name = "klamka", id = "618" },
    { type = "Animation", name = "klamka_porusza_sie", id = "619" },
    { type = "Animation", name = "Fred_z_drzwiami", id = "621" },
    { type = "Animation", name = "diler_kuli_sie_panicznie_przed_Grucha_boisko", id = "622" },
    { type = "Animation", name = "diler_N_boisko", id = "623" },
    { type = "Animation", name = "diler_obrywa_od_freda_boisko", id = "624" },
    { type = "Animation", name = "Diler_obrywa_od_Gruchy_boisko", id = "625" },
    { type = "Animation", name = "diler_przerazony_boisko", id = "626" },
    { type = "Animation", name = "diler_ucieka_z_boiska", id = "627" },
    { type = "Animation", name = "Diler_wypluwa_zeby_boisko", id = "628" },
    { type = "Animation", name = "diler_od_przerazenia_do_normalnosci_boisko", id = "629" },
    { type = "Animation", name = "diler_od_normalnosci_do_przerazenia_boisko", id = "630" },
    { type = "Animation", name = "diler_przerazony_boisko_petla", id = "631" },
    { type = "Animation", name = "nuke_tylem", id = "632" },
    { type = "Animation", name = "nuke_wraca", id = "633" },
    { type = "Animation", name = "Grucha_stoi_pollysy", id = "634" },
    { type = "Animation", name = "Fred_goli_Gruche_raz_parking", id = "635" },
    { type = "Animation", name = "Fred_gasi_kominek_A", id = "636" },
    { type = "Animation", name = "Fred_gasi_kominek_B", id = "637" },
    { type = "Animation", name = "Jorge_petla_neutralna", id = "638" },
    { type = "Animation", name = "Jorge_gadanie_normalne", id = "639" },
    { type = "Animation", name = "Jorge_gadanie_szalone", id = "640" },
    { type = "Animation", name = "Jorge_atakuje_Freda_laska", id = "641" },
    { type = "Animation", name = "Fred_jest_atakowany_laska", id = "642" },
    { type = "Animation", name = "Mnich_zostaje_zastrzelony", id = "643" },
    { type = "Animation", name = "Fred_strzela_do_mnicha", id = "644" },
    { type = "Animation", name = "Aldona_wspina_sie_na_mur_klasztoru", id = "645" },
    { type = "Animation", name = "Aldona_otwiera_drzwi", id = "646" },
    { type = "Animation", name = "Grucha_jest_golony_raz_park", id = "647" },
    { type = "Animation", name = "Grucha_bierze_tupecik_park", id = "648" },
    { type = "Animation", name = "Grucha_reakcja_na_pierwsze_golenie_park", id = "649" },
    { type = "Animation", name = "Grucha_nasluchuje_pollysy_park", id = "650" },
    { type = "Animation", name = "Grucha_bierze_tupecik_sklep", id = "651" },
    { type = "Animation", name = "Grucha_reakcja_na_pierwsze_golenie_sklep", id = "652" },
    { type = "Animation", name = "Grucha_nasluchuje_pollysy_sklep", id = "653" },
    { type = "Animation", name = "Okno_swiatlo", id = "654" },
    { type = "Animation", name = "Okno_ciemne", id = "655" },
    { type = "Animation", name = "Aldona_zdziwienie", id = "656" },
    { type = "Animation", name = "Fred_odkasluje", id = "657" },
    { type = "Animation", name = "Jorge_opuszcza_korytarz", id = "658" },
    { type = "Animation", name = "Tajne_przejscie_otwiera_sie", id = "659" },
    { type = "Animation", name = "Ogien_gasnie_A", id = "660" },
    { type = "Animation", name = "Ogien_gasnie_B", id = "661" },
    { type = "Animation", name = "Ogien_plonie", id = "662" },
    { type = "Animation", name = "GADKA_lawka1", id = "663" },
    { type = "Animation", name = "SIAD_lawka1", id = "664" },
    { type = "Animation", name = "WSTAN_lawka1", id = "665" },
    { type = "Animation", name = "Fred_oddaje_glejt", id = "666" },
    { type = "Animation", name = "Fred_odbiera_glejt", id = "667" },
    { type = "Animation", name = "swiadek_bierze_od_Freda_rybe", id = "668" },
    { type = "Animation", name = "Zawodnik_z_Papierosem_przerazony", id = "669" },
    { type = "Animation", name = "Zawodnik_z_Papierosem_zemdlal", id = "670" },
    { type = "Animation", name = "Fred_daje_pusty_kubek", id = "671" },
    { type = "Animation", name = "Fred_daje_pelen_kubek", id = "672" },
    { type = "Animation", name = "Lufcik", id = "673" },
    { type = "Animation", name = "Lufcik_otwarty", id = "674" },
    { type = "Animation", name = "Lufcik_uchylony", id = "675" },
    { type = "Animation", name = "Fred_wypada_przez_lufcik_z_drugiej_strony", id = "676" },
    { type = "Animation", name = "Fred_oddaje_glejt_z_f", id = "677" },
    { type = "Animation", name = "Fred_odbiera_glejt_z_f", id = "678" },
    { type = "Animation", name = "Fred_odpala_motora", id = "679" },
    { type = "Animation", name = "Fred_odpala_motora_z_kopa", id = "680" },
    { type = "Animation", name = "Skaczacy_silnik", id = "681" },
    { type = "Animation", name = "Wylaczony_silnik", id = "682" },
    { type = "Animation", name = "Fred_gasi_motora", id = "683" },
    { type = "Animation", name = "kowal_bierze_lom", id = "684" },
    { type = "Animation", name = "kowal_N_lom", id = "685" },
    { type = "Animation", name = "kowal_odklada_lom", id = "686" },
    { type = "Animation", name = "kowal_petla_polana", id = "687" },
    { type = "Animation", name = "Grucha_1_jest_leczony", id = "688" },
    { type = "Animation", name = "Namiocik_porusza_sie", id = "689" },
    { type = "Animation", name = "Grucha_1_Gadanie_normalne_A", id = "690" },
    { type = "Animation", name = "Grucha_1_jest_leczony", id = "691" },
    { type = "Animation", name = "grucha_1_nasluchuje_a", id = "692" },
    { type = "Animation", name = "Grucha_1_niewidoczny", id = "693" },
    { type = "Animation", name = "Grucha_1_out_z_namiotu", id = "694" },
    { type = "Animation", name = "Grucha_wklada_stringi", id = "695" },
    { type = "Animation", name = "York_petla_neutralna", id = "696" },
    { type = "Animation", name = "York_gadanie", id = "697" },
    { type = "Animation", name = "Kot_petla_neutralna", id = "698" },
    { type = "Animation", name = "Kot_syczy", id = "699" },
    { type = "Animation", name = "Kot_pije_mleko", id = "700" },
    { type = "Animation", name = "Pani_z_Obslugi_schylona", id = "701" },
    { type = "Animation", name = "Pani_z_Obslugi_sie_prostuje", id = "702" },
    { type = "Animation", name = "Fred_bierze_daje_srednio_g", id = "703" },
    { type = "Animation", name = "Ribka", id = "704" },
    { type = "Animation", name = "Ribka_p", id = "705" },
    { type = "Animation", name = "Ribka_k", id = "706" },
    { type = "Animation", name = "Fred_gra_w_Tonka_f", id = "707" },
    { type = "Animation", name = "Harasym_mowi_szeptem", id = "708" },
    { type = "Animation", name = "Fred_skacze_raczej_wysoko_na_lufcik_G", id = "709" },
    { type = "Animation", name = "Grabarz_bierze_glejt", id = "710" },
    { type = "Animation", name = "Grabarz_oddaje_glejt", id = "711" },
    { type = "Animation", name = "Grabarz_stoi_przy_grobie", id = "712" },
    { type = "Animation", name = "Fred_boi_sie_przy_kapliczce", id = "713" },
    { type = "Animation", name = "Grucha_boi_sie_przy_kapliczce", id = "714" },
    { type = "Animation", name = "Aldona_boi_sie_przy_kapliczce", id = "715" },
    { type = "Animation", name = "FZB_konsternacja_przy_kapliczce", id = "716" },
    { type = "Animation", name = "Grucha_gadanie_bojowe", id = "717" },
    { type = "Animation", name = "Aldona_rzut_na_skrzynię", id = "718" },
    { type = "Animation", name = "Fred_wyjmuje_giwere_A", id = "719" },
    { type = "Animation", name = "Bandytowoz_przejazd_pierwszy", id = "720" },
    { type = "Animation", name = "Bandytowoz_przejazd_drugi", id = "721" },
    { type = "Animation", name = "Kafary_wysiadaja_z_bandytowozu", id = "722" },
    { type = "Animation", name = "Kafary_rozmawiają", id = "723" },
    { type = "Animation", name = "Harasym_swieci", id = "724" },
    { type = "Animation", name = "Harasym_przemiana", id = "725" },
    { type = "Animation", name = "FZB_przemiana", id = "726" },
    { type = "Animation", name = "Diabelny_FZB_atak_i_walka", id = "727" },
    { type = "Animation", name = "Anieslki_Harasym_walka", id = "728" },
    { type = "Animation", name = "Harasym_wychodzi_kapliczka", id = "729" },
    { type = "Animation", name = "Harasym_rozmawia_kapliczka", id = "730" },
    { type = "Animation", name = "Aldona_rozmawia_zdenerwowana_1", id = "731" },
    { type = "Animation", name = "Aldona_rozmawia_zdenerwowana_2", id = "732" },
    { type = "Animation", name = "Aldona_zdenerwowana", id = "733" },
    { type = "Animation", name = "Aldona_spi_spi", id = "734" },
    { type = "Animation", name = "Glosnik_nadaje_hejnal", id = "735" },
    { type = "Animation", name = "Glosnik_n", id = "736" },
    { type = "Animation", name = "Grucha_zdejmuje_dres", id = "737" },
    { type = "Animation", name = "FZB_zdziwienie", id = "738" },
    { type = "Animation", name = "Aldona_zwrot_do_bandytowozu", id = "739" },
    { type = "Animation", name = "Fred_zwrot_do_bandytowozu", id = "740" },
    { type = "Animation", name = "Grucha_zwrot_do_bandytowozu", id = "741" },
    { type = "Animation", name = "Harasym_mowi_swiecac", id = "742" },
    { type = "Animation", name = "FZB_walka", id = "744" },
    { type = "Animation", name = "Harasym_walka", id = "745" },
    { type = "Animation", name = "Fred_gada_do_gory", id = "746" },
    { type = "Animation", name = "Aldona_rozmawia_krypta", id = "747" },
    { type = "Animation", name = "Aldona_zaspana_krypta", id = "748" },
    { type = "Animation", name = "Aldona_rozmawia_korytarz", id = "749" },
    { type = "Animation", name = "Aldona_zaspana_korytarz", id = "750" },
    { type = "Animation", name = "Fred_przystawia_drabine", id = "751" },
    { type = "Animation", name = "Drzwi_do_biblioteki_otwieranie", id = "752" },
    { type = "Animation", name = "Drzwi_do_biblioteki_zamykanie", id = "753" },
    { type = "Animation", name = "Drzwi_do_biblioteki_uchylone", id = "754" },
    { type = "Animation", name = "Drzwi_do_biblioteki_zamkniete", id = "755" },
    { type = "Animation", name = "Okno_w_DzPnP", id = "756" },
    { type = "Animation", name = "Drzwi_do_biblioteki_otwarte", id = "757" },
    { type = "Animation", name = "Okno_na_pietrze_o", id = "758" },
    { type = "Animation", name = "Okno_na_pietrze_z", id = "759" },
    { type = "Animation", name = "Fred_podaje_na_drabinie_kwiaty", id = "760" },
    { type = "Animation", name = "Malwina_end", id = "761" },
    { type = "Animation", name = "fred_rozmawia_przez_telefon_B", id = "762" },
    { type = "Animation", name = "fred_rozmawia_slucha_przez_telefon_A", id = "763" },
    { type = "Animation", name = "Aldona_wstala", id = "764" },
    { type = "Animation", name = "Grucha_wyciaga_strzelbe", id = "765" },
    { type = "Animation", name = "Fred_zapowietrza_sie_b", id = "766" },
    { type = "Animation", name = "Fred_Kaczka_wychodzi_z_grobu", id = "767" },
    { type = "Animation", name = "Fred_Kaczka_kwacze", id = "768" },
    { type = "Animation", name = "Fred_ryjowka_wychodzi_z_grobu", id = "769" },
    { type = "Animation", name = "Fred_ryjowka_weszy", id = "770" },
    { type = "Animation", name = "Fred_obcy_wychodzi_z_grobu", id = "771" },
    { type = "Animation", name = "Fred_obcy_syczy", id = "772" },
    { type = "Animation", name = "Ikona_N", id = "773" },
    { type = "Animation", name = "Ikona_moved", id = "774" },
    { type = "Animation", name = "Wojarska_petla_n", id = "775" },
    { type = "Animation", name = "Poslaniec_petla", id = "776" },
    { type = "Animation", name = "Aldona_zdziwienie_korytarz", id = "777" },
    { type = "Animation", name = "Aldona_przechodzi_przez_tajne_przejscie", id = "778" },
    { type = "Animation", name = "Grucha_przechodzi_przez_tajne_przejscie", id = "779" },
    { type = "Animation", name = "Tajne_przejscie_otwarte", id = "780" },
    { type = "Animation", name = "Tajne_przejscie_zamkniete", id = "781" },
    { type = "Animation", name = "Bandytowoz_wjezdza_na_stacje_STOP", id = "782" },
    { type = "Animation", name = "kafar_1_wysiada_z_bandytowozu_stoi", id = "783" },
    { type = "Animation", name = "Fred_zaklada_maske", id = "784" },
    { type = "Animation", name = "Fred_zdejmuje_maske", id = "785" },
    { type = "Animation", name = "Fred_straszy_w_Masce_petla", id = "786" },
    { type = "Animation", name = "Przejscie_tajne_otw", id = "787" },
    { type = "Animation", name = "Przejscie_tajne_zam", id = "788" },
    { type = "Animation", name = "Przejscie_tajne_zamykanie", id = "789" },
    { type = "Animation", name = "Przejscie_tajne_otwieranie", id = "790" },
    { type = "Animation", name = "Aldona_rozmawia_ppk", id = "791" },
    { type = "Animation", name = "Aldona_zaspana_ppk", id = "792" },
    { type = "Animation", name = "Gromnica_robi_sztuczke_z_nozem_2", id = "793" },
    { type = "Animation", name = "Aldona_1_n", id = "794" },
    { type = "Animation", name = "Aldona_1_rozmawia", id = "795" },
    { type = "Animation", name = "Aldona_1_otwiera_drzwi", id = "796" },
    { type = "Animation", name = "Aldona_1_drzwi", id = "797" },
    { type = "Animation", name = "Aldona_wspina_sie_n", id = "798" },
    { type = "Animation", name = "Kot_dostaje_mleko", id = "799" },
    { type = "Animation", name = "Grucha_siada_na_kanapie", id = "800" },
    { type = "Animation", name = "Garnek", id = "801" },
    { type = "Animation", name = "Garnek_n", id = "802" },
    { type = "Animation", name = "Fred_wertuje_ksiazke_telefoniczna", id = "803" },
    { type = "Animation", name = "furgonetka_lina_idle", id = "804" },
    { type = "Animation", name = "furgonetka_lina_idle2", id = "805" },
    { type = "Animation", name = "furgonetka_lina_gadka", id = "806" },
    { type = "Animation", name = "furgonetka_lina_okno_dol", id = "807" },
    { type = "Animation", name = "fzb_przyjmuje_poze_szalenca_kapliczka", id = "808" },
    { type = "Animation", name = "fzb_n_kapliczka", id = "809" },
    { type = "Animation", name = "harasym_zaczyna_swiecic", id = "810" },
    { type = "Animation", name = "harasym_N_kapliczka", id = "811" },
    { type = "Animation", name = "Fred_daje_mieso", id = "812" },
    { type = "Animation", name = "bandytowoz_zajezdza", id = "813" },
    { type = "Animation", name = "bandytowoz_stoi", id = "814" },
    { type = "Animation", name = "bandytowoz_czeka", id = "815" },
    { type = "Animation", name = "kafar_1_wysiada_z_bandytowozu_stoi_final", id = "816" },
    { type = "Animation", name = "kafar_1_wysiada_z_bandytowozu_final", id = "817" },
    { type = "Animation", name = "kafar_1_mowi_final", id = "818" },
    { type = "Animation", name = "FZB_po_przemianie", id = "819" },
    { type = "Animation", name = "Harasym_po_przemianie", id = "820" },
    { type = "Animation", name = "Aniol_diabel_walka", id = "821" },
    { type = "Animation", name = "Aniol_diabel_idle", id = "822" },
    { type = "Animation", name = "ost_otw", id = "823" },
    { type = "Animation", name = "ost_zam", id = "824" },
    { type = "Animation", name = "zlom_furtka_otw", id = "825" },
    { type = "Animation", name = "zlom_furtka_zam", id = "826" },
    { type = "Animation", name = "Zlom_otwieranie_furtki", id = "827" },
    { type = "Animation", name = "Grucha_w_dresie_N", id = "828" },
    { type = "Animation", name = "Grucha_w_dresie_N2", id = "829" },
    { type = "Animation", name = "fred_bieg_boisko", id = "830" },
    { type = "Animation", name = "fred_wyskakuje_z_krzakow_boisko", id = "831" },
    { type = "Animation", name = "Fred_mowi_z_giwera_w_lewo_I", id = "832" },
    { type = "Animation", name = "Fred_mowi_z_giwera_w_lewo_II", id = "833" },
    { type = "Animation", name = "diler_proboje_uciekac_z_boiska", id = "834" },
    { type = "Animation", name = "Grucha_zostaje_porwany2", id = "835" },
    { type = "Animation", name = "Grucha_zostaje_porwany3", id = "836" },
    { type = "Animation", name = "Grucha_wchodzi_do_tajnego_przejscia", id = "837" },
    { type = "Animation", name = "Fred_wchodzi_do_tajnego_przejscia", id = "838" },
    { type = "Animation", name = "Fred_wychodzi_z_tajnego_przejscia", id = "839" },
    { type = "Animation", name = "aldona3", id = "840" },
    { type = "Animation", name = "Kafary_wbiegaja_na_final", id = "841" },
    { type = "Animation", name = "komix1_N", id = "842" },
    { type = "Animation", name = "Komiks2_N", id = "843" },
    { type = "Animation", name = "Komix1", id = "844" },
    { type = "Animation", name = "Komiks2", id = "845" },
    { type = "Animation", name = "fred_nasluchuje_harasyma", id = "846" },
    { type = "Animation", name = "flower_stoi_na_rampie", id = "847" },
    { type = "Animation", name = "grucha_wstaje_z_kanapy", id = "848" },
    { type = "Animation", name = "Tow_Roman_gubi_piulki", id = "849" },
    { type = "Animation", name = "flower_przed_wywrotka", id = "850" },
    { type = "Animation", name = "Grucha_chowa_strzelbe", id = "851" },
    { type = "Animation", name = "Psy_N", id = "852" },
    { type = "Animation", name = "York_statyczny", id = "853" },
    { type = "Animation", name = "fred_pada", id = "854" },
    { type = "Animation", name = "fred_lezy", id = "855" },
    { type = "Animation", name = "FZB_gada_maly", id = "856" },
    { type = "Animation", name = "fzb_pojawia_sie_maly", id = "857" },
    { type = "Animation", name = "reinkarnacja_big", id = "858" },
    { type = "Animation", name = "reinkarnacja", id = "859" },
    { type = "Animation", name = "kaczka", id = "860" },
    { type = "Animation", name = "kaczka_gada", id = "861" },
    { type = "Animation", name = "kaczka_slucha", id = "862" },
    { type = "Animation", name = "ryjowka", id = "863" },
    { type = "Animation", name = "ryjowka_gada", id = "864" },
    { type = "Animation", name = "ryjowka_slucha", id = "865" },
    { type = "Animation", name = "alien", id = "866" },
    { type = "Animation", name = "alien_gada", id = "867" },
    { type = "Animation", name = "Remka_static", id = "868" },
    { type = "Animation", name = "Remka_wejscie", id = "869" },
    { type = "Animation", name = "Remka_wyjscie", id = "870" },
    { type = "Animation", name = "glos5_gada", id = "871" },
}