return {
    {
        type = "ClipReference",
        clipId = "Akt_1\\Szósty Dialog ze Stróżem - po odnalezieniu wnuka",
        id = "doprowadzenie_zioma_2",
        name = "doprowadzenie_zioma_2",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Przybycie na parking",
        id = "Przybycie_na_parking",
        name = "Przybycie_na_parking",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Pierwszy dialog z FZB",
        id = "Rozmowa_z_FZB_przy_kosciele",
        name = "Rozmowa_z_FZB_przy_kosciele",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Pierwsze ponowne spotkanie z Dilerem",
        id = "spotkanie_z_dilerem_boisko",
        name = "spotkanie_z_dilerem_boisko",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Spotkanie z Harasymem",
        id = "Spotkanie z Harasymem",
        name = "Spotkanie z Harasymem",
    },
    {
        type = "Clip",
        id = "Jehowy_widoczny",
        name = "Jehowy_widoczny",
        {
            type = "ClipAction",
            actionID = "11",
            name = "set visible",
            params = "Akt_2\\OBOZ HIPPISOW\\Swiadek_Jehowy,true",
            sfx = "",
            popup = "",
            groupelem = "",
            character = "",
            wave = "",
            text = "",
        },
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Akcja z Kowalem czesc druga",
        id = "Akcja z Kowalem czesc druga",
        name = "Akcja z Kowalem czesc druga",
    },
    {
        type = "ClipReference",
        clipId = "Prolog\\Fred wyłazi z grobu",
        id = "fred budzi sie na polanie",
        name = "fred budzi sie na polanie",
    },
    {
        type = "ClipReference",
        clipId = "Prolog\\Fred budzi się na polanie po pierwszej rozmowie z FZB",
        id = "fred budzi sie na polanie2",
        name = "fred budzi sie na polanie2",
    },
    { type = "ClipReference", clipId = "Prolog\\Rozmowa z Bogiem", id = "klip niebo", name = "klip niebo" },
    { type = "ClipReference", clipId = "Prolog\\Rozmowa z Bogiem - ciąg dalszy", id = "klip pieklo", name = "klip pieklo" },
    {
        type = "ClipReference",
        clipId = "Prolog\\Spotkanie na Rakowieckiej",
        id = "spotkanie na rakowieckiej",
        name = "spotkanie na rakowieckiej",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Finał Ucieczki przed Kafarami",
        id = "Finał Ucieczki przed Kafarami",
        name = "Finał Ucieczki przed Kafarami",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Dialog z Gangsterami 3",
        id = "Dialog z Gangsterami 3",
        name = "Dialog z Gangsterami 3",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Klip nieinteraktywny",
        id = "Klip nieinteraktywny",
        name = "Klip nieinteraktywny",
    },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 2 of 3)",
        id = "Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 2 of 3)",
        name = "Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 2 of 3)",
    },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Rozbiegowka Aktu - sekwencja nieinteraktywna",
        id = "Rozbiegowka Aktu - sekwencja nieinteraktywna",
        name = "Rozbiegowka Aktu - sekwencja nieinteraktywna",
    },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Spotkanie z Kurierem",
        id = "Spotkanie z Kurierem",
        name = "Spotkanie z Kurierem",
    },
    {
        type = "Clip",
        id = "Klip Stodola",
        name = "Klip Stodola",
        {
            type = "ClipAction",
            actionID = "11",
            name = "set visible",
            params = "Fred,true",
            sfx = "",
            popup = "",
            groupelem = "",
            character = "",
            wave = "",
            text = "",
        },
    },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Spotkanie z Poslancem",
        id = "Spotkanie z Poslancem",
        name = "Spotkanie z Poslancem",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Ciąg dalszy ucieczki przed Kafarami",
        id = "Ciąg dalszy ucieczki przed Kafarami",
        name = "Ciąg dalszy ucieczki przed Kafarami",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Wejscie przez lufcik",
        id = "Wejscie przez lufcik",
        name = "Wejscie przez lufcik",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Normalne wyjscie z toalety",
        id = "Normalne wyjscie z toalety",
        name = "Normalne wyjscie z toalety",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Ucieczka przed Kafarami",
        id = "Ucieczka przed Kafarami",
        name = "Ucieczka przed Kafarami",
    },
    { type = "ClipReference", clipId = "Akt_3\\Nadawanie hejnalu", id = "Nadawanie hejnalu", name = "Nadawanie hejnalu" },
    { type = "ClipReference", clipId = "Akt_2\\Komiks 1", id = "Komiks 1", name = "Komiks 1" },
    { type = "ClipReference", clipId = "Akt_3\\Komiks 2", id = "Komiks 2", name = "Komiks 2" },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Spotkanie z Harasymem - dialog rozgrywany po pierwszej wizycie w Muszli Koncertowej",
        id = "Spotkanie z Harasymem - dialog rozgrywany po pierwszej wizycie w Muszli Koncertowej",
        name = "Spotkanie z Harasymem - dialog rozgrywany po pierwszej wizycie w Muszli Koncertowej",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Znikniecie licealistow",
        id = "Znikniecie licealistow",
        name = "Znikniecie licealistow",
    },
    { type = "ClipReference", clipId = "Akt_3\\Final Gry", id = "Final Gry", name = "Final Gry" },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Wejscie do Klasztoru",
        id = "Wejscie do Klasztoru",
        name = "Wejscie do Klasztoru",
    },
    { type = "ClipReference", clipId = "Akt_3\\Wyciemnienie", id = "Wyciemnienie", name = "Wyciemnienie" },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Pierwsze wejscie do klasztoru",
        id = "Pierwsze wejscie do klasztoru",
        name = "Pierwsze wejscie do klasztoru",
    },
    { type = "ClipReference", clipId = "Akt_3\\Spotkanie z FZB", id = "Spotkanie z FZB", name = "Spotkanie z FZB" },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Counter gadek ze zlomiarzami",
        id = "Counter gadek ze zlomiarzami",
        name = "Counter gadek ze zlomiarzami",
    },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Gadka o nowej sciezce",
        id = "Gadka o nowej sciezce",
        name = "Gadka o nowej sciezce",
    },
    {
        type = "ClipReference",
        clipId = "Akt_2\\Pojawienie sie swietlikow",
        id = "Pojawienie sie swietlikow",
        name = "Pojawienie sie swietlikow",
    },
    { type = "ClipReference", clipId = "Prolog\\Wylaczenie Freda", id = "Wylaczenie Freda", name = "Wylaczenie Freda" },
    {
        type = "ClipReference",
        clipId = "Akt_1\\Wylaczenie Freda i Gruchy",
        id = "Wylaczenie Freda i Gruchy",
        name = "Wylaczenie Freda i Gruchy",
    },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Wlaczenie lepszej mapy wis",
        id = "Wlaczenie lepszej mapy wis",
        name = "Wlaczenie lepszej mapy wis",
    },
    {
        type = "ClipReference",
        clipId = "Akt_1\\reinkarnacja_kaczka",
        id = "reinkarnacja_kaczka",
        name = "reinkarnacja_kaczka",
    },
    { type = "ClipReference", clipId = "Akt_3\\reinkarnacja_alien", id = "reinkarnacja_alien", name = "reinkarnacja_alien" },
    {
        type = "ClipReference",
        clipId = "Akt_3\\Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 4 0f 3)",
        id = "Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 4 0f 3)",
        name = "Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 4 0f 3)",
    },
}