return {
    { type = "ChangeLoc", name = "Parking strzezony", clip_id = "doprowadzenie_zioma_2", const_id = "3" },
    { type = "ChangeLoc", name = "Parking strzezony", clip_id = "Przybycie_na_parking", const_id = "1" },
    { type = "ChangeLoc", name = "Okolice kosciola", clip_id = "Rozmowa_z_FZB_przy_kosciele", const_id = "45" },
    { type = "ChangeLoc", name = "Szkola", clip_id = "reinkarnacja_kaczka", const_id = "213" },
    { type = "ChangeLoc", name = "Boisko szkolne", clip_id = "spotkanie_z_dilerem_boisko", const_id = "50" },
    { type = "ChangeLoc", name = "Sklep plytowy", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Centrum handlowe", clip_id = "Znikniecie licealistow", const_id = "149" },
    { type = "ChangeLoc", name = "Kafejka internetowa", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Plac za miastem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Siedziba mafii", clip_id = "Klip nieinteraktywny", const_id = "106" },
    { type = "ChangeLoc", name = "Dom kowala", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Skrzyzowanie", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Stodola", clip_id = "Klip stodola", const_id = "101" },
    { type = "ChangeLoc", name = "Oboz hippisow", clip_id = "Spotkanie z Harasymem", const_id = "75" },
    { type = "ChangeLoc", name = "Oboz hippisow", clip_id = "Jehowy_widoczny", const_id = "76" },
    { type = "ChangeLoc", name = "Oboz hippisow", clip_id = "Akcja z Kowalem czesc druga", const_id = "79" },
    { type = "ChangeLoc", name = "Dom lekarza", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Ogrod za domem lekarza", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Stacja benzynowa", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Toaleta zwykla", clip_id = "Wejscie przez lufcik", const_id = "144" },
    { type = "ChangeLoc", name = "Toaleta", clip_id = "Ucieczka przed Kafarami", const_id = "62" },
    {
        type = "ChangeLoc",
        name = "Przejscie miedzy toaleta a cmentarzem",
        clip_id = "Ciąg dalszy ucieczki przed Kafarami",
        const_id = "105",
    },
    {
        type = "ChangeLoc",
        name = "Przejscie miedzy toaleta a cmentarzem",
        clip_id = "Normalne wyjscie z toalety",
        const_id = "143",
    },
    { type = "ChangeLoc", name = "Cmentarz", clip_id = "Finał Ucieczki przed Kafarami", const_id = "62" },
    { type = "ChangeLoc", name = "Starsza czesc cmentarza", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "LAKA", clip_id = "Pojawienie sie swietlikow", const_id = "205" },
    { type = "ChangeLoc", name = "Dom z pokojem na pietrze", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Lesna droga z wojskowym jeepem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Rozglosnia radiowa", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Zajazd", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Pokoj na pietrze zajazdu", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Zlomowisko", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Kapliczka za miastem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Blokada na drodze", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Biblioteka", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Podworze za tymze domem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Muszla koncertowa", clip_id = "Spotkanie z Poslancem", const_id = "141" },
    { type = "ChangeLoc", name = "PARKING PRZY ROZGLOSNI RADIOWEJ", clip_id = "reinkarnacja_alien", const_id = "214" },
    { type = "ChangeLoc", name = "Plac przed Zajazdem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Podjazd pod klasztorem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Dom z bialych desek", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Polana za muszla koncertowa", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Niebo", clip_id = "klip niebo", const_id = "87" },
    { type = "ChangeLoc", name = "Pieklo", clip_id = "klip pieklo", const_id = "88" },
    { type = "ChangeLoc", name = "Polana z grobem", clip_id = "fred budzi sie na polanie", const_id = "84" },
    { type = "ChangeLoc", name = "Polana z grobem", clip_id = "fred budzi sie na polanie2", const_id = "86" },
    { type = "ChangeLoc", name = "Drozka na skraju lasu", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Droga z autem", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Wnetrze samochodu", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "Brama przy rakowieckiej", clip_id = "spotkanie na rakowieckiej", const_id = "85" },
    { type = "ChangeLoc", name = "Siedziba mafii", clip_id = "Dialog z Gangsterami 3", const_id = "105" },
    {
        type = "ChangeLoc",
        name = "BIBLIOTEKA",
        clip_id = "Spotkanie z Harasymem - dialog rozgrywany po pierwszej wizycie w Muszli Koncertowej",
        const_id = "112",
    },
    { type = "ChangeLoc", name = "BLOKADA NA DRODZE", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "DOM Z BIALYCH DESEK", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "KAPLICZKA ZA MIASTEM", clip_id = "Spotkanie z FZB", const_id = "181" },
    { type = "ChangeLoc", name = "KORYTARZ KLASZTORNY", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "KRYPTA", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "MUSZLA KONCERTOWA", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "PARKING PRZY ROZGLOSNI RADIOWEJ", clip_id = "Spotkanie z Kurierem", const_id = "134" },
    {
        type = "ChangeLoc",
        name = "PARKING PRZY ROZGLOSNI RADIOWEJ",
        clip_id = "Rozbiegowka Aktu - sekwencja nieinteraktywna",
        const_id = "133",
    },
    { type = "ChangeLoc", name = "PLAC PRZED ZAJAZDEM", clip_id = "Nadawanie hejnalu", const_id = "225" },
    { type = "ChangeLoc", name = "PODJAZD POD KLASZTOREM", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "PODWORZE ZA TYMZE DOMEM", clip_id = "", const_id = "" },
    {
        type = "ChangeLoc",
        name = "POKOJ NA PIETRZE ZAJAZDU",
        clip_id = "Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 2 of 3)",
        const_id = "225",
    },
    {
        type = "ChangeLoc",
        name = "ROZGLOSNIA RADIOWA",
        clip_id = "Przekazanie DJ-owi plyty z Hejnalem Mariackim (part 4 0f 3)",
        const_id = "225",
    },
    { type = "ChangeLoc", name = "ZAJAZD", clip_id = "", const_id = "" },
    { type = "ChangeLoc", name = "ZLOMOWISKO", clip_id = "Counter gadek ze zlomiarzami", const_id = "182" },
    { type = "ChangeLoc", name = "KOMIKS1", clip_id = "Komiks 1", const_id = "146" },
    { type = "ChangeLoc", name = "KOMIKS2", clip_id = "Komiks 2", const_id = "147" },
    { type = "ChangeLoc", name = "KAPLICZKA ZA MIASTEM", clip_id = "Final Gry", const_id = "151" },
    { type = "ChangeLoc", name = "PODJAZD POD KLASZTOREM", clip_id = "Wejscie do Klasztoru", const_id = "119" },
    { type = "ChangeLoc", name = "AKCJA W KLASZTORZE", clip_id = "Wyciemnienie", const_id = "119" },
    { type = "ChangeLoc", name = "KORYTARZ KLASZTORNY", clip_id = "Pierwsze wejscie do klasztoru", const_id = "119" },
    { type = "ChangeLoc", name = "PLAC PRZED ZAJAZDEM", clip_id = "Gadka o nowej sciezce", const_id = "201" },
    { type = "ChangeLoc", name = "WNETRZE SAMOCHODU", clip_id = "Wylaczenie Freda", const_id = "205" },
    { type = "ChangeLoc", name = "WNETRZE SAMOCHODU1", clip_id = "Wylaczenie Freda i Gruchy", const_id = "205" },
    { type = "ChangeLoc", name = "ZAJAZD", clip_id = "Wlaczenie lepszej mapy wis", const_id = "212" },
}