return {
    { type = "Constraint", name = "poczatkowa sekwencja dialogu Fred-Grucha", id = "1", expression = "t[105] = false" },
    { type = "Constraint", name = "zostawienie fruy", id = "2", expression = "t[2] = true" },
    { type = "Constraint", name = "Sprowadzenie wnuka do dziada", id = "3", expression = "t[3] = true" },
    {
        type = "Constraint",
        name = "Opatrzenie Flowera",
        id = "4",
        expression = "(t[37] = true) and (t[45] = false) and (t[46] = false)",
    },
    { type = "Constraint", name = "wypadek Flowera", id = "5", expression = "(t[8] = true) and (t[37] = false)" },
    { type = "Constraint", name = "Zabranie oleju", id = "6", expression = "t[9] = true" },
    { type = "Constraint", name = "Zabranie wody utlenionej", id = "7", expression = "(t[10] = true) and (t[27] = true)" },
    { type = "Constraint", name = "Zabranie bandaza", id = "8", expression = "(t[10] = true) and (t[27] = true)" },
    { type = "Constraint", name = "Zabranie hot-doga", id = "9", expression = "(t[129] = true) and (t[11] = true)" },
    { type = "Constraint", name = "Pojawienie sie skateparku", id = "10", expression = "t[12] = true" },
    { type = "Constraint", name = "Pojawienie sie kosciola", id = "11", expression = "t[13] = true" },
    { type = "Constraint", name = "Pojawienie sie Centrum handlowego", id = "12", expression = "t[14] = true" },
    { type = "Constraint", name = "Pojawienie sie sklepu plytowego (nieaktywnego)", id = "13", expression = "t[14] = true" },
    { type = "Constraint", name = "Pojawienie sie szkoły sredniej", id = "14", expression = "t[14] = true" },
    { type = "Constraint", name = "pojawienie sie placu za miastem", id = "15", expression = "t[14] = true" },
    { type = "Constraint", name = "Pojawienie się kafejki internetowej", id = "16", expression = "t[15] = true" },
    {
        type = "Constraint",
        name = "Pojawienie sie przejścia na boisko szkolne i mozliwosc dzwonienia",
        id = "17",
        expression = "(t[16] = true) and (t[21] = true) and (t[53] = true)",
    },
    { type = "Constraint", name = "Mozemy Ograc Nuka", id = "18", expression = "t[17] = true" },
    {
        type = "Constraint",
        name = "jestesmy gotowi do Nauki gry w Tonka",
        id = "19",
        expression = "(t[18] = true) and (t[17] = false)",
    },
    { type = "Constraint", name = "Pojawienie sie sklepu plytowego (aktywnego)", id = "20", expression = "t[19] = true" },
    {
        type = "Constraint",
        name = "Telefon do dilera",
        id = "21",
        expression = "(t[16] = true) and (t[50] = true) and (t[21] = true) and (t[31] = true)",
    },
    { type = "Constraint", name = "Wyjęcie monety z gumy", id = "22", expression = "t[23] = true" },
    { type = "Constraint", name = "Odklejenie gumy od automatu", id = "23", expression = "t[24] = true" },
    {
        type = "Constraint",
        name = "Zlozenie  maszynki do golenia",
        id = "24",
        expression = "(t[25] = true) and (t[26] = true)",
    },
    { type = "Constraint", name = "Zabranie silnika do maszynki", id = "25", expression = "t[9] = true" },
    {
        type = "Constraint",
        name = "Odebranie dresu po wczesniejszej gadce z tekstylia",
        id = "26",
        expression = "(t[143] = true) and (t[128] = true)",
    },
    {
        type = "Constraint",
        name = "Spotkanie z dilerem",
        id = "27",
        expression = "(t[29] = true) and (t[25] = true) and (t[28] = true)",
    },
    {
        type = "Constraint",
        name = "mozemy juz wyciagnac mafiosow",
        id = "28",
        expression = "(t[35] = true) and (t[301] = false)",
    },
    {
        type = "Constraint",
        name = "ogolenie gruchy",
        id = "29",
        expression = "(t[32] = true) and (t[33] = true) and (t[31] = false)",
    },
    {
        type = "Constraint",
        name = "Rozpoczęcie golenia gruchy w strużuwce",
        id = "30",
        expression = "(t[91] = true) and (t[10] = true)",
    },
    { type = "Constraint", name = "Oddanie sznurka chrząstkowi", id = "31", expression = "t[33] = true" },
    { type = "Constraint", name = "wejście do kryjówki gangsterów", id = "32", expression = "t[35] = true" },
    { type = "Constraint", name = "Znalezienie tajnego przejścia", id = "33", expression = "t[36] = true" },
    { type = "Constraint", name = "Rozmowa z drugim ziomem po opatrzeniu", id = "34", expression = "t[130] = true" },
    {
        type = "Constraint",
        name = "Odebranie dresu_bez wczesniejszej gadki z tekstylia",
        id = "35",
        expression = "t[143] = true",
    },
    {
        type = "Constraint",
        name = "Odebranie kadluba maszynki po wczesniejszej gadce z waldkiem",
        id = "36",
        expression = "(t[143] = true) and (t[127] = true)",
    },
    {
        type = "Constraint",
        name = "Odebranie kadluba maszynki bez  wczesniejszej gadki  z waldkiem",
        id = "37",
        expression = "t[143] = true",
    },
    {
        type = "Constraint",
        name = "Odmowa golenia z powodu protestu winyla/stroza",
        id = "38",
        expression = "(t[32] = true) and (t[126] = false) and (t[31] = false)",
    },
    { type = "Constraint", name = "Wyłączenie tv", id = "39", expression = "t[39] =true" },
    { type = "Constraint", name = "Nakarmienie Psa", id = "40", expression = "(t[10] = true) and (t[27] = false)" },
    { type = "Constraint", name = "Dalsza gadka z matka", id = "41", expression = "t[14] = true" },
    { type = "Constraint", name = "Przestraszenie dilera", id = "42", expression = "(t[11] = true) and  (t[129] = false)" },
    {
        type = "Constraint",
        name = "mozna juz opatrywac Flowera",
        id = "43",
        expression = "(t[45] = true) and (t[46] = true) and (t[4] = true)",
    },
    { type = "Constraint", name = "gdy jest otwarta", id = "44", expression = "(t[10] = true) and (t[27] = true)" },
    { type = "Constraint", name = "mamy dostac zlecenie od FZB", id = "45", expression = "(t[2] = true) and (t[14] = false)" },
    { type = "Constraint", name = "Ogralismy nukea", id = "46", expression = "(t[144] = true) and  (t[17] = true)" },
    {
        type = "Constraint",
        name = "nie ogralismy nukea",
        id = "47",
        expression = "(t[144] = false) and (t[17] = true) and (t[256]=true)",
    },
    {
        type = "Constraint",
        name = "jeszcze nie uczylismy sie grac",
        id = "48",
        expression = "(t[17] = false) and (t[256]=true)",
    },
    { type = "Constraint", name = "jeszcze mozna gume zobaczyc", id = "49", expression = "t[23] = true" },
    { type = "Constraint", name = "po wejsciu powinien byc juz diler", id = "50", expression = "t[29] = true" },
    {
        type = "Constraint",
        name = "mozemy wejsc do siedziby mafii",
        id = "51",
        expression = "(t[104] = true) and (t[35] = true)",
    },
    { type = "Constraint", name = "nowy opis po 1 rozmowie z egzema", id = "52", expression = "t[146] = true" },
    { type = "Constraint", name = "czy kowal wyszedł z domu? TAK", id = "53", expression = "t[150] = true" },
    {
        type = "Constraint",
        name = "glejt podpisany? NIE",
        id = "54",
        expression = "(t[151] = true) or (t[152] = true) or (t[153] = true) or (t[154] = true)",
    },
    { type = "Constraint", name = "glejt podpisany? TAK", id = "55", expression = "t[155] = true" },
    {
        type = "Constraint",
        name = "Czy fred dowiedział się o problemie sercowym Lekarza? TAK",
        id = "56",
        expression = "t[156] = true",
    },
    { type = "Constraint", name = "słoik", id = "57", expression = "t[157] = true" },
    { type = "Constraint", name = "Czy fred ma lattarkę? TAK", id = "58", expression = "t[68] = true" },
    {
        type = "Constraint",
        name = "Czy stodoła została otwarta? TAK Fred nie ma latarki",
        id = "59",
        expression = "(t[159] = true) and (t[68] = false)",
    },
    { type = "Constraint", name = "Czy Fred ma kawę? TAK", id = "60", expression = "t[66] = true" },
    { type = "Constraint", name = "Czy Fred ma kawę? NIE", id = "61", expression = "t[66] = false" },
    { type = "Constraint", name = "Czy ODBYŁA się już akcja z Kafarami? NIE", id = "62", expression = "t[161] = false" },
    {
        type = "Constraint",
        name = "Czy Fred ma glejt od Kowala? TAK",
        id = "63",
        expression = "(t[151] = true) or (t[152] = true) or (t[153] = true) or (t[154] = true) or (t[155] = true)",
    },
    {
        type = "Constraint",
        name = "Czy Fred ma glejt od Kowala? NIE",
        id = "64",
        expression = "(t[151] = false) and (t[152] = false) and (t[153] = false) and (t[154] = false) and (t[155] = false)",
    },
    {
        type = "Constraint",
        name = "Czy odbyła się akcja z Kafarami i grabarz podpisał glejt? TAK",
        id = "65",
        expression = "((t[153] = true) or (t[154] = true) or (t[155] = true)) and (t[161] = true)",
    },
    {
        type = "Constraint",
        name = "Czy odbyła się akcja z Kafarami i Fred ma glejt do podpisu? TAK",
        id = "66",
        expression = "((t[153] = true) or (t[154] = true) or (t[155] = true)) and (t[161] = true)",
    },
    {
        type = "Constraint",
        name = "Czy odbyla się już akcja z Kafarami i gadal z grabarzem o jego problemie?TAK+glejt pusty",
        id = "67",
        expression = "(t[161] = true) and (t[162] = true) and (t[151] = true)",
    },
    { type = "Constraint", name = "Czy Fred wystraszył Idiotów? TAK", id = "68", expression = "t[163] = true" },
    {
        type = "Constraint",
        name = "Czy Fred ma podziurawione wieczko? TAK",
        id = "69",
        expression = "(t[60] = true) and (t[156] = true)",
    },
    { type = "Constraint", name = "Czy drabina jest oparta pod oknem? TAK", id = "70", expression = "t[164] = true" },
    { type = "Constraint", name = "Czy sprawa z Malwiną zalatwiona? TAK", id = "71", expression = "t[165] = true" },
    { type = "Constraint", name = "Czy sprawa z Malwiną zalatwiona? NIE", id = "72", expression = "t[165] = false" },
    { type = "Constraint", name = "Czy akcja z wieczkiem dozwolona? TAK", id = "73", expression = "t[166] = true" },
    { type = "Constraint", name = "Fred nakarmł Świadka? TAK", id = "74", expression = "t[212] = true" },
    {
        type = "Constraint",
        name = "Początkowa sekwencja w obozie hipisów",
        id = "75",
        expression = "(t[185] = false) and (t[215] = false)",
    },
    { type = "Constraint", name = "Swiadek Jehowy widoczny", id = "76", expression = "(t[185] = true) and (t[215] = false)" },
    { type = "Constraint", name = "Fred ma maske plemienną.", id = "77", expression = "t[55] = true" },
    { type = "Constraint", name = "Odbyla się akcja z kowalem.", id = "78", expression = "t[214] = true" },
    { type = "Constraint", name = "Odbywa się akcja z kowalem TAK", id = "79", expression = "t[215] = true" },
    { type = "Constraint", name = "Czy Fred dostał właśnie od Kowala glejt? TAK", id = "80", expression = "t[216] = true" },
    { type = "Constraint", name = "fura_otwarta_mozna_zamknac", id = "81", expression = "(t[217] = true) and (t[42] = true)" },
    {
        type = "Constraint",
        name = "fura_zamknieta_mozna_otworzyc",
        id = "82",
        expression = "(t[217] = false) and (t[218] = false) and (t[42] = true)",
    },
    {
        type = "Constraint",
        name = "mozna_otworzyc_fure ale_bez gasnicy",
        id = "83",
        expression = "(t[217] = false) and (t[218] = true) and (t[42] = true)",
    },
    { type = "Constraint", name = "rozpoczecie gry", id = "84", expression = "t[229] = false" },
    { type = "Constraint", name = "mozemy przyjechac po gruche", id = "85", expression = "t[233] = false" },
    {
        type = "Constraint",
        name = "polana z grobem budzenie po piekle",
        id = "86",
        expression = "(t[229] = true) and (t[241] = true) and (t[244]=false)",
    },
    { type = "Constraint", name = "odegrac klip nieba", id = "87", expression = "t[227]=false" },
    { type = "Constraint", name = "odegrac klip piekla", id = "88", expression = "t[228]=false" },
    {
        type = "Constraint",
        name = "mozna otworzyc schowek z bez tupecika w srodku",
        id = "89",
        expression = "(t[242]=false) and (t[243]=true)",
    },
    { type = "Constraint", name = "mozna zamknac schowek", id = "90", expression = "t[242]=true" },
    {
        type = "Constraint",
        name = "schowek z zabranym tupecikiem niezaleznie czy otwarty czy zamkniety",
        id = "91",
        expression = "t[243]=true",
    },
    {
        type = "Constraint",
        name = "Czy fred dowiedział się o problemie sercowym Lekarza i Czy drabina jest oparta pod oknem? TAK",
        id = "92",
        expression = "(t[156] = true) and (t[164] = true)",
    },
    { type = "Constraint", name = "Czy kula u Winyla obraca sie? TAK", id = "93", expression = "t[246] =true" },
    {
        type = "Constraint",
        name = "Czy Fred gadał z Malwiną o podarunku od Lekarza?",
        id = "94",
        expression = "t[250] = true",
    },
    {
        type = "Constraint",
        name = "Fred załatwił sprawę z malwiną i ma pusty glejt",
        id = "95",
        expression = "(t[165] = true) and (t[151] = true)",
    },
    {
        type = "Constraint",
        name = "Fred załatwił sprawę z malwiną i ma glejt z podpisem grabarza",
        id = "96",
        expression = "(t[165] = true) and (t[153] = true)",
    },
    {
        type = "Constraint",
        name = "Czy ODBYŁA się już akcja z Kafarami? TAK a z lopatą nie.",
        id = "97",
        expression = "(t[161] = true) and (t[251] = false)",
    },
    {
        type = "Constraint",
        name = "Czy Fred dał grabarzowi łopatę? NIE i ODBYŁA się już akcja z Kafarami? TAK",
        id = "98",
        expression = "(t[251] = false) and (t[161] = true)",
    },
    {
        type = "Constraint",
        name = "Czy odbyla się już akcja z Kafarami i gadal z grabarzem o jego problemie?TAK+glejt podpisany przez lekarza",
        id = "99",
        expression = "(t[161] = true) and (t[162] = true) and (t[152] = true)",
    },
    { type = "Constraint", name = "Rybak wypił kawę", id = "100", expression = "t[252] = true" },
    { type = "Constraint", name = "Czy stodoła została otwarta? TAK", id = "101", expression = "(t[159] = true)" },
    { type = "Constraint", name = "Czy stodoła została otwarta? NIE", id = "102", expression = "(t[159] = false)" },
    {
        type = "Constraint",
        name = "Czy stodoła została otwarta? TAKZapalono światło?NIE",
        id = "103",
        expression = "(t[159] = true) and (t[253] = false)",
    },
    { type = "Constraint", name = "Zapalono światło?TAK", id = "104", expression = "t[253] = true" },
    { type = "Constraint", name = "Akcja z gangsterami?TRWA", id = "105", expression = "t[254] = true" },
    { type = "Constraint", name = "Trwa wtrącenie wątku z odesłaniem Kafarów.", id = "106", expression = "t[255] = true" },
    { type = "Constraint", name = "Pierwsza rozmowa z Nukem sie nie odbyla?TAK", id = "107", expression = "t[256]=false" },
    {
        type = "Constraint",
        name = "Odbyła się pierwsza istotna rozmowa z Kelnerem? TAK",
        id = "108",
        expression = "t[257] = true",
    },
    { type = "Constraint", name = "Odbyła się rozmowa Z FZB przy kapliczce? TAK", id = "109", expression = "t[258] = true" },
    {
        type = "Constraint",
        name = "Odbyła się druga istotna rozmowa z Kelnerem? TAK",
        id = "110",
        expression = "t[259] = true",
    },
    {
        type = "Constraint",
        name = "Odbyła się rozmowa o hejnale z DJ Radiowym? TAK",
        id = "111",
        expression = "t[260] = true",
    },
    { type = "Constraint", name = "Spotkanie z Harasymem dozwolone? TAK", id = "112", expression = "t[261] = true" },
    { type = "Constraint", name = "Odbyła się rozmowa z DJ Hajsem?TAK", id = "113", expression = "t[262] = true" },
    {
        type = "Constraint",
        name = "Odbyła się pierwsza rozmowa z tow. Romanem?TAK",
        id = "114",
        expression = "t[263] = true",
    },
    { type = "Constraint", name = "Odbyła się dezaktywacja kota tow. Romana?TAK", id = "115", expression = "t[264] = true" },
    { type = "Constraint", name = "Odbyło się odwdzieczenie sie tow. Romana?TAK", id = "116", expression = "t[265] = true" },
    {
        type = "Constraint",
        name = "Odbyło się przekazanie plyty z hejnałem DJRadiowemu? TAK",
        id = "117",
        expression = "t[266] = true",
    },
    { type = "Constraint", name = "Zamowiono linę? TAK", id = "118", expression = "t[267] = true" },
    { type = "Constraint", name = "Odbyła się rozmowa z Aldoną? TAK", id = "119", expression = "t[268] = true" },
    {
        type = "Constraint",
        name = "Nie odbyla sie rozmowa z FZB, Aldona się nie obudziła.",
        id = "120",
        expression = "(t[258] = false) and (t[269] = false)",
    },
    {
        type = "Constraint",
        name = "Odbyla sie rozmowa z FZB, Aldona się nie obudziła.",
        id = "121",
        expression = "(t[258] = true) and (t[269] = false)",
    },
    {
        type = "Constraint",
        name = "Odbyla sie rozmowa z FZB, Aldona się obudziła.",
        id = "122",
        expression = "(t[258] = true) and (t[269] = true)",
    },
    {
        type = "Constraint",
        name = "Aldona dostala nie liny, nie dostala planu klasztoru",
        id = "123",
        expression = "(t[270] = false) and (t[271] = false)",
    },
    {
        type = "Constraint",
        name = "Aldona dostala line, nie dostala planu klasztoru",
        id = "124",
        expression = "(t[270] = true) and (t[271] = false)",
    },
    {
        type = "Constraint",
        name = "Aldona nie dostala liny, dostala plan klasztoru",
        id = "125",
        expression = "(t[271] = true) and (t[270] = false)",
    },
    {
        type = "Constraint",
        name = "Aldona dostala line, dostala plan klasztoru",
        id = "126",
        expression = "(t[270] = true) and (t[271] = true)",
    },
    { type = "Constraint", name = "Sforsowanie bram Zlomowiska", id = "127", expression = "t[272] = true" },
    { type = "Constraint", name = "Po pierwszej gadce z pijącymi piwo", id = "128", expression = "t[273] = true" },
    { type = "Constraint", name = "Nadawanie hejnału trwa", id = "129", expression = "(t[275] = false)and(t[380]=true)" },
    {
        type = "Constraint",
        name = "odczytanie z ksiazki telefonu,ale brak karty kredytowej i przed udanym telefonem",
        id = "130",
        expression = "(t[276] = true) and (t[75] = false) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "odczytanie z ksiazki telefonu i jest karta kredytowa i przed udanym telefonem",
        id = "131",
        expression = "(t[276] = true) and (t[75] = true) and (t[267] = false)",
    },
    { type = "Constraint", name = "przed udanym telefonem(lina nie zamowiona)", id = "132", expression = "t[267] = false" },
    { type = "Constraint", name = "Rozbiegowka aktu", id = "133", expression = "t[277] = true" },
    { type = "Constraint", name = "Kurier z liną czeka pod Rozgłośnią", id = "134", expression = "t[278] = true" },
    { type = "Constraint", name = "Utrata miesa", id = "135", expression = "t[279] = true" },
    { type = "Constraint", name = "Otrucie psów na Złomowisku", id = "136", expression = "t[280] = true" },
    {
        type = "Constraint",
        name = "Fred ma mieso lub ma zatrute mieso",
        id = "137",
        expression = "(t[73] = true) or (t[74] = true)",
    },
    {
        type = "Constraint",
        name = "Fred nie ma żadnego mięsa, nie otruł i nie stracił mięsa",
        id = "138",
        expression = "(t[73] = false) and (t[74] = false) and (t[280] = false) and (t[279] = false)",
    },
    { type = "Constraint", name = "Dozwolony opis dmuchanego materacu", id = "139", expression = "t[281] = true" },
    { type = "Constraint", name = "Igła została przekazana DJHajsowi? TAK", id = "140", expression = "t[284] = true" },
    { type = "Constraint", name = "Odbedzie sie Spotkanie z Poslancem", id = "141", expression = "t[285] = true" },
    {
        type = "Constraint",
        name = "Odbyła się pierwsza istotna rozmowa z Kelnerem i Aldona się nie obudziła",
        id = "142",
        expression = "(t[259] = true) and (t[269] = false)",
    },
    { type = "Constraint", name = "Wyjscie przez lufcik trwa", id = "143", expression = "t[286] = true" },
    { type = "Constraint", name = "Wejscie przez lufcik do toalety trwa", id = "144", expression = "t[287] = true" },
    { type = "Constraint", name = "Czy drabina jest oparta pod oknem? Nie", id = "145", expression = "t[164] = false" },
    { type = "Constraint", name = "Odegraj komiks1? TAK", id = "146", expression = "t[293] = false" },
    { type = "Constraint", name = "Odegraj komiks2? TAK", id = "147", expression = "t[295] = false" },
    { type = "Constraint", name = "Fred zabrał gumiaki?TAK", id = "148", expression = "t[296] = true" },
    { type = "Constraint", name = "Odegra sie klip ze zniknieciem licealistów", id = "149", expression = "t[297] = true" },
    { type = "Constraint", name = "Odbyła sie pierwsza rozmowa z Wojarską? TAK", id = "150", expression = "t[299] = true" },
    { type = "Constraint", name = "Odegraj Final? TAK", id = "151", expression = "t[300] = true" },
    { type = "Constraint", name = "Fred nie zabrał łopaty znad grobu.", id = "152", expression = "t[40] = false" },
    { type = "Constraint", name = "Pies stróża nie nakarmiony.", id = "153", expression = "t[10] = false" },
    {
        type = "Constraint",
        name = "Odmowa golenia z powodu braku tupecika",
        id = "154",
        expression = "(t[32] = false) and (t[126] = false) and (t[31] = false)",
    },
    {
        type = "Constraint",
        name = "Mozna ogolic Gruche",
        id = "155",
        expression = "(t[32] = false) and (t[126] = true) and (t[31] = false)",
    },
    {
        type = "Constraint",
        name = "Nie mozna wejsc do siedziby mafii, ani wywabić stamtąd gangsterów.",
        id = "156",
        expression = "(t[35] = false) and (t[301] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Textylią 1",
        id = "157",
        expression = "(t[302] = false) and (t[143] = false) and (t[21] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Textylią 2",
        id = "158",
        expression = "(t[302] = true) and (t[143] = false) and (t[21] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Textylią 3",
        id = "159",
        expression = "(t[302] = true) and (t[143] = true) and (t[21] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Textylią 4",
        id = "160",
        expression = "(t[302] = false) and (t[143] = true) and (t[21] = false)",
    },
    { type = "Constraint", name = "Gadki z Textylią 5", id = "161", expression = "t[21] = true" },
    { type = "Constraint", name = "Odmowa golenia Chrzastka", id = "162", expression = "t[33] = true" },
    {
        type = "Constraint",
        name = "Gadki z Elektronikiem 1",
        id = "163",
        expression = "(t[303] = false) and (t[304] = false) and (t[305] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Elektronikiem 2",
        id = "164",
        expression = "(t[303] = false) and (t[304] = true) and (t[305] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Elektronikiem 3",
        id = "165",
        expression = "(t[303] = true) and (t[304] = true) and (t[305] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki z Elektronikiem 4",
        id = "166",
        expression = "(t[303] = true) and (t[304] = false) and (t[305] = false)",
    },
    { type = "Constraint", name = "Gadki z Elektronikiem 5", id = "167", expression = "t[305] = true" },
    { type = "Constraint", name = "Czy ODBYŁA się już akcja z Kafarami? TAK", id = "168", expression = "t[161] = true" },
    { type = "Constraint", name = "Gadki pani z obslugi 1", id = "169", expression = "(t[161] = false) and (t[66] = false)" },
    { type = "Constraint", name = "Gadki pani z obslugi 2", id = "170", expression = "(t[161] = true) and (t[66] = false)" },
    { type = "Constraint", name = "Gadki pani z obslugi 3", id = "171", expression = "(t[161] = true) and (t[66] = true)" },
    {
        type = "Constraint",
        name = "Gadki i inne sprawy z Malwiną 1",
        id = "172",
        expression = "(t[164] = true) and (t[156] = false) and (t[250] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki i inne sprawy z Malwiną 2",
        id = "173",
        expression = "(t[164] = true) and (t[156] = true) and (t[250] = false)",
    },
    {
        type = "Constraint",
        name = "Gadki i inne sprawy z Malwiną 3",
        id = "174",
        expression = "(t[164] = true) and (t[156] = true) and (t[250] = true)",
    },
    { type = "Constraint", name = "Wrota stodoły zamkniete", id = "175", expression = "t[306] = true" },
    {
        type = "Constraint",
        name = "Wrota stodoły otwarte - ciemne",
        id = "176",
        expression = "(t[307] = true) and (t[367] = true)",
    },
    {
        type = "Constraint",
        name = "Wrota stodoły otwarte - jasne",
        id = "177",
        expression = "(t[308] = true) and (t[367] = true)",
    },
    {
        type = "Constraint",
        name = "Zmana opisu Swiadka Jehowy i mozliwosc nakarmienia go",
        id = "178",
        expression = "t[309] = true",
    },
    {
        type = "Constraint",
        name = "Fred ma glejt podpisany przez grabarza i lekarza",
        id = "179",
        expression = "t[154] = true",
    },
    {
        type = "Constraint",
        name = "Fred ma pusty glejt i zalatwil sprawe z Malwina.",
        id = "180",
        expression = "(t[165] = true) and (t[151] = true)",
    },
    {
        type = "Constraint",
        name = "Odbyła się rozmowa Z FZB przy kapliczce? NIE",
        id = "181",
        expression = "t[258] = false",
    },
    { type = "Constraint", name = "Const techniczny", id = "182", expression = "t[359] = true" },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_1",
        id = "183",
        expression = "(t[75] = false) and (t[276] = false) and (t[266] = false) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_2",
        id = "184",
        expression = "(t[75] = false) and (t[276] = false) and (t[266] = true) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_3",
        id = "185",
        expression = "(t[75] = false) and (t[276] = true) and (t[266] = false) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_4",
        id = "186",
        expression = "(t[75] = false) and (t[276] = true) and (t[266] = true) and (t[267] = false) and (t[368] = true)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_5",
        id = "187",
        expression = "(t[75] = true) and (t[276] = false) and (t[266] = false) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_6",
        id = "188",
        expression = "(t[75] = true) and (t[276] = false) and (t[266] = true) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_7",
        id = "189",
        expression = "(t[75] = true) and (t[276] = true) and (t[266] = false) and (t[267] = false)",
    },
    {
        type = "Constraint",
        name = "Logika gadek przez telefon w rozlosni_8",
        id = "190",
        expression = "(t[75] = true) and (t[276] = true) and (t[266] = true) and (t[267] = false) and (t[368] = true)",
    },
    { type = "Constraint", name = "Logika gadek przez telefon w rozlosni_9", id = "191", expression = "t[267] = true" },
    { type = "Constraint", name = "Odegrana akcja z bandytowozem", id = "192", expression = "t[38] = true" },
    { type = "Constraint", name = "Mozna gadac z Pania z Obslugi? TAK", id = "193", expression = "t[360] = true" },
    { type = "Constraint", name = "Mozna gadac z Pania z obslugi? NIE", id = "194", expression = "t[360] = false" },
    {
        type = "Constraint",
        name = "Mozna odebrac plan klasztoru? TAK",
        id = "195",
        expression = "(t[89] = true) and (t[361] = true)  and (t[369] = false)",
    },
    { type = "Constraint", name = "Drzwi do biblioteki otwarte? TAK", id = "196", expression = "t[361] = true" },
    { type = "Constraint", name = "Lekarz jest w domu? TAK", id = "197", expression = "t[362] = false" },
    { type = "Constraint", name = "Lekarza nie ma w domu? TAK", id = "198", expression = "t[362] = true" },
    { type = "Constraint", name = "Kot pije mleko? TAK", id = "199", expression = "t[363] = true" },
    { type = "Constraint", name = "Kot pije mleko? NIE", id = "200", expression = "t[363] = false" },
    { type = "Constraint", name = "Odegrac klip o nowej sciezce? TAK", id = "201", expression = "t[364] = true" },
    { type = "Constraint", name = "Jorge wyszedl? TAK", id = "202", expression = "t[365] = true" },
    { type = "Constraint", name = "Dozwolone gadki z Yorkiem", id = "203", expression = "t[366] = true" },
    {
        type = "Constraint",
        name = "Wrota stodoły otwarte - ciemne - pierwsze wejscie",
        id = "204",
        expression = "(t[307] = true) and (t[367] = false)",
    },
    { type = "Constraint", name = "always true", id = "205", expression = "(t[87] = true)" },
    {
        type = "Constraint",
        name = "Mozna odebrac plan klasztoru? NIE",
        id = "206",
        expression = "(t[89] = false) and (t[361] = true)  and (t[369] = false)",
    },
    {
        type = "Constraint",
        name = "Drzwi do biblioteki otwarte? NIE",
        id = "207",
        expression = "(t[361] = false) and (t[369] = false)",
    },
    { type = "Constraint", name = "Bagaznik bez kluczykow1", id = "208", expression = "(t[217] = true)" },
    {
        type = "Constraint",
        name = "Bagaznik bez kluczykow2",
        id = "209",
        expression = "(t[217] = false) and (t[218] = false)",
    },
    { type = "Constraint", name = "Bagaznik bez kluczykow3", id = "210", expression = "(t[217] = false) and (t[218] = true)" },
    { type = "Constraint", name = "Po ogoleniu Gruchy do końca", id = "211", expression = "t[31] = true" },
    {
        type = "Constraint",
        name = "Podmiana mapy wis w zajeździe",
        id = "212",
        expression = "(t[269] = true) and (t[370] = false)",
    },
    {
        type = "Constraint",
        name = "czy fred miał już tripa kaczkę? NIE.",
        id = "213",
        expression = "(t[35] = true) and (t[371] = false)",
    },
    {
        type = "Constraint",
        name = "czy fred miał już tripa aliena? NIE.",
        id = "214",
        expression = "(t[333] = true) and (t[372] = false)",
    },
    {
        type = "Constraint",
        name = "Czy mamy zlecenie od rybaka? Tak",
        id = "215",
        expression = "(t[373] = true) and(t[252]=false)",
    },
    {
        type = "Constraint",
        name = "czy zabraliśmy igłę? NIE",
        id = "216",
        expression = "(t[262] = true) and(t[374]=false)",
    },
    { type = "Constraint", name = "Jesteśmy 1 raz na zakończeniu", id = "217", expression = "t[376]=false" },
    {
        type = "Constraint",
        name = "Wrota stodoły otwarte sa ciemne otwarte i nic wiecej",
        id = "218",
        expression = "t[307] = true",
    },
    {
        type = "Constraint",
        name = "Po otruciu psów i przed otwarciem furtki",
        id = "219",
        expression = "(t[280] = true) and (t[272] = false)",
    },
    {
        type = "Constraint",
        name = "Przed otruciem psów i przed otwarciem furtki",
        id = "220",
        expression = "(t[280] = false) and (t[272] = false)",
    },
    {
        type = "Constraint",
        name = "wiemy o problemie laekarza ale nie mamy podziurawionego wieczka",
        id = "221",
        expression = "(t[60] =false) and (t[156] = true)",
    },
    { type = "Constraint", name = "wiemy, ze malwina to malwina", id = "222", expression = "(t[379]=true)" },
    {
        type = "Constraint",
        name = "oko na malwine po wizycie u doktorka",
        id = "223",
        expression = "(t[156] = true)and(t[379]=false)",
    },
    {
        type = "Constraint",
        name = "tera bedzie nieudana gadka z bibliotekarką",
        id = "224",
        expression = "(t[89]=false)and(t[361]=true)",
    },
    {
        type = "Constraint",
        name = "hejnał się skończył ale jeszcze nie mamy karty",
        id = "225",
        expression = "(t[275] = true)and(t[380]=true)",
    },
    {
        type = "Constraint",
        name = "wiemy juz o wampirze i mozemy wystraszyc zapytac o niego idiotow.",
        id = "226",
        expression = "(t[163] = false)and(t[381]=true)",
    },
    { type = "Constraint", name = "otwarty klasztor", id = "227", expression = "t[382]=true" },
}