return {
    {
        type = "Item",
        przedmiot = "Lopata",
        filename = "INV_1",
        text = "Fajna łopata.",
        picname = "INV_1.png",
        cursorname = "INV_1_kurs.png",
        id = "1",
        trigger_id = "40",
        displayname = "Łopata",
    },
    {
        type = "Item",
        przedmiot = "Patyk",
        filename = "INV_2",
        text = "Kawał badyla.",
        picname = "INV_2.png",
        cursorname = "INV_2_kurs.png",
        id = "2",
        trigger_id = "41",
        displayname = "Patyk",
    },
    {
        type = "Item",
        przedmiot = "Kluczyki_od_samochodu",
        filename = "INV_3",
        text = "Kluczyki od mojej zajebistej fury.",
        picname = "INV_3.png",
        cursorname = "INV_3_kurs.png",
        id = "3",
        trigger_id = "42",
        displayname = "Kluczyki od samochodu",
    },
    {
        type = "Item",
        przedmiot = "Silnik_od_golarki_elektrycznej",
        filename = "INV_4",
        text = "Prawie kompletna golarka.",
        picname = "INV_4.png",
        cursorname = "INV_4_kurs.png",
        id = "4",
        trigger_id = "43",
        displayname = "Silnik od golarki elektrycznej",
    },
    {
        type = "Item",
        przedmiot = "Puszka_oleju_silnikowego",
        filename = "INV_5",
        text = "Puszka oleju czarnego jak smoła.",
        picname = "INV_5.png",
        cursorname = "INV_5_kurs.png",
        id = "5",
        trigger_id = "44",
        displayname = "Puszka oleju silnikowego",
    },
    {
        type = "Item",
        przedmiot = "Woda_utleniona",
        filename = "INV_6",
        text = "Woda utleniona wzięta zasadniczo z apteczki.",
        picname = "INV_6.png",
        cursorname = "INV_6_kurs.png",
        id = "6",
        trigger_id = "45",
        displayname = "Woda utleniona",
    },
    {
        type = "Item",
        przedmiot = "Bandaz",
        filename = "INV_7",
        text = "Bandaż zabrany z apteczki. Zasadniczo.",
        picname = "INV_7.png",
        cursorname = "INV_7_kurs.png",
        id = "7",
        trigger_id = "46",
        displayname = "Bandaż",
    },
    {
        type = "Item",
        przedmiot = "Hot-Dog",
        filename = "INV_8",
        text = "Pieskie żarcie.",
        picname = "INV_8.png",
        cursorname = "INV_8_kurs.png",
        id = "8",
        trigger_id = "47",
        displayname = "Hot-dog",
    },
    {
        type = "Item",
        przedmiot = "Stalowa_linka",
        filename = "INV_9",
        text = "Stalowa linka. Można na niej konia powiesić.",
        picname = "INV_9.png",
        cursorname = "INV_9_kurs.png",
        id = "9",
        trigger_id = "48",
        displayname = "Stalowa linka",
    },
    {
        type = "Item",
        przedmiot = "Guma_przylepiona_u_podstawy_aparatu_telefonicznego_nr_4",
        filename = "INV_10",
        text = "Żuta po każdym posiłku. Przekazywana z pokolenia na pokolenie.",
        picname = "INV_10.png",
        cursorname = "INV_10_kurs.png",
        id = "10",
        trigger_id = "49",
        displayname = "Guma do żucia",
    },
    {
        type = "Item",
        przedmiot = "Moneta_wyjęta_z_gumy_do_zucia",
        filename = "INV_11",
        text = "O, a tu scenarzysta się nie wysilił!",
        picname = "INV_11.png",
        cursorname = "INV_11_kurs.png",
        id = "11",
        trigger_id = "50",
        displayname = "Moneta wyjęta z gumy do żucia",
    },
    {
        type = "Item",
        przedmiot = "Bateria",
        filename = "INV_12",
        text = "Bateryja.",
        picname = "INV_12.png",
        cursorname = "INV_12_kurs.png",
        id = "12",
        trigger_id = "51",
        displayname = "Bateria",
    },
    {
        type = "Item",
        przedmiot = "Kadlub_golarki_elektrycznej",
        filename = "INV_13",
        text = "Kadłub golarki elektrycznej. W zasadzie połowa golarki.",
        picname = "INV_13.png",
        cursorname = "INV_13_kurs.png",
        id = "13",
        trigger_id = "52",
        displayname = "Kadłub golarki elektrycznej",
    },
    {
        type = "Item",
        przedmiot = "Kartka z numerem tel. Dilera",
        filename = "INV_14",
        text = "To kartka z numerem telefonu dilera narkotyków. Dostaliśmy ją od Nuke&apos;a.",
        picname = "INV_14.png",
        cursorname = "INV_14_kurs.png",
        id = "14",
        trigger_id = "53",
        displayname = "Kartka z numerem tel. Dilera",
    },
    {
        type = "Item",
        przedmiot = "Dresik",
        filename = "INV_15",
        text = "Kreszowy dres. Klasyczna sprawa.",
        picname = "INV_15.png",
        cursorname = "INV_15_kurs.png",
        id = "15",
        trigger_id = "54",
        displayname = "Dresik",
    },
    {
        type = "Item",
        przedmiot = "Maska_plemienna",
        filename = "INV_16",
        text = "Świetna sprawa taka plemienna maska. Ekstra byłoby w niej na kogoś wyskoczyć.",
        picname = "INV_16.png",
        cursorname = "INV_16_kurs.png",
        id = "16",
        trigger_id = "55",
        displayname = "Maska plemienna",
    },
    {
        type = "Item",
        przedmiot = "Jablko",
        filename = "INV_17",
        text = "Ładne jabłko. Aż chce się je zjeść.",
        picname = "INV_17.png",
        cursorname = "INV_17_kurs.png",
        id = "17",
        trigger_id = "56",
        displayname = "Jabłko",
    },
    {
        type = "Item",
        przedmiot = "Lom",
        filename = "INV_18",
        text = "Łom kowala. Może nie najbardziej klasyczne narzędzie, ale zawsze..",
        picname = "INV_18.png",
        cursorname = "INV_18_kurs.png",
        id = "18",
        trigger_id = "57",
        displayname = "Łom",
    },
    {
        type = "Item",
        przedmiot = "Sloik",
        filename = "INV_19",
        text = "Szklany słoik. Znalazłem go chyba za przystankiem w tej nudnej jak uhm... wsi.",
        picname = "INV_19.png",
        cursorname = "INV_19_kurs.png",
        id = "19",
        trigger_id = "58",
        displayname = "Słoik",
    },
    {
        type = "Item",
        przedmiot = "Wieczko",
        filename = "INV_20",
        text = "Zakrętka od słoika. Pokrywka, znaczy.",
        picname = "INV_20.png",
        cursorname = "INV_20_kurs.png",
        id = "20",
        trigger_id = "59",
        displayname = "Wieczko",
    },
    {
        type = "Item",
        przedmiot = "Podziurawione_wieczko",
        filename = "INV_21",
        text = "No bardzo fajne sitko, nie uważasz?",
        picname = "INV_21.png",
        cursorname = "INV_21_kurs.png",
        id = "21",
        trigger_id = "60",
        displayname = "Podziurawione wieczko",
    },
    {
        type = "Item",
        przedmiot = "Sloik_z_podziurawionym_wieczkiem",
        filename = "INV_22",
        text = "Słoik z sitkiem zamiast wieczka.",
        picname = "INV_22.png",
        cursorname = "INV_22_kurs.png",
        id = "22",
        trigger_id = "61",
        displayname = "Słoik z podziurawionym wieczkiem",
    },
    {
        type = "Item",
        przedmiot = "Zakrecony_sloik",
        filename = "INV_23",
        text = "Zakręcony jak Reni Jusis.",
        picname = "INV_23.png",
        cursorname = "INV_23_kurs.png",
        id = "23",
        trigger_id = "62",
        displayname = "Zakręcony słoik",
    },
    {
        type = "Item",
        przedmiot = "Srodki_nasenne",
        filename = "INV_24",
        text = "Bardzo silne środki nasenne. To jest, nasenno-znieczulające.",
        picname = "INV_24.png",
        cursorname = "INV_24_kurs.png",
        id = "24",
        trigger_id = "63",
        displayname = "Środki nasenne",
    },
    {
        type = "Item",
        przedmiot = "Noz",
        filename = "INV_25",
        text = "Nóż zabrany z ogrodu doktorka",
        picname = "INV_25.png",
        cursorname = "INV_25_kurs.png",
        id = "25",
        trigger_id = "64",
        displayname = "Nóż",
    },
    {
        type = "Item",
        przedmiot = "Drabina",
        filename = "INV_26",
        text = "Całkiem przyjemna drabina.",
        picname = "INV_26.png",
        cursorname = "INV_26_kurs.png",
        id = "26",
        trigger_id = "65",
        displayname = "Drabina",
    },
    {
        type = "Item",
        przedmiot = "Promocyjna_kawa",
        filename = "INV_27",
        text = "Kubek pełen kawy.",
        picname = "INV_27.png",
        cursorname = "INV_27_kurs.png",
        id = "27",
        trigger_id = "66",
        displayname = "Promocyjna kawa",
    },
    {
        type = "Item",
        przedmiot = "Spinka_do_wlosow",
        filename = "INV_28",
        text = "Spinka do włosów. Jeden z bardziej uniwersalnych przedmiotów na świecie.",
        picname = "INV_28.png",
        cursorname = "INV_28_kurs.png",
        id = "28",
        trigger_id = "67",
        displayname = "Spinka do włosów",
    },
    {
        type = "Item",
        przedmiot = "Latarka",
        filename = "INV_29",
        text = "Latarka – bardzo przydatna rzecz. Zwłaszcza na wsi, w środku nocy.",
        picname = "INV_29.png",
        cursorname = "INV_29_kurs.png",
        id = "29",
        trigger_id = "68",
        displayname = "Latarka",
    },
    {
        type = "Item",
        przedmiot = "Ryba",
        filename = "INV_30",
        text = "Motyw pasyjno-religijny.",
        picname = "INV_30.png",
        cursorname = "INV_30_kurs.png",
        id = "30",
        trigger_id = "69",
        displayname = "Ryba",
    },
    {
        type = "Item",
        przedmiot = "Zloty_pierscionek",
        filename = "INV_31",
        text = "Złoty pierścionek, który znalazłem wewnątrz ryby. Ciekawe, jak się tam dostał?",
        picname = "INV_31.png",
        cursorname = "INV_31_kurs.png",
        id = "31",
        trigger_id = "70",
        displayname = "Złoty pierścionek",
    },
    {
        type = "Item",
        przedmiot = "Swietliki",
        filename = "INV_32",
        text = "Świetliki... Słyszałem, że laskom się takie akcje podobają. Że romantyczne takie.",
        picname = "INV_32.png",
        cursorname = "INV_32_kurs.png",
        id = "32",
        trigger_id = "71",
        displayname = "Świetliki",
    },
    {
        type = "Item",
        przedmiot = "Ksiazka_telefoniczna",
        filename = "Ksiazka",
        text = "Oficjalne wydawnictwo niegdysiejszego monopolisty.",
        picname = "INV_33.png",
        cursorname = "INV_33_kurs.png",
        id = "33",
        trigger_id = "72",
        displayname = "Książka telefoniczna",
    },
    {
        type = "Item",
        przedmiot = "Porcja_Miesa",
        filename = "INV_34",
        text = "Ochłap ścierwa. Krwawy.",
        picname = "INV_34.png",
        cursorname = "INV_34_kurs.png",
        id = "34",
        trigger_id = "73",
        displayname = "Porcja mięsa",
    },
    {
        type = "Item",
        przedmiot = "Zatrtute_Mieso",
        filename = "INV_35",
        text = "Porcja zatrutego mięsa. Na mord z nim można pójść.",
        picname = "INV_35.png",
        cursorname = "INV_35_kurs.png",
        id = "35",
        trigger_id = "74",
        displayname = "Zatrtute mięso",
    },
    {
        type = "Item",
        przedmiot = "Karta_kredytowa",
        filename = "INV_36",
        text = "To karta kredytowa DJ-a z lokalnego radia.",
        picname = "INV_36.png",
        cursorname = "INV_36_kurs.png",
        id = "36",
        trigger_id = "75",
        displayname = "Karta kredytowa",
    },
    {
        type = "Item",
        przedmiot = "Butelka_mleka",
        filename = "INV_37",
        text = "Mleko. Na zęby dobre.",
        picname = "INV_37.png",
        cursorname = "INV_37_kurs.png",
        id = "37",
        trigger_id = "76",
        displayname = "Butelka mleka",
    },
    {
        type = "Item",
        przedmiot = "Srubokret_z_ulamana_raczka",
        filename = "INV_38",
        text = "Mam niejasne przeczucie, że ten śrubokręt okaże się w pewnym momencie niezastąpiony.",
        picname = "INV_38.png",
        cursorname = "INV_38_kurs.png",
        id = "38",
        trigger_id = "77",
        displayname = "Śrubokręt z ułamaną rączką",
    },
    {
        type = "Item",
        przedmiot = "Prawie_Dobre_Gumiaki",
        filename = "INV_39",
        text = "Prawie dobre gumiaki. Tylko z  jednej strony takie trochę zwęglone.",
        picname = "INV_39.png",
        cursorname = "INV_39_kurs.png",
        id = "39",
        trigger_id = "78",
        displayname = "Prawie dobre gumiaki",
    },
    {
        type = "Item",
        przedmiot = "Kilkadziesiat_Metrow_Liny",
        filename = "INV_40",
        text = "Kilkadziesiąt solidnych metrów liny.",
        picname = "INV_40.png",
        cursorname = "INV_40_kurs.png",
        id = "40",
        trigger_id = "79",
        displayname = "Kilkadziesiąt metrów liny",
    },
    {
        type = "Item",
        przedmiot = "Mapa_Klasztoru",
        filename = "INV_41",
        text = "To mój plan awaryjny.",
        picname = "INV_41.png",
        cursorname = "INV_41_kurs.png",
        id = "41",
        trigger_id = "80",
        displayname = "Mapa klasztoru",
    },
    {
        type = "Item",
        przedmiot = "Ulotki_partyjne",
        filename = "INV_42",
        text = "To ulotka Ligi Ludzi Pracy.",
        picname = "INV_42.png",
        cursorname = "INV_42_kurs.png",
        id = "42",
        trigger_id = "81",
        displayname = "Ulotki partyjne",
    },
    {
        type = "Item",
        przedmiot = "Tyczka",
        filename = "INV_43",
        text = "Tyczka. Taka do warzyw.",
        picname = "INV_43.png",
        cursorname = "INV_43_kurs.png",
        id = "43",
        trigger_id = "82",
        displayname = "Tyczka",
    },
    {
        type = "Item",
        przedmiot = "Dziwna_Podkowa",
        filename = "INV_44",
        text = "Jakaś dziwna ta podkowa.",
        picname = "INV_44.png",
        cursorname = "INV_44_kurs.png",
        id = "44",
        trigger_id = "83",
        displayname = "Dziwna podkowa",
    },
    {
        type = "Item",
        przedmiot = "Magnes",
        filename = "INV_45",
        text = "Magnes. Taki to się zawsze przyda.",
        picname = "INV_45.png",
        cursorname = "INV_45_kurs.png",
        id = "45",
        trigger_id = "84",
        displayname = "Magnes",
    },
    {
        type = "Item",
        przedmiot = "Igla",
        filename = "INV_46",
        text = "Igła. Ta słynna, ze stogu siana.",
        picname = "INV_46.png",
        cursorname = "INV_46_kurs.png",
        id = "46",
        trigger_id = "85",
        displayname = "Igła",
    },
    {
        type = "Item",
        przedmiot = "Szkatułka_z_Relikwia",
        filename = "INV_47",
        text = "To dla takiej skrzyneczki  tyle się namęczyłem?!",
        picname = "INV_47.png",
        cursorname = "INV_47_kurs.png",
        id = "47",
        trigger_id = "86",
        displayname = "Szkatułka z relikwią",
    },
    {
        type = "Item",
        przedmiot = "Giwera_Freda",
        filename = "INV_48",
        text = "To moja ekstra zabójcza giwera. Jest ze mną przez cały czas mojej gangsterskiej kariery.",
        picname = "INV_48.png",
        cursorname = "INV_48_kurs.png",
        id = "48",
        trigger_id = "87",
        displayname = "Giwera Freda",
    },
    {
        type = "Item",
        przedmiot = "Plyta_z_Hejnalem_Mariackim",
        filename = "INV_49",
        text = "Płyta z Hejnałem Mariackim zmiksowana przez DJ-a Hajsa. Zioom.",
        picname = "INV_49.png",
        cursorname = "INV_49_kurs.png",
        id = "49",
        trigger_id = "88",
        displayname = "Płyta z hejnałem mariackim",
    },
    {
        type = "Item",
        przedmiot = "Karta_biblioteczna",
        filename = "INV_50",
        text = "Karta dająca mi dostęp do biblioteki.",
        picname = "INV_50.png",
        cursorname = "INV_50_kurs.png",
        id = "50",
        trigger_id = "89",
        displayname = "Karta biblioteczna",
    },
    {
        type = "Item",
        przedmiot = "Plan_Klasztoru",
        filename = "INV_51",
        text = "To mój plan awaryjny.",
        picname = "INV_51.png",
        cursorname = "INV_51_kurs.png",
        id = "51",
        trigger_id = "90",
        displayname = "Plan klasztoru",
    },
    {
        type = "Item",
        przedmiot = "Maszynka_do_golenia",
        filename = "INV_52",
        text = "To taka maszynka, tyle że do golenia.",
        picname = "INV_52.png",
        cursorname = "INV_52_kurs.png",
        id = "52",
        trigger_id = "91",
        displayname = "Maszynka do golenia",
    },
    {
        type = "Item",
        przedmiot = "Tupecik",
        filename = "INV_53",
        text = "Sztuczne włosy, to jak sztuczne zęby.",
        picname = "INV_53.png",
        cursorname = "INV_53_kurs.png",
        id = "53",
        trigger_id = "126",
        displayname = "Tupecik",
    },
    {
        type = "Item",
        przedmiot = "Owoc_krzaka_ozdobnego",
        filename = "INV_54",
        text = "To chyba kumkłat.",
        picname = "INV_54.png",
        cursorname = "INV_54_kurs.png",
        id = "54",
        trigger_id = "131",
        displayname = "Owoc krzaka ozdobnego",
    },
    {
        type = "Item",
        przedmiot = "Ryba_wypatroszona",
        filename = "INV_55",
        text = "Pusta ryba.",
        picname = "INV_55.png",
        cursorname = "INV_55_kurs.png",
        id = "55",
        trigger_id = "145",
        displayname = "Wypatroszona ryba",
    },
    {
        type = "Item",
        przedmiot = "Sztuczne_kwiaty",
        filename = "INV_56",
        text = "Plastykowe kwiatuszki.",
        picname = "INV_56.png",
        cursorname = "INV_56_kurs.png",
        id = "56",
        trigger_id = "147",
        displayname = "Sztuczne kwiatki",
    },
    {
        type = "Item",
        przedmiot = "Sloik_z_martwymi_swietlikami",
        filename = "INV_57",
        text = "Słoik, a w środku świetliki - szkoda, że martwe. Podusiły się robaczki.",
        picname = "INV_57.png",
        cursorname = "INV_57_kurs.png",
        id = "57",
        trigger_id = "148",
        displayname = "Martwe świetliki",
    },
    {
        type = "Item",
        przedmiot = "Sloik_z_zywymi_swietlikami",
        filename = "INV_58",
        text = "Świetliki... Słyszałem, że laskom się takie akcje podobają. Że romantyczne takie.",
        picname = "INV_58.png",
        cursorname = "INV_58_kurs.png",
        id = "58",
        trigger_id = "149",
        displayname = "Słoik z żywymi świetlikami",
    },
    {
        type = "Item",
        przedmiot = "Glejt_bez_podpisow",
        filename = "INV_59",
        text = "To Glejt, który muszą podpisać:pracownik służby zdrowia, pracownik cmentarza oraz świadek. Skąd mam je niby wziąć? I to o tej porze w dodatku..",
        picname = "INV_59.png",
        cursorname = "INV_59_kurs.png",
        id = "59",
        trigger_id = "151",
        displayname = "Glejt",
    },
    {
        type = "Item",
        przedmiot = "Glejt_z_podpisem_lekarza",
        filename = "INV_60",
        text = "Oo.. Jeszcze tylko pozostał podpis pracownika cmentarza i świadka.",
        picname = "INV_60.png",
        cursorname = "INV_60_kurs.png",
        id = "60",
        trigger_id = "152",
        displayname = "Glejt",
    },
    {
        type = "Item",
        przedmiot = "Glejt_z_podpisem_grabarza",
        filename = "INV_61",
        text = "Oo.. Jeszcze tylko pozostał podpis lekarza i świadka.",
        picname = "INV_61.png",
        cursorname = "INV_61_kurs.png",
        id = "61",
        trigger_id = "153",
        displayname = "Glejt",
    },
    {
        type = "Item",
        przedmiot = "Glejt_z_podpisami_lekarza_i_grabarza",
        filename = "INV_62",
        text = "Oho.. Pozostał mi już tylko podpis świadka.",
        picname = "INV_62.png",
        cursorname = "INV_62_kurs.png",
        id = "62",
        trigger_id = "154",
        displayname = "Glejt",
    },
    {
        type = "Item",
        przedmiot = "Glejt_z_trzema_podpisami",
        filename = "INV_63",
        text = "Glejt dla kowala z trzema niezbędnymi podpisami!",
        picname = "INV_63.png",
        cursorname = "INV_63_kurs.png",
        id = "63",
        trigger_id = "155",
        displayname = "Glejt",
    },
    {
        type = "Item",
        przedmiot = "Pokrojone_jablko",
        filename = "INV_64",
        text = "Swieżutkie jabłko. Do tego obrane i pokrojone. Aż chce się je zjeść.",
        picname = "INV_64.png",
        cursorname = "INV_64_kurs.png",
        id = "64",
        trigger_id = "158",
        displayname = "Pokrojone jabłko",
    },
    {
        type = "Item",
        przedmiot = "Pusty_kubek_po_kawie",
        filename = "INV_65",
        text = "Kubek jest, kawy brak. Albo wypiłem, albo rozlałem...",
        picname = "INV_65.png",
        cursorname = "INV_65_kurs.png",
        id = "65",
        trigger_id = "160",
        displayname = "Kubek po kawie",
    },
    {
        type = "Item",
        przedmiot = "Ryba_upieczona",
        filename = "INV_66",
        text = "Upieczona ryba",
        picname = "INV_66.png",
        cursorname = "INV_66_kurs.png",
        id = "66",
        trigger_id = "213",
        displayname = "Upieczona ryba",
    },
    {
        type = "Item",
        przedmiot = "Gasnica",
        filename = "INV_67",
        text = "To gaśnica z bagażnika Szatańskiej Fury.",
        picname = "INV_67.png",
        cursorname = "INV_67_kurs.png",
        id = "67",
        trigger_id = "219",
        displayname = "Gaśnica",
    },
    {
        type = "Item",
        przedmiot = "100_neuro",
        filename = "INV_68",
        text = "100 neuro bardzo fajny papierek",
        picname = "INV_68.png",
        cursorname = "INV_68_kurs.png",
        id = "68",
        trigger_id = "245",
        displayname = "100 neuro",
    },
    {
        type = "Item",
        przedmiot = "Spodek",
        filename = "INV_69",
        text = "Porcelanowy spodek.",
        picname = "INV_69.png",
        cursorname = "INV_69_kurs.png",
        id = "69",
        trigger_id = "274",
        displayname = "Spodek",
    },
    {
        type = "Item",
        przedmiot = "Spodek_z_mlekiem",
        filename = "INV_70",
        text = "Spodek z mlekiem.",
        picname = "INV_70.png",
        cursorname = "INV_70_kurs.png",
        id = "71",
        trigger_id = "283",
        displayname = "Spodek z mlekiem",
    },
    {
        type = "Item",
        przedmiot = "Stringi",
        filename = "INV_71",
        text = "To prawdziwe stringi - nie, że jakieś gacie po tacie.",
        picname = "INV_71.png",
        cursorname = "INV_71_kurs.png",
        id = "72",
        trigger_id = "288",
        displayname = "Stringi",
    },
    {
        type = "Item",
        przedmiot = "Magnes_z_igla",
        filename = "INV_72",
        text = "To magnes, który przyciągnął igłę.",
        picname = "INV_72.png",
        cursorname = "INV_72_kurs.png",
        id = "73",
        trigger_id = "289",
        displayname = "Magnes z igłą",
    },
    {
        type = "Item",
        przedmiot = "Butelka_po_mleku",
        filename = "INV_73",
        text = "Pusta butelka po mleku.",
        picname = "INV_73.png",
        cursorname = "INV_73_kurs.png",
        id = "74",
        trigger_id = "290",
        displayname = "Pusta butelka",
    },
    {
        type = "Item",
        przedmiot = "Butelka_z_woda",
        filename = "INV_74",
        text = "Butelka, którą napełniłem wodą.",
        picname = "INV_74.png",
        cursorname = "INV_74_kurs.png",
        id = "75",
        trigger_id = "291",
        displayname = "Butelka z wodą",
    },
    {
        type = "Item",
        przedmiot = "Wlasciwy_kluczyk",
        filename = "INV_75",
        text = "Kluczyk, który znalazlem w krypcie.",
        picname = "INV_75.png",
        cursorname = "INV_75_kurs.png",
        id = "76",
        trigger_id = "298",
        displayname = "Ten właściwy kluczyk",
    },
}