return {
	{
		fred_x = "124",
		fred_direction = "C",
		grucha_x = "51",
		fred_y = "494",
		grucha_direction = "C",
		source = "PARKING STRZEZONY",
		grucha_y = "487",
		dest = "SKEJTPARK 1",
	},
	{
		fred_x = "939",
		fred_direction = "G",
		grucha_x = "829",
		fred_y = "567",
		grucha_direction = "G",
		source = "SKEJTPARK 1",
		grucha_y = "533",
		dest = "PARKING STRZEZONY",
	},
	{
		fred_x = "939",
		fred_direction = "G",
		grucha_x = "829",
		fred_y = "567",
		grucha_direction = "G",
		source = "SKEJTPARK 2",
		grucha_y = "533",
		dest = "PARKING STRZEZONY",
	},
	{
		fred_x = "303",
		fred_direction = "A",
		grucha_x = "410",
		fred_y = "507",
		grucha_direction = "A",
		source = "PARKING STRZEZONY",
		grucha_y = "534",
		dest = "NULL",
	},
	{
		fred_x = "508",
		fred_direction = "A",
		grucha_x = "339",
		fred_y = "546",
		grucha_direction = "A",
		source = "SKEJTPARK 1",
		grucha_y = "531",
		dest = "NULL",
	},
	{
		fred_x = "292",
		fred_direction = "A",
		grucha_x = "445",
		fred_y = "580",
		grucha_direction = "A",
		source = "SKEJTPARK 2",
		grucha_y = "590",
		dest = "NULL",
	},
	{
		fred_x = "238",
		fred_direction = "A",
		grucha_x = "317",
		fred_y = "529",
		grucha_direction = "A",
		source = "OKOLICE KOSCIOLA",
		grucha_y = "574",
		dest = "NULL",
	},
	{
		fred_x = "1093",
		fred_direction = "A",
		grucha_x = "945",
		fred_y = "560",
		grucha_direction = "A",
		source = "SZKOLA",
		grucha_y = "558",
		dest = "NULL",
	},
	{
		fred_x = "582",
		fred_direction = "A",
		grucha_x = "405",
		fred_y = "525",
		grucha_direction = "A",
		source = "BOISKO SZKOLNE",
		grucha_y = "531",
		dest = "NULL",
	},
	{
		fred_x = "150",
		fred_direction = "A",
		grucha_x = "84",
		fred_y = "361",
		grucha_direction = "A",
		source = "SKLEP PLYTOWY",
		grucha_y = "411",
		dest = "NULL",
	},
	{
		fred_x = "1086",
		fred_direction = "A",
		grucha_x = "1207",
		fred_y = "536",
		grucha_direction = "A",
		source = "CENTRUM HANDLOWE",
		grucha_y = "522",
		dest = "NULL",
	},
	{
		fred_x = "1066",
		fred_direction = "A",
		grucha_x = "896",
		fred_y = "565",
		grucha_direction = "A",
		source = "KAFEJKA INTERNETOWA",
		grucha_y = "540",
		dest = "NULL",
	},
	{
		fred_x = "1093",
		fred_direction = "G",
		grucha_x = "1006",
		fred_y = "575",
		grucha_direction = "G",
		source = "SZKOLA",
		grucha_y = "553",
		dest = "KAFEJKA INTERNETOWA",
	},
	{
		fred_x = "104",
		fred_direction = "C",
		grucha_x = "160",
		fred_y = "510",
		grucha_direction = "C",
		source = "SKLEP PLYTOWY",
		grucha_y = "573",
		dest = "CENTRUM HANDLOWE",
	},
	{
		fred_x = "390",
		fred_direction = "A",
		grucha_x = "522",
		fred_y = "552",
		grucha_direction = "A",
		source = "PLAC ZA MIASTEM",
		grucha_y = "457",
		dest = "NULL",
	},
	{
		fred_x = "70",
		fred_direction = "C",
		grucha_x = "110",
		fred_y = "584",
		grucha_direction = "C",
		source = "KAFEJKA INTERNETOWA",
		grucha_y = "501",
		dest = "SIEDZIBA MAFII",
	},
	{
		fred_x = "637",
		fred_direction = "G",
		grucha_x = "749",
		fred_y = "565",
		grucha_direction = "G",
		source = "SKEJTPARK 1",
		grucha_y = "559",
		dest = "SKEJTPARK 2",
	},
	{
		fred_x = "474",
		fred_direction = "H",
		grucha_x = "556",
		fred_y = "507",
		grucha_direction = "H",
		source = "SKEJTPARK 2",
		grucha_y = "531",
		dest = "SKEJTPARK 1",
	},
	{
		fred_x = "858",
		fred_direction = "G",
		grucha_x = "766",
		fred_y = "568",
		grucha_direction = "G",
		source = "SZKOLA",
		grucha_y = "515",
		dest = "BOISKO SZKOLNE",
	},
	{
		fred_x = "477",
		fred_direction = "A",
		grucha_x = "334",
		fred_y = "434",
		grucha_direction = "A",
		source = "BOISKO SZKOLNE",
		grucha_y = "436",
		dest = "SZKOLA",
	},
	{
		fred_x = "370",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "570",
		grucha_direction = "E",
		source = "DOM KOWALA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "360",
		fred_direction = "E",
		grucha_x = "0",
		fred_y = "580",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "380",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "425",
		grucha_direction = "E",
		source = "STODOLA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "-10",
		fred_direction = "",
		grucha_x = "0",
		fred_y = "-10",
		grucha_direction = "",
		source = "KOMIKS1",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "450",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "570",
		grucha_direction = "E",
		source = "KOMIKS1",
		grucha_y = "0",
		dest = "OBOZ HIPPISOW",
	},
	{
		fred_x = "450",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "570",
		grucha_direction = "E",
		source = "OBOZ HIPPISOW",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "100",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "580",
		grucha_direction = "E",
		source = "DOM LEKARZA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "250",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "580",
		grucha_direction = "E",
		source = "OGROD ZA DOMEM LEKARZA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "390",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "540",
		grucha_direction = "E",
		source = "STACJA BENZYNOWA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "409",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "423",
		grucha_direction = "E",
		source = "STODOLA PO CIEMKU",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "320",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "560",
		grucha_direction = "E",
		source = "TOALETA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "445",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "565",
		grucha_direction = "E",
		source = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "70",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "570",
		grucha_direction = "E",
		source = "CMENTARZ",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "80",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "510",
		grucha_direction = "E",
		source = "STARSZA CZESC CMENTARZA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "100",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "580",
		grucha_direction = "E",
		source = "LAKA",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "220",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "580",
		grucha_direction = "E",
		source = "DOM Z POKOJEM NA PIETRZE",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "265",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "527",
		grucha_direction = "E",
		source = "LESNA DROGA Z WOJSKOWYM JEEPEM",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "330",
		fred_direction = "E",
		grucha_x = "0",
		fred_y = "590",
		grucha_direction = "E",
		source = "LESNA DROGA Z WOJSKOWYM JEEPEM",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "54",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "560",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "LESNA DROGA Z WOJSKOWYM JEEPEM",
	},
	{
		fred_x = "66",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "307",
		grucha_direction = "E",
		source = "STODOLA",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "382",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "440",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "STODOLA",
	},
	{
		fred_x = "66",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "307",
		grucha_direction = "E",
		source = "STODOLA PO CIEMKU",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "382",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "440",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "STODOLA PO CIEMKU",
	},
	{
		fred_x = "572",
		fred_direction = "B",
		grucha_x = "0",
		fred_y = "161",
		grucha_direction = "E",
		source = "DOM LEKARZA",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "116",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "575",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "DOM LEKARZA",
	},
	{
		fred_x = "40",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "400",
		grucha_direction = "E",
		source = "DOM KOWALA",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "738",
		fred_direction = "G",
		grucha_x = "0",
		fred_y = "581",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "DOM KOWALA",
	},
	{
		fred_x = "679",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "234",
		grucha_direction = "E",
		source = "STACJA BENZYNOWA",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "214",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "545",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "STACJA BENZYNOWA",
	},
	{
		fred_x = "684",
		fred_direction = "G",
		grucha_x = "0",
		fred_y = "485",
		grucha_direction = "E",
		source = "CMENTARZ",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "59",
		fred_direction = "E",
		grucha_x = "0",
		fred_y = "573",
		grucha_direction = "E",
		source = "SKRZYZOWANIE",
		grucha_y = "0",
		dest = "CMENTARZ",
	},
	{
		fred_x = "465",
		fred_direction = "E",
		grucha_x = "0",
		fred_y = "574",
		grucha_direction = "E",
		source = "LAKA",
		grucha_y = "0",
		dest = "SKRZYZOWANIE",
	},
	{
		fred_x = "257",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "573",
		grucha_direction = "E",
		source = "OBOZ HIPPISOW",
		grucha_y = "0",
		dest = "LESNA DROGA Z WOJSKOWYM JEEPEM",
	},
	{
		fred_x = "1470",
		fred_direction = "F",
		grucha_x = "0",
		fred_y = "590",
		grucha_direction = "E",
		source = "LESNA DROGA Z WOJSKOWYM JEEPEM",
		grucha_y = "0",
		dest = "OBOZ HIPPISOW",
	},
	{
		fred_x = "1570",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "590",
		grucha_direction = "E",
		source = "DOM KOWALA",
		grucha_y = "0",
		dest = "OBOZ HIPPISOW",
	},
	{
		fred_x = "61",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "553",
		grucha_direction = "E",
		source = "DOM Z POKOJEM NA PIETRZE",
		grucha_y = "0",
		dest = "DOM KOWALA",
	},
	{
		fred_x = "184",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "580",
		grucha_direction = "E",
		source = "DOM KOWALA",
		grucha_y = "0",
		dest = "DOM Z POKOJEM NA PIETRZE",
	},
	{
		fred_x = "628",
		fred_direction = "G",
		grucha_x = "0",
		fred_y = "478",
		grucha_direction = "E",
		source = "OGROD ZA DOMEM LEKARZA",
		grucha_y = "0",
		dest = "DOM LEKARZA",
	},
	{
		fred_x = "253",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "577",
		grucha_direction = "E",
		source = "DOM LEKARZA",
		grucha_y = "0",
		dest = "OGROD ZA DOMEM LEKARZA",
	},
	{
		fred_x = "446",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "408",
		grucha_direction = "E",
		source = "TOALETA ZWYKLA",
		grucha_y = "0",
		dest = "STACJA BENZYNOWA",
	},
	{
		fred_x = "266",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "535",
		grucha_direction = "E",
		source = "STACJA BENZYNOWA",
		grucha_y = "0",
		dest = "TOALETA",
	},
	{
		fred_x = "266",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "535",
		grucha_direction = "E",
		source = "STACJA BENZYNOWA",
		grucha_y = "0",
		dest = "TOALETA ZWYKLA",
	},
	{
		fred_x = "40",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "458",
		grucha_direction = "E",
		source = "TOALETA",
		grucha_y = "0",
		dest = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM",
	},
	{
		fred_x = "59",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "573",
		grucha_direction = "E",
		source = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM",
		grucha_y = "0",
		dest = "CMENTARZ",
	},
	{
		fred_x = "70",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "480",
		grucha_direction = "E",
		source = "CMENTARZ",
		grucha_y = "0",
		dest = "STARSZA CZESC CMENTARZA",
	},
	{
		fred_x = "534",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "360",
		grucha_direction = "E",
		source = "STARSZA CZESC CMENTARZA",
		grucha_y = "0",
		dest = "CMENTARZ",
	},
	{
		fred_x = "56",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "571",
		grucha_direction = "E",
		source = "STARSZA CZESC CMENTARZA",
		grucha_y = "0",
		dest = "LAKA",
	},
	{
		fred_x = "348",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "425",
		grucha_direction = "E",
		source = "POLANA Z GROBEM",
		grucha_y = "0",
		dest = "NULL",
	},
	{
		fred_x = "3200",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "3200",
		grucha_direction = "E",
		source = "POLANA Z GROBEM",
		grucha_y = "0",
		dest = "NIEBO",
	},
	{
		fred_x = "3701",
		fred_direction = "",
		grucha_x = "0",
		fred_y = "3476",
		grucha_direction = "",
		source = "NIEBO",
		grucha_y = "0",
		dest = "PIEKLO",
	},
	{
		fred_x = "4000",
		fred_direction = "A",
		grucha_x = "4000",
		fred_y = "4000",
		grucha_direction = "E",
		source = "WNETRZE SAMOCHODU",
		grucha_y = "4000",
		dest = "PARKING STRZEZONY",
	},
	{
		fred_x = "774",
		fred_direction = "A",
		grucha_x = "700",
		fred_y = "391",
		grucha_direction = "A",
		source = "WNETRZE SAMOCHODU1",
		grucha_y = "410",
		dest = "PARKING STRZEZONY",
	},
	{
		fred_x = "4000",
		fred_direction = "",
		grucha_x = "4000",
		fred_y = "4000",
		grucha_direction = "E",
		source = "PARKING STRZEZONY",
		grucha_y = "4000",
		dest = "WNETRZE SAMOCHODU1",
	},
	{
		fred_x = "3701",
		fred_direction = "",
		grucha_x = "",
		fred_y = "3476",
		grucha_direction = "",
		source = "PIEKLO",
		grucha_y = "",
		dest = "NULL",
	},
	{
		fred_x = "350",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "375",
		grucha_direction = "E",
		source = "PIEKLO",
		grucha_y = "0",
		dest = "POLANA Z GROBEM",
	},
	{
		fred_x = "1444",
		fred_direction = "F",
		grucha_x = "0",
		fred_y = "546",
		grucha_direction = "E",
		source = "POLANA Z GROBEM",
		grucha_y = "0",
		dest = "DROGA NA SKRAJU LASU",
	},
	{
		fred_x = "110",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "355",
		grucha_direction = "E",
		source = "DROGA NA SKRAJU LASU",
		grucha_y = "0",
		dest = "POLANA Z GROBEM",
	},
	{
		fred_x = "720",
		fred_direction = "H",
		grucha_x = "0",
		fred_y = "330",
		grucha_direction = "E",
		source = "DROGA Z AUTEM",
		grucha_y = "0",
		dest = "POLANA Z GROBEM",
	},
	{
		fred_x = "80",
		fred_direction = "D",
		grucha_x = "0",
		fred_y = "533",
		grucha_direction = "E",
		source = "POLANA Z GROBEM",
		grucha_y = "0",
		dest = "DROGA Z AUTEM",
	},
	{
		fred_x = "4000",
		fred_direction = "",
		grucha_x = "4000",
		fred_y = "4000",
		grucha_direction = "E",
		source = "DROGA Z AUTEM",
		grucha_y = "4000",
		dest = "WNETRZE SAMOCHODU",
	},
	{
		fred_x = "760",
		fred_direction = "",
		grucha_x = "790",
		fred_y = "380",
		grucha_direction = "E",
		source = "WNETRZE SAMOCHODU",
		grucha_y = "380",
		dest = "Null",
	},
	{
		fred_x = "80",
		fred_direction = "",
		grucha_x = "",
		fred_y = "533",
		grucha_direction = "",
		source = "DROGA Z AUTEM",
		grucha_y = "",
		dest = "Null",
	},
	{
		fred_x = "345",
		fred_direction = "A",
		grucha_x = "0",
		fred_y = "381",
		grucha_direction = "E",
		source = "WNETRZE SAMOCHODU",
		grucha_y = "0",
		dest = "DROGA Z AUTEM",
	},
	{
		fred_x = "1095",
		fred_direction = "A",
		grucha_x = "885",
		fred_y = "448",
		grucha_direction = "A",
		source = "WNETRZE SAMOCHODU",
		grucha_y = "400",
		dest = "BRAMA PRZY RAKOWIECKIEJ",
	},
	{
		fred_x = "735",
		fred_direction = "A",
		grucha_x = "827",
		fred_y = "505",
		grucha_direction = "A",
		source = "RAKOWIECKA",
		grucha_y = "507",
		dest = "Null",
	},
	{
		fred_x = "884",
		fred_direction = "G",
		grucha_x = "962",
		fred_y = "498",
		grucha_direction = "G",
		source = "PARKING STRZEZONY",
		grucha_y = "551",
		dest = "RAKOWIECKA",
	},
	{
		fred_x = "93",
		fred_direction = "C",
		grucha_x = "52",
		fred_y = "576",
		grucha_direction = "C",
		source = "RAKOWIECKA",
		grucha_y = "529",
		dest = "PARKING STRZEZONY",
	},
	{
		fred_x = "513",
		fred_direction = "A",
		grucha_x = "602",
		fred_y = "560",
		grucha_direction = "A",
		source = "BIBLIOTEKA",
		grucha_y = "553",
		dest = "Null",
	},
	{
		fred_x = "983",
		fred_direction = "A",
		grucha_x = "1082",
		fred_y = "475",
		grucha_direction = "A",
		source = "BLOKADA NA DRODZE",
		grucha_y = "475",
		dest = "Null",
	},
	{
		fred_x = "446",
		fred_direction = "A",
		grucha_x = "540",
		fred_y = "594",
		grucha_direction = "A",
		source = "DOM Z BIALYCH DESEK",
		grucha_y = "586",
		dest = "Null",
	},
	{
		fred_x = "507",
		fred_direction = "A",
		grucha_x = "615",
		fred_y = "560",
		grucha_direction = "A",
		source = "KAPLICZKA ZA MIASTEM",
		grucha_y = "553",
		dest = "Null",
	},
	{
		fred_x = "321",
		fred_direction = "A",
		grucha_x = "395",
		fred_y = "462",
		grucha_direction = "A",
		source = "KORYTARZ KLASZTORNY",
		grucha_y = "450",
		dest = "Null",
	},
	{
		fred_x = "356",
		fred_direction = "",
		grucha_x = "382",
		fred_y = "588",
		grucha_direction = "",
		source = "KRYPTA",
		grucha_y = "568",
		dest = "Null",
	},
	{
		fred_x = "544",
		fred_direction = "A",
		grucha_x = "630",
		fred_y = "455",
		grucha_direction = "A",
		source = "MUSZLA KONCERTOWA",
		grucha_y = "444",
		dest = "Null",
	},
	{
		fred_x = "388",
		fred_direction = "A",
		grucha_x = "487",
		fred_y = "574",
		grucha_direction = "A",
		source = "PARKING PRZY ROZGLOSNI RADIOWEJ",
		grucha_y = "573",
		dest = "Null",
	},
	{
		fred_x = "300",
		fred_direction = "A",
		grucha_x = "388",
		fred_y = "563",
		grucha_direction = "A",
		source = "PLAC PRZED ZAJAZDEM",
		grucha_y = "555",
		dest = "Null",
	},
	{
		fred_x = "443",
		fred_direction = "A",
		grucha_x = "355",
		fred_y = "519",
		grucha_direction = "A",
		source = "PODJAZD POD KLASZTOREM",
		grucha_y = "524",
		dest = "Null",
	},
	{
		fred_x = "456",
		fred_direction = "A",
		grucha_x = "374",
		fred_y = "496",
		grucha_direction = "A",
		source = "PODWORZE ZA TYMZE DOMEM",
		grucha_y = "509",
		dest = "Null",
	},
	{
		fred_x = "272",
		fred_direction = "A",
		grucha_x = "395",
		fred_y = "512",
		grucha_direction = "A",
		source = "POKOJ NA PIETRZE ZAJAZDU",
		grucha_y = "486",
		dest = "Null",
	},
	{
		fred_x = "681",
		fred_direction = "A",
		grucha_x = "599",
		fred_y = "473",
		grucha_direction = "A",
		source = "ROZGLOSNIA RADIOWA",
		grucha_y = "432",
		dest = "Null",
	},
	{
		fred_x = "105",
		fred_direction = "A",
		grucha_x = "200",
		fred_y = "586",
		grucha_direction = "A",
		source = "ZAJAZD",
		grucha_y = "589",
		dest = "Null",
	},
	{
		fred_x = "560",
		fred_direction = "A",
		grucha_x = "643",
		fred_y = "579",
		grucha_direction = "A",
		source = "ZLOMOWISKO",
		grucha_y = "573",
		dest = "Null",
	},
	{
		fred_x = "83",
		fred_direction = "A",
		grucha_x = "33",
		fred_y = "460",
		grucha_direction = "A",
		source = "MUSZLA KONCERTOWA",
		grucha_y = "458",
		dest = "PLAC PRZED ZAJAZDEM",
	},
	{
		fred_x = "750",
		fred_direction = "H",
		grucha_x = "834",
		fred_y = "462",
		grucha_direction = "H",
		source = "ZAJAZD",
		grucha_y = "472",
		dest = "PLAC PRZED ZAJAZDEM",
	},
	{
		fred_x = "624",
		fred_direction = "C",
		grucha_x = "746",
		fred_y = "577",
		grucha_direction = "C",
		source = "BLOKADA NA DRODZE",
		grucha_y = "574",
		dest = "ZLOMOWISKO",
	},
	{
		fred_x = "24",
		fred_direction = "C",
		grucha_x = "60",
		fred_y = "535",
		grucha_direction = "C",
		source = "PARKING PRZY ROZGLOSNI RADIOWEJ",
		grucha_y = "467",
		dest = "PLAC PRZED ZAJAZDEM",
	},
	{
		fred_x = "102",
		fred_direction = "C",
		grucha_x = "244",
		fred_y = "573",
		grucha_direction = "C",
		source = "BIBLIOTEKA",
		grucha_y = "555",
		dest = "PARKING PRZY ROZGLOSNI RADIOWEJ",
	},
	{
		fred_x = "301",
		fred_direction = "A",
		grucha_x = "325",
		fred_y = "451",
		grucha_direction = "A",
		source = "DOM Z BIALYCH DESEK",
		grucha_y = "475",
		dest = "PLAC PRZED ZAJAZDEM",
	},
	{
		fred_x = "220",
		fred_direction = "A",
		grucha_x = "124",
		fred_y = "490",
		grucha_direction = "A",
		source = "ROZGLOSNIA RADIOWA",
		grucha_y = "494",
		dest = "PARKING PRZY ROZGLOSNI RADIOWEJ",
	},
	{
		fred_x = "853",
		fred_direction = "G",
		grucha_x = "918",
		fred_y = "578",
		grucha_direction = "G",
		source = "PLAC PRZED ZAJAZDEM",
		grucha_y = "491",
		dest = "PARKING PRZY ROZGLOSNI RADIOWEJ",
	},
	{
		fred_x = "681",
		fred_direction = "G",
		grucha_x = "599",
		fred_y = "473",
		grucha_direction = "G",
		source = "PARKING PRZY ROZGLOSNI RADIOWEJ",
		grucha_y = "432",
		dest = "ROZGLOSNIA RADIOWA",
	},
	{
		fred_x = "105",
		fred_direction = "F",
		grucha_x = "200",
		fred_y = "586",
		grucha_direction = "E",
		source = "PLAC PRZED ZAJAZDEM",
		grucha_y = "589",
		dest = "ZAJAZD",
	},
	{
		fred_x = "222",
		fred_direction = "C",
		grucha_x = "320",
		fred_y = "596",
		grucha_direction = "C",
		source = "PLAC PRZED ZAJAZDEM",
		grucha_y = "597",
		dest = "ZLOMOWISKO",
	},
	{
		fred_x = "297",
		fred_direction = "A",
		grucha_x = "297",
		fred_y = "410",
		grucha_direction = "A",
		source = "KAPLICZKA ZA MIASTEM",
		grucha_y = "380",
		dest = "ZLOMOWISKO",
	},
	{
		fred_x = "302",
		fred_direction = "D",
		grucha_x = "187",
		fred_y = "582",
		grucha_direction = "D",
		source = "DOM Z BIALYCH DESEK",
		grucha_y = "583",
		dest = "PODWORZE ZA TYMZE DOMEM",
	},
	{
		fred_x = "767",
		fred_direction = "H",
		grucha_x = "841",
		fred_y = "401",
		grucha_direction = "G",
		source = "MUSZLA KONCERTOWA",
		grucha_y = "392",
		dest = "PODWORZE ZA TYMZE DOMEM",
	},
	{
		fred_x = "440",
		fred_direction = "E",
		grucha_x = "344",
		fred_y = "540",
		grucha_direction = "E",
		source = "BIBLIOTEKA",
		grucha_y = "540",
		dest = "PODJAZD POD KLASZTOREM",
	},
	{
		fred_x = "355",
		fred_direction = "",
		grucha_x = "443",
		fred_y = "524",
		grucha_direction = "",
		source = "KRYPTA",
		grucha_y = "519",
		dest = "PODJAZD POD KLASZTOREM",
	},
	{
		fred_x = "110",
		fred_direction = "C",
		grucha_x = "58",
		fred_y = "457",
		grucha_direction = "B",
		source = "PODWORZE ZA TYMZE DOMEM",
		grucha_y = "431",
		dest = "MUSZLA KONCERTOWA",
	},
	{
		fred_x = "356",
		fred_direction = "",
		grucha_x = "382",
		fred_y = "588",
		grucha_direction = "",
		source = "KORYTARZ KLASZTORNY",
		grucha_y = "568",
		dest = "KRYPTA",
	},
	{
		fred_x = "326",
		fred_direction = "A",
		grucha_x = "379",
		fred_y = "410",
		grucha_direction = "A",
		source = "PODJAZD POD KLASZTOREM",
		grucha_y = "405",
		dest = "KORYTARZ KLASZTORNY",
	},
	{
		fred_x = "588",
		fred_direction = "E",
		grucha_x = "682",
		fred_y = "588",
		grucha_direction = "E",
		source = "ZLOMOWISKO",
		grucha_y = "545",
		dest = "KAPLICZKA ZA MIASTEM",
	},
	{
		fred_x = "195",
		fred_direction = "C",
		grucha_x = "98",
		fred_y = "590",
		grucha_direction = "C",
		source = "PLAC PRZED ZAJAZDEM",
		grucha_y = "593",
		dest = "DOM Z BIALYCH DESEK",
	},
	{
		fred_x = "646",
		fred_direction = "A",
		grucha_x = "781",
		fred_y = "530",
		grucha_direction = "H",
		source = "PODWORZE ZA TYMZE DOMEM",
		grucha_y = "517",
		dest = "DOM Z BIALYCH DESEK",
	},
	{
		fred_x = "840",
		fred_direction = "G",
		grucha_x = "900",
		fred_y = "576",
		grucha_direction = "G",
		source = "ZLOMOWISKO",
		grucha_y = "528",
		dest = "PLAC PRZED ZAJAZDEM",
	},
	{
		fred_x = "560",
		fred_direction = "A",
		grucha_x = "622",
		fred_y = "344",
		grucha_direction = "A",
		source = "PODJAZD POD KLASZTOREM",
		grucha_y = "350",
		dest = "BIBLIOTEKA",
	},
	{
		fred_x = "178",
		fred_direction = "C",
		grucha_x = "66",
		fred_y = "582",
		grucha_direction = "C",
		source = "PARKING PRZY ROZGLOSNI RADIOWEJ",
		grucha_y = "564",
		dest = "BIBLIOTEKA",
	},
	{
		fred_x = "272",
		fred_direction = "A",
		grucha_x = "395",
		fred_y = "512",
		grucha_direction = "A",
		source = "ZAJAZD",
		grucha_y = "486",
		dest = "POKOJ NA PIETRZE ZAJAZDU",
	},
	{
		fred_x = "",
		fred_direction = "",
		grucha_x = "",
		fred_y = "",
		grucha_direction = "",
		source = "ROZGLOSNIA RADIOWA",
		grucha_y = "",
		dest = "POKOJ NA PIETRZE ZAJAZDU",
	},
	{
		fred_x = "-20",
		fred_direction = "",
		grucha_x = "-20",
		fred_y = "-20",
		grucha_direction = "",
		source = "KOMIKS2",
		grucha_y = "-20",
		dest = "Null",
	},
	{
		fred_x = "388",
		fred_direction = "A",
		grucha_x = "487",
		fred_y = "574",
		grucha_direction = "A",
		source = "KOMIKS2",
		grucha_y = "573",
		dest = "PARKING PRZY ROZGLOSNI RADIOWEJ",
	},
	{
		fred_x = "541",
		fred_direction = "A",
		grucha_x = "636",
		fred_y = "401",
		grucha_direction = "A",
		source = "KORYTARZ KLASZTORNY",
		grucha_y = "322",
		dest = "KAPLICZKA ZA MIASTEM",
	},
	{
		fred_x = "467",
		fred_direction = "A",
		grucha_x = "355",
		fred_y = "519",
		grucha_direction = "A",
		source = "ZAJAZD",
		grucha_y = "524",
		dest = "PODJAZD POD KLASZTOREM",
	},
	{
		fred_x = "-20",
		fred_direction = "",
		grucha_x = "-40",
		fred_y = "-20",
		grucha_direction = "",
		source = "PODJAZD POD KLASZTOREM",
		grucha_y = "-40",
		dest = "AKCJA W KLASZTORZE",
	},
	{
		fred_x = "326",
		fred_direction = "",
		grucha_x = "395",
		fred_y = "462",
		grucha_direction = "",
		source = "AKCJA W KLASZTORZE",
		grucha_y = "450",
		dest = "KORYTARZ KLASZTORNY",
	},
	{
		fred_x = "40",
		fred_direction = "C",
		grucha_x = "0",
		fred_y = "458",
		grucha_direction = "E",
		source = "TOALETA ZWYKLA",
		grucha_y = "0",
		dest = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM",
	},
	{
		fred_x = "565",
		fred_direction = "D",
		grucha_x = "700",
		fred_y = "580",
		grucha_direction = "E",
		source = "KAPLICZKA ZA MIASTEM",
		grucha_y = "570",
		dest = "PLAC PRZED ZAJAZDEM",
	},
	{
		fred_x = "319",
		fred_direction = "A",
		grucha_x = "550",
		fred_y = "330",
		grucha_direction = "A",
		source = "KAPLICZKA ZA MIASTEM",
		grucha_y = "330",
		dest = "KONIEC",
	},
	{
		fred_x = "467",
		fred_direction = "A",
		grucha_x = "355",
		fred_y = "519",
		grucha_direction = "A",
		source = "KORYTARZ KLASZTORNY",
		grucha_y = "524",
		dest = "PODJAZD POD KLASZTOREM",
	},
	{
		fred_x = "1380",
		fred_direction = "C",
		grucha_x = "1320",
		fred_y = "530",
		grucha_direction = "C",
		source = "ZLOMOWISKO",
		grucha_y = "520",
		dest = "BLOKADA NA DRODZE",
	},
}