return {
    { type = "Sfx", name = "Pojawia_sie_FZB", id = "SFX_1" },
    { type = "Sfx", name = "Pogłos", id = "SFX_2" },
    { type = "Sfx", name = "Rozmywanie", id = "SFX_3" },
    { type = "Sfx", name = "Pomruk silnika Szatańskiej Fury", id = "SFX_4" },
    { type = "Sfx", name = "Odgłosy uderzania ręką w dach samochodu", id = "SFX_5" },
    { type = "Sfx", name = "Brzęknięcie elektrycznego zamka", id = "SFX_6" },
    { type = "Sfx", name = "Wycie silnika Szatańskiej Fury", id = "SFX_7" },
    { type = "Sfx", name = "Gromy and pioruny", id = "SFX_8" },
    { type = "Sfx", name = "Plaskacz w twarz", id = "SFX_9" },
    { type = "Sfx", name = "Cios w zęby", id = "SFX_10" },
    { type = "Sfx", name = "Kolba w głowę", id = "SFX_11" },
    { type = "Sfx", name = "Skrzypienie zawiasów", id = "SFX_12" },
    { type = "Sfx", name = "Tłusty podkład hiphopowy", id = "SFX_13" },
    { type = "Sfx", name = "Imprezowy podkład hiphopowy", id = "SFX_14" },
    { type = "Sfx", name = "Odgłosy gry w &quot;Tońka&quot;", id = "SFX_15" },
    { type = "Sfx", name = "Ogłoszenie_zwycięzcy_raz", id = "SFX_16" },
    { type = "Sfx", name = "Ogłoszenie_zwycięzcy_dwa", id = "SFX_17" },
    { type = "Sfx", name = "Dogorywanie_Chrząstka", id = "SFX_18" },
    { type = "Sfx", name = "Porażnie_Chrząstka", id = "SFX_19" },
    { type = "Sfx", name = "Syreny_policyjne", id = "SFX_20" },
    { type = "Sfx", name = "Walenie_w_drzwi", id = "SFX_21" },
    { type = "Sfx", name = "Wezwanie_policyjne", id = "SFX_22" },
    { type = "Sfx", name = "Wezwanie_policyjne_2", id = "SFX_23" },
    { type = "Sfx", name = "Bulgotanie_oleju", id = "SFX_24" },
    { type = "Sfx", name = "Uderzenie_o_chodnik", id = "SFX_25" },
    { type = "Sfx", name = "Podkład_na_harfie", id = "SFX_26" },
    { type = "Sfx", name = "Odgłosy_jedzenia", id = "SFX_27" },
    { type = "Sfx", name = "Skrobanie_pióra_o_papier", id = "SFX_28" },
    { type = "Sfx", name = "Temat_z_&quot;Psychozy&quot;", id = "SFX_29" },
    { type = "Sfx", name = "Stukot_Łomoty_Skrzypienie", id = "SFX_30" },
    { type = "Sfx", name = "Brzęczenie_dzwonka", id = "SFX_31" },
    { type = "Sfx", name = "Chaos_i_hałas", id = "SFX_32" },
    { type = "Sfx", name = "Skrzypienie furtki", id = "SFX_33" },
    { type = "Sfx", name = "Krzaków_szelest", id = "SFX_34" },
    { type = "Sfx", name = "Przełykanie", id = "SFX_35" },
    { type = "Sfx", name = "Pomruk silnika Bandytowozu", id = "SFX_36" },
    { type = "Sfx", name = "Szczęk_drzwi", id = "SFX_37" },
    { type = "Sfx", name = "Szarpanie_klamki", id = "SFX_38" },
    { type = "Sfx", name = "Łomotanie_w_drzwi", id = "SFX_39" },
    { type = "Sfx", name = "Upadek_na_ziemię", id = "SFX_40" },
    { type = "Sfx", name = "Nóż_uderzający_w_karoserię", id = "SFX_41" },
    { type = "Sfx", name = "Maszyna_zgrzyta", id = "SFX_42" },
    { type = "Sfx", name = "Furtka_skrzypi", id = "SFX_43" },
    { type = "Sfx", name = "Szczekanie_psa", id = "SFX_44" },
    { type = "Sfx", name = "Kaczy_chód_Posłańca", id = "SFX_45" },
    { type = "Sfx", name = "Wyładowania_elektryczne", id = "SFX_46" },
    { type = "Sfx", name = "Perkusja_z_Las_Vegas", id = "SFX_47" },
    { type = "Sfx", name = "Włączenie_telewizora", id = "SFX_48" },
    { type = "Sfx", name = "Wyłączenie_telewizora", id = "SFX_49" },
    { type = "Sfx", name = "Niebiańskie_trąby", id = "SFX_50" },
    { type = "Sfx", name = "Niebiańskie_chóry", id = "SFX_51" },
    { type = "Sfx", name = "Piekielne_wycia_i_diably", id = "SFX_52" },
    { type = "Sfx", name = "Krzyki_potępionych", id = "SFX_53" },
    { type = "Sfx", name = "Odpezpieczna_giwera", id = "SFX_54" },
    { type = "Sfx", name = "Trzask_drzwi_fury", id = "SFX_55" },
    { type = "Sfx", name = "Chlupanie_swieconej_wody", id = "SFX_56" },
    { type = "Sfx", name = "telefon1", id = "SFX_57" },
    { type = "Sfx", name = "telefon2", id = "SFX_58" },
    { type = "Sfx", name = "Golenie", id = "SFX_59" },
    { type = "Sfx", name = "Huczenie_ognia", id = "SFX_60" },
    { type = "Sfx", name = "Bulgotanie_wrzacej_smoly", id = "SFX_61" },
    { type = "Sfx", name = "Spiecie_elektryczne", id = "SFX_62" },
    { type = "Sfx", name = "Syczenie_pary", id = "SFX_63" },
    { type = "Sfx", name = "Szczekanie_psów_obronnych", id = "SFX_64" },
    { type = "Sfx", name = "Jedzenie_miesa_przez_psy_obronne", id = "SFX_65" },
    { type = "Sfx", name = "Chlapniecie_miesa_o_ziemie_na_zlomowisku", id = "SFX_66" },
    { type = "Sfx", name = "Skomlenie_psow_obronnych", id = "SFX_67" },
    { type = "Sfx", name = "Plonace_ognisko", id = "SFX_68" },
    { type = "Sfx", name = "Zgrzyt_plyty_winylowej", id = "SFX_69" },
    { type = "Sfx", name = "Brzeczenie_much", id = "SFX_70" },
    { type = "Sfx", name = "Zwolnienie_blokady_samochodowej", id = "SFX_71" },
    { type = "Sfx", name = "Dramatyczna_walka", id = "SFX_72" },
    { type = "Sfx", name = "Odległy_halas_bandytowozu", id = "SFX_73" },
    { type = "Sfx", name = "Zajadle_hamowanie", id = "SFX_74" },
    { type = "Sfx", name = "Trzaskanie_drzwi", id = "SFX_75" },
    { type = "Sfx", name = "Brzeczenie_elektrycznego_magnesu", id = "SFX_76" },
    { type = "Sfx", name = "Pojedyncze_brzekniecie_magnesu_o_blache", id = "SFX_77" },
    { type = "Sfx", name = "Pojedyncze_dzwiekniecie_magnesu_o_blache", id = "SFX_78" },
    { type = "Sfx", name = "wykrecanie_numeru", id = "SFX_79" },
    { type = "Sfx", name = "wertowanie_kartek", id = "SFX_80" },
    { type = "Sfx", name = "szum_wody_lecacej_z_kranu", id = "SFX_81" },
    { type = "Sfx", name = "pracujacy_dzwig", id = "SFX_82" },
    { type = "Sfx", name = "otwarcie_tajnego_przejscia", id = "SFX_83" },
    { type = "Sfx", name = "wystrzal_z_kapiszonowca", id = "SFX_84" },
    { type = "Sfx", name = "otwarcie_kufra", id = "SFX_85" },
    { type = "Sfx", name = "Blask_Harasyma", id = "SFX_86" },
    { type = "Sfx", name = "Przemiana_Harasyma", id = "SFX_87" },
    { type = "Sfx", name = "Przemiana_FZB", id = "SFX_88" },
    { type = "Sfx", name = "Syczenie_gaszonego_ognia", id = "SFX_89" },
    { type = "Sfx", name = "Syczenie_gaśnicy", id = "SFX_90" },
    { type = "Sfx", name = "Chlupanie_wody", id = "SFX_91" },
    { type = "Sfx", name = "Aldona_wspina_sie", id = "SFX_92" },
    { type = "Sfx", name = "Zgrzytanie_zamka_klasztoru", id = "SFX_93" },
    { type = "Sfx", name = "Klikniecie", id = "SFX_94" },
    { type = "Sfx", name = "Nieudane_odpalanie_motoru", id = "SFX_95" },
    { type = "Sfx", name = "Udane_odpalenie_motoru.", id = "SFX_96" },
    { type = "Sfx", name = "Odpezpieczna_giwera", id = "SFX_97" },
    { type = "Sfx", name = "Trzask_drzwi_fury", id = "SFX_98" },
    { type = "Sfx", name = "Strzał_z_pistoletu", id = "SFX_99" },
    { type = "Sfx", name = "Odgłosy_walki", id = "SFX_100" },
    { type = "Sfx", name = "Szuranie_szuflady", id = "SFX_101" },
    { type = "Sfx", name = "Podswietlenie_przycisku", id = "SFX_102" },
    { type = "Sfx", name = "Klikniecie_na_przycisk", id = "SFX_103" },
    { type = "Sfx", name = "Klikniecie_na_checkbox", id = "SFX_104" },
    { type = "Sfx", name = "Przesuwanie_suwaka", id = "SFX_105" },
    { type = "Sfx", name = "Otwarcie_bagaznika", id = "SFX_106" },
    { type = "Sfx", name = "Zamkniecie_bagaznika", id = "SFX_107" },
    { type = "Sfx", name = "Zamykanie_drzwi_rakowieckiej", id = "SFX_108" },
    { type = "Sfx", name = "Atak_Jorge", id = "SFX_109" },
    { type = "Sfx", name = "Wydobycie_gumy_z_monety", id = "SFX_110" },
    { type = "Sfx", name = "Patroszenie_ryby_nozem", id = "SFX_111" },
    { type = "Sfx", name = "Zakręcanie_słoika", id = "SFX_112" },
    { type = "Sfx", name = "Nalewanie_mleka_do_spodka", id = "SFX_113" },
    { type = "Sfx", name = "Krojenie_jablka", id = "SFX_114" },
    { type = "Sfx", name = "Upadajaca_igla", id = "SFX_115" },
    { type = "Sfx", name = "Zlozenie_golarki", id = "SFX_116" },
    { type = "Sfx", name = "fred_wpada_do_grobu", id = "SFX_117" },
    { type = "Sfx", name = "fred_mowi_o_ksiazce_tel", id = "SFX_118" },
    { type = "Sfx", name = "nowa_lokacja", id = "SFX_119" },
    { type = "Sfx", name = "nowy_przedmiot", id = "SFX_120" },
}