return {
    { type = "Trigger", name = "1 Przybycie na parking", state = "False", id = "1" },
    { type = "Trigger", name = "Rozmowa ze strozem po sprowadzeniu wnuka", state = "False", id = "2" },
    { type = "Trigger", name = "Rozmowa z ziomem 2 po opatrzeniu FLOWERA", state = "False", id = "3" },
    { type = "Trigger", name = "Wypadek Flowera", state = "False", id = "4" },
    { type = "Trigger", name = "Zabranie wody utlenionej", state = "False", id = "5" },
    { type = "Trigger", name = "Zabranie  bandaza", state = "False", id = "6" },
    { type = "Trigger", name = "Zabranie oleju", state = "False", id = "7" },
    { type = "Trigger", name = "Wylanie oleju na rampe", state = "False", id = "8" },
    { type = "Trigger", name = "Otwarcie kosza na parkingu", state = "False", id = "9" },
    { type = "Trigger", name = "Nakarmienie psa", state = "False", id = "10" },
    { type = "Trigger", name = "Przestraszenie dilera", state = "False", id = "11" },
    { type = "Trigger", name = "Zlecenie od struza", state = "False", id = "12" },
    { type = "Trigger", name = "Odstawienie fury", state = "False", id = "13" },
    { type = "Trigger", name = "Zlecenie od FZB przy kosciele", state = "False", id = "14" },
    { type = "Trigger", name = "Gadka z ochroniarzem przed szokola(piąta)", state = "False", id = "15" },
    { type = "Trigger", name = "Gadka z Nukem po wygranej(otrzymanie telefonu do dilera)", state = "False", id = "16" },
    { type = "Trigger", name = "Nauka gry w Tonka", state = "False", id = "17" },
    { type = "Trigger", name = "Przesluchanie plyt u winyla", state = "False", id = "18" },
    { type = "Trigger", name = "Rozmowa z licealistami przed nauką gry w Tonka", state = "False", id = "19" },
    { type = "Trigger", name = "Wyjęcie monety z gumy", state = "False", id = "20" },
    { type = "Trigger", name = "Otrzymanie dresu", state = "False", id = "21" },
    { type = "Trigger", name = "Zlożenie maszynki do golenia", state = "False", id = "22" },
    { type = "Trigger", name = "odlepienie gumy", state = "False", id = "23" },
    { type = "Trigger", name = "Przyjżenie sie automatowi 4", state = "False", id = "24" },
    { type = "Trigger", name = "Gadka z elektronikiem po nauce tonka", state = "False", id = "25" },
    { type = "Trigger", name = "Wyjęcie silnika od golarki ze smietnika", state = "False", id = "26" },
    { type = "Trigger", name = "Otwarcie apteczki", state = "False", id = "27" },
    { type = "Trigger", name = "Gadka z tekstylia po nauce w tonka", state = "False", id = "28" },
    { type = "Trigger", name = "Telefon do dilera", state = "False", id = "29" },
    { type = "Trigger", name = "Wejcie na teren boiska i sklepanie dilera", state = "False", id = "30" },
    { type = "Trigger", name = "Ogolenie gruchy", state = "False", id = "31" },
    { type = "Trigger", name = "Rozpoczęcie golenia", state = "False", id = "32" },
    { type = "Trigger", name = "Oddanie linki chrząstkowi", state = "False", id = "33" },
    { type = "Trigger", name = "Zabranie linki ze sklepu Winyla", state = "False", id = "34" },
    { type = "Trigger", name = "druga gadka dilerem na boisku", state = "False", id = "35" },
    { type = "Trigger", name = "Przyjrzenie się szafie w kryjowce gangsterow", state = "False", id = "36" },
    { type = "Trigger", name = "Opatrzenie Flowera", state = "False", id = "37" },
    { type = "Trigger", name = "Pukanie w szybę bandytowozu", state = "False", id = "38" },
    { type = "Trigger", name = "Włączenie telewizora", state = "False", id = "39" },
    { type = "Trigger", name = "Lopata", state = "False", id = "40" },
    { type = "Trigger", name = "Patyk", state = "False", id = "41" },
    { type = "Trigger", name = "Kluczyki_od_samochodu", state = "False", id = "42" },
    { type = "Trigger", name = "Silnik_od_golarki_elektrycznej", state = "False", id = "43" },
    { type = "Trigger", name = "Puszka_oleju_silnikowego", state = "False", id = "44" },
    { type = "Trigger", name = "Woda_utleniona", state = "False", id = "45" },
    { type = "Trigger", name = "Bandaz", state = "False", id = "46" },
    { type = "Trigger", name = "Hot-Dog", state = "False", id = "47" },
    { type = "Trigger", name = "Stalowa_linka", state = "False", id = "48" },
    { type = "Trigger", name = "Guma_przylepiona_u_podstawy_aparatu_telefonicznego_nr_4", state = "False", id = "49" },
    { type = "Trigger", name = "Moneta_wyjęta_z_gumy_do_zucia", state = "False", id = "50" },
    { type = "Trigger", name = "Bateria", state = "False", id = "51" },
    { type = "Trigger", name = "Kadlub_golarki_elektrycznej", state = "False", id = "52" },
    { type = "Trigger", name = "Kartka z numerem tel. Dilera", state = "False", id = "53" },
    { type = "Trigger", name = "Dresik", state = "False", id = "54" },
    { type = "Trigger", name = "Maska_plemienna", state = "False", id = "55" },
    { type = "Trigger", name = "Jablko", state = "False", id = "56" },
    { type = "Trigger", name = "Lom", state = "False", id = "57" },
    { type = "Trigger", name = "Sloik", state = "False", id = "58" },
    { type = "Trigger", name = "Wieczko", state = "False", id = "59" },
    { type = "Trigger", name = "Podziurawione_wieczko", state = "False", id = "60" },
    { type = "Trigger", name = "Sloik_z_podziurawionym_wieczkiem", state = "False", id = "61" },
    { type = "Trigger", name = "Zakrecony_sloik", state = "False", id = "62" },
    { type = "Trigger", name = "Srodki_nasenne", state = "False", id = "63" },
    { type = "Trigger", name = "Noz", state = "False", id = "64" },
    { type = "Trigger", name = "Drabina", state = "False", id = "65" },
    { type = "Trigger", name = "Promocyjna_kawa", state = "False", id = "66" },
    { type = "Trigger", name = "Spinka_do_wlosow", state = "False", id = "67" },
    { type = "Trigger", name = "Latarka", state = "False", id = "68" },
    { type = "Trigger", name = "Ryba", state = "False", id = "69" },
    { type = "Trigger", name = "Zloty_pierscionek", state = "False", id = "70" },
    { type = "Trigger", name = "Swietliki", state = "False", id = "71" },
    { type = "Trigger", name = "Ksiazka_telefoniczna", state = "False", id = "72" },
    { type = "Trigger", name = "Porcja_Miesa", state = "False", id = "73" },
    { type = "Trigger", name = "Zatrtute_Mieso", state = "False", id = "74" },
    { type = "Trigger", name = "Karta_kredytowa", state = "False", id = "75" },
    { type = "Trigger", name = "Butelka_mleka", state = "False", id = "76" },
    { type = "Trigger", name = "Srubokret_z_ulamana_raczka", state = "False", id = "77" },
    { type = "Trigger", name = "Prawie_Dobre_Gumiaki", state = "False", id = "78" },
    { type = "Trigger", name = "Kilkadziesiat_Metrow_Liny", state = "False", id = "79" },
    { type = "Trigger", name = "Mapa_Klasztoru", state = "False", id = "80" },
    { type = "Trigger", name = "Ulotki_partyjne", state = "False", id = "81" },
    { type = "Trigger", name = "Tyczka", state = "False", id = "82" },
    { type = "Trigger", name = "Dziwna_Podkowa", state = "False", id = "83" },
    { type = "Trigger", name = "Magnes", state = "False", id = "84" },
    { type = "Trigger", name = "Igla", state = "False", id = "85" },
    { type = "Trigger", name = "Szkatułka_z_Relikwia", state = "False", id = "86" },
    { type = "Trigger", name = "Giwera_Freda", state = "True", id = "87" },
    { type = "Trigger", name = "Plyta_z_Hejnalem_Mariackim", state = "False", id = "88" },
    { type = "Trigger", name = "Karta_biblioteczna", state = "False", id = "89" },
    { type = "Trigger", name = "Plan_Klasztoru", state = "False", id = "90" },
    { type = "Trigger", name = "Maszynka_do_golenia", state = "False", id = "91" },
    { type = "Trigger", name = "PARKING STRZEZONY", state = "True", id = "94" },
    { type = "Trigger", name = "SKEJTPARK 1", state = "False", id = "95" },
    { type = "Trigger", name = "SKEJTPARK 2", state = "False", id = "96" },
    { type = "Trigger", name = "OKOLICE KOSCIOLA", state = "False", id = "97" },
    { type = "Trigger", name = "SZKOLA", state = "False", id = "98" },
    { type = "Trigger", name = "BOISKO SZKOLNE", state = "False", id = "99" },
    { type = "Trigger", name = "SKLEP PLYTOWY", state = "False", id = "100" },
    { type = "Trigger", name = "CENTRUM HANDLOWE", state = "False", id = "101" },
    { type = "Trigger", name = "KAFEJKA INTERNETOWA", state = "False", id = "102" },
    { type = "Trigger", name = "PLAC ZA MIASTEM", state = "False", id = "103" },
    { type = "Trigger", name = "SIEDZIBA MAFII", state = "False", id = "104" },
    { type = "Trigger", name = "PARKING STRZEZONY_visited", state = "False", id = "105" },
    { type = "Trigger", name = "SKEJTPARK 1_visited", state = "False", id = "106" },
    { type = "Trigger", name = "SKEJTPARK 2_visited", state = "False", id = "107" },
    { type = "Trigger", name = "OKOLICE KOSCIOLA_visited", state = "False", id = "108" },
    { type = "Trigger", name = "SZKOLA_visited", state = "False", id = "109" },
    { type = "Trigger", name = "BOISKO SZKOLNE_visited", state = "False", id = "110" },
    { type = "Trigger", name = "SKLEP PLYTOWY_visited", state = "False", id = "111" },
    { type = "Trigger", name = "CENTRUM HANDLOWE_visited", state = "False", id = "112" },
    { type = "Trigger", name = "KAFEJKA INTERNETOWA_visited", state = "False", id = "113" },
    { type = "Trigger", name = "PLAC ZA MIASTEM_visited", state = "False", id = "114" },
    { type = "Trigger", name = "SIEDZIBA MAFII_visited", state = "False", id = "115" },
    { type = "Trigger", name = "PARKING STRZEZONY_inactive", state = "False", id = "116" },
    { type = "Trigger", name = "SKEJTPARK 1_inactive", state = "False", id = "117" },
    { type = "Trigger", name = "SKEJTPARK 2_inactive", state = "False", id = "118" },
    { type = "Trigger", name = "OKOLICE KOSCIOLA_inactive", state = "False", id = "119" },
    { type = "Trigger", name = "SZKOLA_inactive", state = "False", id = "120" },
    { type = "Trigger", name = "BOISKO SZKOLNE_inactive", state = "False", id = "121" },
    { type = "Trigger", name = "SKLEP PLYTOWY_inactive", state = "False", id = "122" },
    { type = "Trigger", name = "CENTRUM HANDLOWE_inactive", state = "False", id = "123" },
    { type = "Trigger", name = "KAFEJKA INTERNETOWA_inactive", state = "False", id = "124" },
    { type = "Trigger", name = "PLAC ZA MIASTEM_inactive", state = "False", id = "125" },
    { type = "Trigger", name = "Tupecik", state = "False", id = "126" },
    { type = "Trigger", name = "Gadka z elektronikiem przed nauka tonka", state = "False", id = "127" },
    { type = "Trigger", name = "Gadka z tekstylia  przed nauka tonka", state = "False", id = "128" },
    { type = "Trigger", name = "Zabranie hot doga", state = "False", id = "129" },
    { type = "Trigger", name = "rozmowa z drugim ziomem po wypadku", state = "False", id = "130" },
    { type = "Trigger", name = "Owoc_krzaka_ozdobnego", state = "False", id = "131" },
    { type = "Trigger", name = "PARKING STRZEZONY_multivisited", state = "False", id = "132" },
    { type = "Trigger", name = "SKEJTPARK 1_multivisited", state = "False", id = "133" },
    { type = "Trigger", name = "SKEJTPARK 2_multivisited", state = "False", id = "134" },
    { type = "Trigger", name = "OKOLICE KOSCIOLA_multivisited", state = "False", id = "135" },
    { type = "Trigger", name = "SZKOLA_multivisited", state = "False", id = "136" },
    { type = "Trigger", name = "BOISKO SZKOLNE_multivisited", state = "False", id = "137" },
    { type = "Trigger", name = "SKLEP PLYTOWY_multivisited", state = "False", id = "138" },
    { type = "Trigger", name = "CENTRUM HANDLOWE_multivisited", state = "False", id = "139" },
    { type = "Trigger", name = "KAFEJKA INTERNETOWA_multivisited", state = "False", id = "140" },
    { type = "Trigger", name = "PLAC ZA MIASTEM_multivisited", state = "False", id = "141" },
    { type = "Trigger", name = "SIEDZIBA MAFII_multivisited", state = "False", id = "142" },
    { type = "Trigger", name = "znikniecie licealistow", state = "False", id = "143" },
    { type = "Trigger", name = "ogranie nuke&apos;a", state = "False", id = "144" },
    { type = "Trigger", name = "Ryba_wypatroszona", state = "False", id = "145" },
    { type = "Trigger", name = "odbyta 1 rozmowa z egzema", state = "False", id = "146" },
    { type = "Trigger", name = "Sztuczne_kwiaty", state = "False", id = "147" },
    { type = "Trigger", name = "Sloik_z_martwymi_swietlikami", state = "False", id = "148" },
    { type = "Trigger", name = "Sloik_z_zywymi_swietlikami", state = "False", id = "149" },
    { type = "Trigger", name = "kowal jest wywolany z domu", state = "False", id = "150" },
    { type = "Trigger", name = "Glejt_bez_podpisow", state = "False", id = "151" },
    { type = "Trigger", name = "Glejt_z_podpisem_lekarza", state = "False", id = "152" },
    { type = "Trigger", name = "Glejt_z_podpisem_grabarza", state = "False", id = "153" },
    { type = "Trigger", name = "Glejt_z_podpisami_lekarza_i_grabarza", state = "False", id = "154" },
    { type = "Trigger", name = "Glejt_z_trzema_podpisami", state = "False", id = "155" },
    { type = "Trigger", name = "fred dowiedział się o problemie sercowym Lekarza", state = "False", id = "156" },
    { type = "Trigger", name = "Fred gadal z Lekarzem o kwiatach", state = "False", id = "157" },
    { type = "Trigger", name = "Pokrojone_jablko", state = "False", id = "158" },
    { type = "Trigger", name = "Otwarcie łomem wrót stodoły", state = "False", id = "159" },
    { type = "Trigger", name = "Pusty_kubek_po_kawie", state = "False", id = "160" },
    { type = "Trigger", name = "Odbyta akcja z Kafarami", state = "False", id = "161" },
    { type = "Trigger", name = "Fred gadal z Grabarzem o jego problemie", state = "False", id = "162" },
    { type = "Trigger", name = "Wystraszenie Natripowanych Idiotów", state = "False", id = "163" },
    { type = "Trigger", name = "Drabina oparta pod oknem", state = "False", id = "164" },
    { type = "Trigger", name = "Zalatwiona sprawa z Malwiną", state = "False", id = "165" },
    { type = "Trigger", name = "Akcja z wieczkiem dozwolona.", state = "False", id = "166" },
    { type = "Trigger", name = "DOM KOWALA", state = "False", id = "167" },
    { type = "Trigger", name = "SKRZYZOWANIE", state = "False", id = "168" },
    { type = "Trigger", name = "STODOLA", state = "False", id = "169" },
    { type = "Trigger", name = "OBOZ HIPPISOW", state = "False", id = "170" },
    { type = "Trigger", name = "DOM LEKARZA", state = "False", id = "171" },
    { type = "Trigger", name = "OGROD ZA DOMEM LEKARZA", state = "False", id = "172" },
    { type = "Trigger", name = "STACJA BENZYNOWA", state = "False", id = "173" },
    { type = "Trigger", name = "STODOLA PO CIEMKU", state = "False", id = "174" },
    { type = "Trigger", name = "TOALETA", state = "False", id = "175" },
    { type = "Trigger", name = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM", state = "False", id = "176" },
    { type = "Trigger", name = "CMENTARZ", state = "False", id = "177" },
    { type = "Trigger", name = "STARSZA CZESC CMENTARZA", state = "False", id = "178" },
    { type = "Trigger", name = "LAKA", state = "False", id = "179" },
    { type = "Trigger", name = "DOM Z POKOJEM NA PIETRZE", state = "False", id = "180" },
    { type = "Trigger", name = "LESNA DROGA Z WOJSKOWYM JEEPEM", state = "False", id = "181" },
    { type = "Trigger", name = "DOM KOWALA_visited", state = "False", id = "182" },
    { type = "Trigger", name = "SKRZYZOWANIE_visited", state = "False", id = "183" },
    { type = "Trigger", name = "STODOLA _visited", state = "False", id = "184" },
    { type = "Trigger", name = "OBOZ HIPPISOW_visited", state = "False", id = "185" },
    { type = "Trigger", name = "DOM LEKARZA_visited", state = "False", id = "186" },
    { type = "Trigger", name = "OGROD ZA DOMEM LEKARZA_visited", state = "False", id = "187" },
    { type = "Trigger", name = "STACJA BENZYNOWA_visited", state = "False", id = "188" },
    { type = "Trigger", name = "STODOLA PO CIEMKU_visited", state = "False", id = "189" },
    { type = "Trigger", name = "TOALETA_visited", state = "False", id = "190" },
    { type = "Trigger", name = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM_visited", state = "False", id = "191" },
    { type = "Trigger", name = "CMENTARZ_visited", state = "False", id = "192" },
    { type = "Trigger", name = "STARSZA CZESC CMENTARZA_visited", state = "False", id = "193" },
    { type = "Trigger", name = "LAKA_visited", state = "False", id = "194" },
    { type = "Trigger", name = "DOM Z POKOJEM NA PIETRZE_visited", state = "False", id = "195" },
    { type = "Trigger", name = "LESNA DROGA Z WOJSKOWYM JEEPEM_visited", state = "False", id = "196" },
    { type = "Trigger", name = "DOM KOWALA_inactive", state = "False", id = "197" },
    { type = "Trigger", name = "SKRZYZOWANIE_inactive", state = "False", id = "198" },
    { type = "Trigger", name = "STODOLA _inactive", state = "False", id = "199" },
    { type = "Trigger", name = "OBOZ HIPPISOW_inactive", state = "False", id = "200" },
    { type = "Trigger", name = "DOM LEKARZA_inactive", state = "False", id = "201" },
    { type = "Trigger", name = "OGROD ZA DOMEM LEKARZA_inactive", state = "False", id = "202" },
    { type = "Trigger", name = "STACJA BENZYNOWA_inactive", state = "False", id = "203" },
    { type = "Trigger", name = "STODOLA PO CIEMKU_inactive", state = "False", id = "204" },
    { type = "Trigger", name = "TOALETA_inactive", state = "False", id = "205" },
    { type = "Trigger", name = "PRZEJSCIE MIEDZY TOALETA A CMENTARZEM_inactive", state = "False", id = "206" },
    { type = "Trigger", name = "CMENTARZ_inactive", state = "False", id = "207" },
    { type = "Trigger", name = "STARSZA CZESC CMENTARZA_inactive", state = "False", id = "208" },
    { type = "Trigger", name = "LAKA_inactive", state = "False", id = "209" },
    { type = "Trigger", name = "DOM Z POKOJEM NA PIETRZE_inactive", state = "False", id = "210" },
    { type = "Trigger", name = "LESNA DROGA Z WOJSKOWYM JEEPEM_inactive", state = "False", id = "211" },
    { type = "Trigger", name = "Fred nakarmł Świadka.", state = "False", id = "212" },
    { type = "Trigger", name = "Ryba_upieczona", state = "False", id = "213" },
    { type = "Trigger", name = "Koniec akcji z kowalem.", state = "False", id = "214" },
    { type = "Trigger", name = "Akcja z kowalem część druga", state = "False", id = "215" },
    { type = "Trigger", name = "Fred dostał właśnie od Kowala glejt", state = "False", id = "216" },
    { type = "Trigger", name = "Fura_ma_otwarty_bagaznik", state = "False", id = "217" },
    { type = "Trigger", name = "gasnica jest zabrana", state = "False", id = "218" },
    { type = "Trigger", name = "Gasnica", state = "False", id = "219" },
    { type = "Trigger", name = "Niebo", state = "False", id = "220" },
    { type = "Trigger", name = "Pieklo", state = "False", id = "221" },
    { type = "Trigger", name = "Polana z grobem", state = "False", id = "222" },
    { type = "Trigger", name = "Drozka na skraju lasu", state = "False", id = "223" },
    { type = "Trigger", name = "Droga z autem", state = "False", id = "224" },
    { type = "Trigger", name = "Wnetrze samochodu", state = "False", id = "225" },
    { type = "Trigger", name = "Brama przy rakowieckiej", state = "False", id = "226" },
    { type = "Trigger", name = "Niebo_visited", state = "False", id = "227" },
    { type = "Trigger", name = "Pieklo_visited", state = "False", id = "228" },
    { type = "Trigger", name = "Polana z grobem_visited", state = "False", id = "229" },
    { type = "Trigger", name = "Drozka na skraju lasu_visited", state = "False", id = "230" },
    { type = "Trigger", name = "Droga z autem_visited", state = "False", id = "231" },
    { type = "Trigger", name = "Wnetrze samochodu_visited", state = "False", id = "232" },
    { type = "Trigger", name = "Brama przy rakowieckiej_visited", state = "False", id = "233" },
    { type = "Trigger", name = "Niebo_inactive", state = "False", id = "234" },
    { type = "Trigger", name = "Pieklo_inactive", state = "False", id = "235" },
    { type = "Trigger", name = "Polana z grobem_inactive", state = "False", id = "236" },
    { type = "Trigger", name = "Drozka na skraju lasu_inactive", state = "False", id = "237" },
    { type = "Trigger", name = "Droga z autem_inactive", state = "False", id = "238" },
    { type = "Trigger", name = "Wnetrze samochodu_inactive", state = "False", id = "239" },
    { type = "Trigger", name = "Brama przy rakowieckiej_inactive", state = "False", id = "240" },
    { type = "Trigger", name = "juz_po_odwiedzeniu_piekla", state = "False", id = "241" },
    { type = "Trigger", name = "schowek jest otwarty", state = "False", id = "242" },
    { type = "Trigger", name = "tupecik jest juz zabrany", state = "False", id = "243" },
    { type = "Trigger", name = "odegralem pobudke po piekle", state = "False", id = "244" },
    { type = "Trigger", name = "100_neuro", state = "False", id = "245" },
    { type = "Trigger", name = "Kula u Winyla obraca sie", state = "True", id = "246" },
    { type = "Trigger", name = "RAKOWIECKA", state = "True", id = "247" },
    { type = "Trigger", name = "RAKOWIECKA_visited", state = "False", id = "248" },
    { type = "Trigger", name = "RAKOWIECKA_inactive", state = "False", id = "249" },
    { type = "Trigger", name = "Fred gadał z Malwiną o podarunku od Lekarza", state = "False", id = "250" },
    { type = "Trigger", name = "Fred dał Grabarzowi łopatę", state = "False", id = "251" },
    { type = "Trigger", name = "Rybak wypił kawę", state = "False", id = "252" },
    { type = "Trigger", name = "Zapalenie światła w stodole", state = "False", id = "253" },
    { type = "Trigger", name = "Akcja z gangsterami", state = "False", id = "254" },
    { type = "Trigger", name = "Wtracenie watku z odeslaniem Kafarow na boisku szkolnym", state = "False", id = "255" },
    { type = "Trigger", name = "Pierwsza rozmowa z Nukem", state = "False", id = "256" },
    { type = "Trigger", name = "Pierwsza istotna rozmowa z Kelnerem", state = "False", id = "257" },
    { type = "Trigger", name = "Rozmowa Z FZB przy kapliczce", state = "False", id = "258" },
    { type = "Trigger", name = "Druga istotna rozmowa z Kelnerem", state = "False", id = "259" },
    { type = "Trigger", name = "Rozmowa z DJ Radiowym", state = "False", id = "260" },
    { type = "Trigger", name = "Przybycie poslanca", state = "False", id = "261" },
    { type = "Trigger", name = "Rozmowa z DJ Hajsem", state = "False", id = "262" },
    { type = "Trigger", name = "pierwsza rozmowa z tow. Romanem", state = "False", id = "263" },
    { type = "Trigger", name = "Dezaktywacja kota tow. Romana", state = "False", id = "264" },
    { type = "Trigger", name = "Odwdzieczenie sie tow. Romana", state = "False", id = "265" },
    { type = "Trigger", name = "Przekazanie plyty z hejnałem DJRadiowemu", state = "False", id = "266" },
    { type = "Trigger", name = "Zamowienie liny", state = "False", id = "267" },
    { type = "Trigger", name = "Rozmowa z Aldoną", state = "False", id = "268" },
    { type = "Trigger", name = "Pobudka Aldony", state = "False", id = "269" },
    { type = "Trigger", name = "oddalismy Aldonie linę", state = "False", id = "270" },
    { type = "Trigger", name = "oddalismy Aldonie plan klasztoru", state = "False", id = "271" },
    { type = "Trigger", name = "Sforsowanie bram Zlomowiska", state = "False", id = "272" },
    { type = "Trigger", name = "Po pierwszej gadce z pijącymi piwo", state = "False", id = "273" },
    { type = "Trigger", name = "Spodek", state = "False", id = "274" },
    { type = "Trigger", name = "Nadawanie hejnału trwa", state = "False", id = "275" },
    { type = "Trigger", name = "Odczytanie numeru z książki telefonicznej", state = "False", id = "276" },
    { type = "Trigger", name = "Start Aktu 3", state = "True", id = "277" },
    { type = "Trigger", name = "Kurier z liną czeka pod Rozgłośnią", state = "False", id = "278" },
    { type = "Trigger", name = "Utrata miesa", state = "False", id = "279" },
    { type = "Trigger", name = "Otrucie psów na Złomowisku", state = "False", id = "280" },
    { type = "Trigger", name = "Triger do reakcji na dmuchany materac", state = "False", id = "281" },
    { type = "Trigger", name = "Srodki nasenne", state = "False", id = "282" },
    { type = "Trigger", name = "Spodek_z_mlekiem", state = "False", id = "283" },
    { type = "Trigger", name = "Przekazanie DJHajsowi igły", state = "False", id = "284" },
    { type = "Trigger", name = "Odbedzie sie Spotkanie z Poslancem", state = "False", id = "285" },
    { type = "Trigger", name = "Fred wychodzi przez lufcik", state = "False", id = "286" },
    { type = "Trigger", name = "Fred wchodzi przez lufcik do toalety", state = "False", id = "287" },
    { type = "Trigger", name = "Stringi", state = "False", id = "288" },
    { type = "Trigger", name = "Magnes_z_igla", state = "False", id = "289" },
    { type = "Trigger", name = "Butelka_po_mleku", state = "False", id = "290" },
    { type = "Trigger", name = "Butelka_z_woda", state = "False", id = "291" },
    { type = "Trigger", name = "Komiks1", state = "False", id = "292" },
    { type = "Trigger", name = "Komiks1_visited", state = "False", id = "293" },
    { type = "Trigger", name = "Komiks2", state = "False", id = "294" },
    { type = "Trigger", name = "Komiks2_visited", state = "False", id = "295" },
    { type = "Trigger", name = "Zdobycie gumiaków", state = "False", id = "296" },
    { type = "Trigger", name = "znikniecie licealistow1", state = "False", id = "297" },
    { type = "Trigger", name = "Wlasciwy_kluczyk", state = "False", id = "298" },
    { type = "Trigger", name = "Pierwsza rozmowa z Wojarską", state = "False", id = "299" },
    { type = "Trigger", name = "Final", state = "False", id = "300" },
    { type = "Trigger", name = "Odbyła się akcja w kafeii", state = "False", id = "301" },
    { type = "Trigger", name = "Rozmowa z textylia", state = "False", id = "302" },
    { type = "Trigger", name = "Ogranie licealistów", state = "False", id = "303" },
    { type = "Trigger", name = "Druga gadka z elektronikiem odbyła się", state = "False", id = "304" },
    { type = "Trigger", name = "Dostaliśmy kadłub maszynki", state = "False", id = "305" },
    { type = "Trigger", name = "Wrota stodoły zamkniete", state = "True", id = "306" },
    { type = "Trigger", name = "Wrota stodoły otwarte - ciemne", state = "False", id = "307" },
    { type = "Trigger", name = "Wrota stodoły otwarte - jasne", state = "False", id = "308" },
    { type = "Trigger", name = "Druga gadka ze Swiadkiem", state = "False", id = "309" },
    { type = "Trigger", name = "hidemap", state = "False", id = "310" },
    { type = "Trigger", name = "PARKING PRZY ROZGLOSNI RADIOWEJ", state = "False", id = "311" },
    { type = "Trigger", name = "PODJAZD POD KLASZTOREM", state = "False", id = "312" },
    { type = "Trigger", name = "ROZGLOSNIA RADIOWA", state = "False", id = "313" },
    { type = "Trigger", name = "ZAJAZD", state = "False", id = "314" },
    { type = "Trigger", name = "POKOJ NA PIETRZE ZAJAZDU", state = "False", id = "315" },
    { type = "Trigger", name = "ZLOMOWISKO", state = "False", id = "316" },
    { type = "Trigger", name = "KAPLICZKA ZA MIASTEM", state = "False", id = "317" },
    { type = "Trigger", name = "PODWORZE ZA TYMZE DOMEM", state = "False", id = "318" },
    { type = "Trigger", name = "MUSZLA KONCERTOWA", state = "False", id = "319" },
    { type = "Trigger", name = "PLAC PRZED ZAJAZDEM", state = "False", id = "320" },
    { type = "Trigger", name = "KORYTARZ KLASZTORNY", state = "False", id = "321" },
    { type = "Trigger", name = "BLOKADA NA DRODZE", state = "False", id = "322" },
    { type = "Trigger", name = "BIBLIOTEKA", state = "False", id = "323" },
    { type = "Trigger", name = "DOM Z BIALYCH DESEK", state = "False", id = "324" },
    { type = "Trigger", name = "POLANA ZA MUSZLA KONCERTOWA", state = "False", id = "325" },
    { type = "Trigger", name = "AKCJA W KLASZTORZE", state = "False", id = "326" },
    { type = "Trigger", name = "PARKING PRZY ROZGLOSNI RADIOWEJ_visited", state = "False", id = "327" },
    { type = "Trigger", name = "PODJAZD POD KLASZTOREM_visited", state = "False", id = "328" },
    { type = "Trigger", name = "ROZGLOSNIA RADIOWA_visited", state = "False", id = "329" },
    { type = "Trigger", name = "ZAJAZD_visited", state = "False", id = "330" },
    { type = "Trigger", name = "POKOJ NA PIETRZE ZAJAZDU_visited", state = "False", id = "331" },
    { type = "Trigger", name = "ZLOMOWISKO_visited", state = "False", id = "332" },
    { type = "Trigger", name = "KAPLICZKA ZA MIASTEM_visited", state = "False", id = "333" },
    { type = "Trigger", name = "PODWORZE ZA TYMZE DOMEM_visited", state = "False", id = "334" },
    { type = "Trigger", name = "MUSZLA KONCERTOWA_visited", state = "False", id = "335" },
    { type = "Trigger", name = "PLAC PRZED ZAJAZDEM_visited", state = "False", id = "336" },
    { type = "Trigger", name = "KORYTARZ KLASZTORNY_visited", state = "False", id = "337" },
    { type = "Trigger", name = "BLOKADA NA DRODZE_visited", state = "False", id = "338" },
    { type = "Trigger", name = "BIBLIOTEKA_visited", state = "False", id = "339" },
    { type = "Trigger", name = "DOM Z BIALYCH DESEK_visited", state = "False", id = "340" },
    { type = "Trigger", name = "POLANA ZA MUSZLA KONCERTOWA_visited", state = "False", id = "341" },
    { type = "Trigger", name = "AKCJA W KLASZTORZE_visited", state = "False", id = "342" },
    { type = "Trigger", name = "PARKING PRZY ROZGLOSNI RADIOWEJ_inactive", state = "False", id = "343" },
    { type = "Trigger", name = "PODJAZD POD KLASZTOREM_inactive", state = "False", id = "344" },
    { type = "Trigger", name = "ROZGLOSNIA RADIOWA_inactive", state = "False", id = "345" },
    { type = "Trigger", name = "ZAJAZD_inactive", state = "False", id = "346" },
    { type = "Trigger", name = "POKOJ NA PIETRZE ZAJAZDU_inactive", state = "False", id = "347" },
    { type = "Trigger", name = "ZLOMOWISKO_inactive", state = "False", id = "348" },
    { type = "Trigger", name = "KAPLICZKA ZA MIASTEM_inactive", state = "False", id = "349" },
    { type = "Trigger", name = "PODWORZE ZA TYMZE DOMEM_inactive", state = "False", id = "350" },
    { type = "Trigger", name = "MUSZLA KONCERTOWA_inactive", state = "False", id = "351" },
    { type = "Trigger", name = "PLAC PRZED ZAJAZDEM_inactive", state = "False", id = "352" },
    { type = "Trigger", name = "KORYTARZ KLASZTORNY_inactive", state = "False", id = "353" },
    { type = "Trigger", name = "BLOKADA NA DRODZE_inactive", state = "False", id = "354" },
    { type = "Trigger", name = "BIBLIOTEKA_inactive", state = "False", id = "355" },
    { type = "Trigger", name = "DOM Z BIALYCH DESEK_inactive", state = "False", id = "356" },
    { type = "Trigger", name = "POLANA ZA MUSZLA KONCERTOWA_inactive", state = "False", id = "357" },
    { type = "Trigger", name = "AKCJA W KLASZTORZE_inactive", state = "False", id = "358" },
    { type = "Trigger", name = "Trig techniczny", state = "False", id = "359" },
    { type = "Trigger", name = "Drzwi na stacje benzynowa otwarte", state = "False", id = "360" },
    { type = "Trigger", name = "odbyta 2 gadka z aldona", state = "False", id = "361" },
    { type = "Trigger", name = "Lekarz wyszedl", state = "False", id = "362" },
    { type = "Trigger", name = "Kot pije mleko", state = "False", id = "363" },
    { type = "Trigger", name = "W trakcie pojawiania zarosnietej sciezki", state = "False", id = "364" },
    { type = "Trigger", name = "Jorge wyszedl", state = "False", id = "365" },
    { type = "Trigger", name = "Dozwolone gadki z Yorkiem", state = "False", id = "366" },
    { type = "Trigger", name = "Pierwsze wejscie do stodoly", state = "False", id = "367" },
    { type = "Trigger", name = "Gadka z Aldoną o linie i planie klasztoru", state = "False", id = "368" },
    { type = "Trigger", name = "Odebrano plan klasztoru", state = "False", id = "369" },
    { type = "Trigger", name = "Triger do lepszej mapy wis w zajeździe", state = "False", id = "370" },
    { type = "Trigger", name = "TRIP_Kaczka odbyty", state = "False", id = "371" },
    { type = "Trigger", name = "TRIP_alien odbyty", state = "False", id = "372" },
    { type = "Trigger", name = "rybak zlecił przyniesienie kawy", state = "False", id = "373" },
    { type = "Trigger", name = "zabrałem już igłę", state = "False", id = "374" },
    { type = "Trigger", name = "KONIEC", state = "False", id = "375" },
    { type = "Trigger", name = "KONIEC_visited", state = "False", id = "376" },
    { type = "Trigger", name = "KONIEC_multivisited", state = "False", id = "377" },
    { type = "Trigger", name = "endgame", state = "False", id = "378" },
    { type = "Trigger", name = "wiemy już, że malwina to malwina", state = "False", id = "379" },
    { type = "Trigger", name = "jeszcze nie dostaliśmy karty ale już daliśmy hejnał", state = "False", id = "380" },
    { type = "Trigger", name = "dowiedzielismy sie wlasnie o wampirze ziem", state = "False", id = "381" },
    { type = "Trigger", name = "otwarta_brama w klasztorze", state = "False", id = "382" },
}